-- Real schedule data pipeline (Launch Readiness > Content & distribution,
-- Blocker): lineup/set-time data has lived as a hardcoded SETS array in
-- App.jsx, hand-edited every time a festival or year was added. That's fine
-- for a handful of days but doesn't scale, and it means shipping a new
-- festival's times requires a code change + redeploy instead of just adding
-- rows. Moves the factual part of that data (artist/day/stage/times/genre)
-- into a real table -- adding a festival/year going forward is a SQL
-- insert here, not an App.jsx edit.
--
-- match/sounds_like/sources are NOT real per-user data -- they're
-- simulated stand-ins for a recommendation engine that doesn't exist yet
-- (see the comment at the top of App.jsx). Carried over as-is so behavior
-- doesn't change, but they're demo values, not something a real "add a
-- festival" workflow needs to fill in truthfully.

create table if not exists festival_sets (
  id bigint primary key,
  festival_id text not null,
  day_id text not null,
  artist text not null,
  stage_id text not null,
  start_min integer not null,
  end_min integer not null,
  match integer,
  genre text,
  sounds_like text,
  sources text[] not null default '{}'
);

create index if not exists festival_sets_festival_idx on festival_sets (festival_id);

alter table festival_sets enable row level security;

-- Lineup data is public/promotional by nature (festivals publish their own
-- set times) -- readable by anyone, signed in or not. Writes only ever
-- happen from the SQL editor (or a future admin tool using the service
-- role), so there's deliberately no insert/update/delete policy here.
drop policy if exists "anyone can read festival sets" on festival_sets;
create policy "anyone can read festival sets"
  on festival_sets for select
  using (true);

insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(1, 'bonnaroo', 'fri', 'Dora Jar', 'that', 0, 45, 58, 'Indie Pop', null, '{}'),
(2, 'bonnaroo', 'fri', 'Villanelle', 'what', 45, 90, 44, 'Pop', null, '{}'),
(3, 'bonnaroo', 'fri', 'Lambrini Girls', 'which', 75, 120, 71, 'Punk', 'Raw, high-energy — close to your louder guitar picks', '{"soundcloud"}'),
(4, 'bonnaroo', 'fri', 'PawPaw Rod', 'that', 120, 165, 39, 'Hip-Hop', null, '{}'),
(5, 'bonnaroo', 'fri', 'Claire Rosinkranz', 'which', 135, 180, 52, 'Pop', null, '{}'),
(6, 'bonnaroo', 'fri', 'Amble', 'what', 135, 180, 83, 'Indie Folk', 'Close to your Bon Iver / Fleet Foxes listening', '{"spotify"}'),
(7, 'bonnaroo', 'fri', 'Blues Traveler', 'what', 225, 285, 47, 'Rock', null, '{}'),
(8, 'bonnaroo', 'fri', 'Zack Fox', 'other', 240, 285, 65, 'Hip-Hop', 'You''ve streamed a couple of his guest verses', '{"spotify"}'),
(9, 'bonnaroo', 'fri', 'Rachel Chinouriri', 'this', 255, 300, 79, 'Indie Pop', 'Like Holly Humberstone, more upbeat', '{"spotify","soundcloud"}'),
(10, 'bonnaroo', 'fri', 'Wet Leg', 'which', 300, 360, 94, 'Indie Rock', 'Your #3 most-played artist this year', '{"spotify","soundcloud"}'),
(11, 'bonnaroo', 'fri', 'Mother Mother', 'this', 300, 360, 88, 'Indie Rock', 'Heavy rotation for you the past few months', '{"spotify"}'),
(12, 'bonnaroo', 'fri', 'Łaszewo', 'other', 300, 360, 69, 'Electronic', 'New territory, close to your SoundCloud follows', '{"soundcloud"}'),
(13, 'bonnaroo', 'fri', 'Yungblud', 'what', 345, 405, 73, 'Alt Rock', 'Overlaps with your rock-leaning playlists', '{"spotify"}'),
(14, 'bonnaroo', 'fri', 'Jessie Murph', 'which', 420, 480, 61, 'Pop / Country', null, '{}'),
(15, 'bonnaroo', 'fri', 'GRiZ', 'what', 465, 540, 97, 'Funk / Electronic', 'Your #1 most-played artist this year', '{"spotify","soundcloud"}'),
(16, 'bonnaroo', 'fri', 'The Strokes', 'what', 600, 675, 91, 'Rock', 'Your #2 most-played artist this year', '{"spotify"}'),
(17, 'bonnaroo', 'thu', 'Spiritual Cramp', 'what', 0, 60, 42, 'Punk', null, '{}'),
(18, 'bonnaroo', 'thu', 'Vince Staples', 'what', 90, 150, 68, 'Hip-Hop', 'You''ve streamed a few of his early albums', '{"spotify"}'),
(19, 'bonnaroo', 'thu', 'Four Tet', 'what', 180, 270, 95, 'Electronic', 'Heavy rotation for you lately', '{"spotify","soundcloud"}'),
(20, 'bonnaroo', 'thu', 'Skrillex', 'what', 300, 390, 89, 'Dubstep / Electronic', 'Big part of your electronic listening history', '{"spotify"}'),
(21, 'bonnaroo', 'sat', 'Sunami', 'this', 0, 45, 35, 'Hardcore', null, '{}'),
(22, 'bonnaroo', 'sat', 'Midnight Generation', 'what', 60, 105, 55, 'Indie Rock', null, '{}'),
(23, 'bonnaroo', 'sat', 'Arcy Drive', 'what', 150, 195, 61, 'Alt Rock', null, '{}'),
(24, 'bonnaroo', 'sat', 'Tash Sultana', 'what', 240, 300, 86, 'Psychedelic Soul', 'Overlaps with your looping / psych-leaning playlists', '{"spotify"}'),
(25, 'bonnaroo', 'sat', 'Trixie Mattel', 'that', 195, 255, 30, 'Comedy / Variety', null, '{}'),
(26, 'bonnaroo', 'sat', 'Holly Humberstone', 'which', 195, 255, 77, 'Indie Pop', 'Similar to Rachel Chinouriri, who you caught Friday', '{"spotify"}'),
(27, 'bonnaroo', 'sat', 'Passion Pit', 'this', 360, 420, 72, 'Indie Electropop', 'Nostalgic indie-electropop you still revisit', '{"spotify"}'),
(28, 'bonnaroo', 'sat', 'Alabama Shakes', 'what', 360, 420, 91, 'Rock / Soul', 'Your SoundCloud follows lean into this soul-rock sound', '{"soundcloud"}'),
(29, 'bonnaroo', 'sat', 'The Neighbourhood', 'what', 480, 555, 66, 'Alt Rock', null, '{}'),
(30, 'bonnaroo', 'sat', 'Kesha Presents: Superjam', 'this', 480, 585, 58, 'Pop (special set)', null, '{}'),
(31, 'bonnaroo', 'sat', 'Teddy Swims', 'which', 540, 615, 74, 'Soul / Pop', 'Close to your soul/pop crossover picks', '{"spotify"}'),
(32, 'bonnaroo', 'sat', 'Sara Landry', 'other', 555, 645, 82, 'Techno', 'New territory, close to your SoundCloud follows', '{"soundcloud"}'),
(33, 'bonnaroo', 'sat', 'RÜFÜS DU SOL', 'what', 625, 715, 98, 'Electronic', 'Your #1 most-played artist this weekend', '{"spotify","soundcloud"}'),
(34, 'bonnaroo', 'sun', 'Spacey Jane', 'which', 0, 60, 70, 'Indie Rock', null, '{}'),
(35, 'bonnaroo', 'sun', 'Blondshell', 'that', 15, 60, 80, 'Indie Rock', 'Close to Wet Leg, who you caught Friday', '{"spotify"}'),
(36, 'bonnaroo', 'sun', 'Trombone Shorty', 'what', 60, 120, 48, 'Funk / Jazz', null, '{}'),
(37, 'bonnaroo', 'sun', 'Japanese Breakfast', 'which', 105, 165, 92, 'Indie Pop', 'Heavy rotation for you the past few months', '{"spotify","soundcloud"}'),
(38, 'bonnaroo', 'sun', 'Tedeschi Trucks Band', 'what', 165, 225, 53, 'Blues Rock', null, '{}'),
(39, 'bonnaroo', 'sun', 'Turnover', 'this', 225, 285, 64, 'Dream Pop', null, '{}'),
(40, 'bonnaroo', 'sun', 'Del Water Gap', 'that', 225, 285, 76, 'Indie Pop', 'Close to your Amble listening from Friday', '{"spotify"}'),
(41, 'bonnaroo', 'sun', 'Clipse', 'which', 225, 285, 71, 'Hip-Hop', 'A few of their tracks are in your playlists', '{"spotify"}'),
(42, 'bonnaroo', 'sun', 'Role Model', 'what', 285, 345, 59, 'Pop', null, '{}'),
(43, 'bonnaroo', 'sun', 'Modest Mouse', 'this', 330, 405, 84, 'Indie Rock', 'Your indie rock taste lines up well here', '{"spotify"}'),
(44, 'bonnaroo', 'sun', 'Kesha', 'which', 345, 405, 67, 'Pop', null, '{}'),
(45, 'bonnaroo', 'sun', 'Mariah the Scientist', 'that', 345, 420, 73, 'R&B', 'Close to your R&B listening on SoundCloud', '{"soundcloud"}'),
(46, 'bonnaroo', 'sun', 'Noah Kahan', 'what', 405, 480, 96, 'Folk Pop', 'Your #2 most-played artist this weekend', '{"spotify"}'),
(47, 'coachella', 'fri', 'Dabeull', 'outdoor', 0, 50, 44, 'French House / Funk', null, '{}'),
(48, 'coachella', 'fri', 'Youna', 'sahara', 0, 50, 38, 'Pop', null, '{}'),
(49, 'coachella', 'fri', 'Bob Baker Marionettes', 'gobi', 0, 40, 25, 'Variety / Puppetry', null, '{}'),
(50, 'coachella', 'fri', 'Wednesday', 'sonora', 0, 40, 78, 'Indie Rock', 'Close to Wet Leg and other fuzzy indie rock you like', '{"spotify"}'),
(51, 'coachella', 'fri', 'BINI', 'mojave', 15, 60, 41, 'P-Pop', null, '{}'),
(52, 'coachella', 'fri', 'NewDad', 'gobi', 45, 85, 69, 'Shoegaze / Indie', 'Overlaps with your dreamier indie rock listening', '{"soundcloud"}'),
(53, 'coachella', 'fri', 'HUGEL', 'sahara', 50, 110, 55, 'House', null, '{}'),
(54, 'coachella', 'fri', 'Fleshwater', 'sonora', 50, 90, 47, 'Shoegaze / Metal', null, '{}'),
(55, 'coachella', 'fri', 'Tiga', 'quasar', 60, 180, 62, 'Electro / House', null, '{}'),
(56, 'coachella', 'fri', 'Lykke Li', 'outdoor', 80, 130, 74, 'Indie Pop', 'Close to Rachel Chinouriri, who you caught at Bonnaroo', '{"spotify"}'),
(57, 'coachella', 'fri', 'Teddy Swims', 'coachella-stage', 90, 140, 71, 'Soul / Pop', 'Close to your soul/pop crossover picks', '{"spotify"}'),
(58, 'coachella', 'fri', 'Central Cee', 'mojave', 90, 135, 66, 'UK Hip-Hop', null, '{}'),
(59, 'coachella', 'fri', 'Joyce Manor', 'gobi', 90, 130, 58, 'Emo / Indie Rock', null, '{}'),
(60, 'coachella', 'fri', 'The Two Lips', 'sonora', 120, 160, 33, 'Pop', null, '{}'),
(61, 'coachella', 'fri', 'The xx', 'coachella-stage', 180, 240, 90, 'Indie Electronic', 'Your #1 most-played artist a few years running', '{"spotify","soundcloud"}'),
(62, 'coachella', 'fri', 'Sabrina Carpenter', 'coachella-stage', 305, 395, 88, 'Pop', 'One of your most-streamed pop artists this year', '{"spotify"}'),
(63, 'coachella', 'fri', 'Anyma', 'coachella-stage', 480, 570, 93, 'Melodic Techno / Audiovisual', 'Your SoundCloud follows lean heavily into this sound', '{"soundcloud"}'),
(64, 'coachella', 'sat', 'Jack White', 'mojave', 0, 45, 82, 'Rock / Blues', 'Overlaps with your rock and blues-leaning listening', '{"spotify"}'),
(65, 'coachella', 'sat', 'Los Hermanos Flores', 'outdoor', 60, 105, 40, 'Latin / Cumbia', null, '{}'),
(66, 'coachella', 'sat', 'Alex G', 'outdoor', 130, 175, 77, 'Indie Rock', 'Consistent with your lo-fi indie rock taste', '{"spotify"}'),
(67, 'coachella', 'sat', 'Addison Rae', 'coachella-stage', 150, 195, 54, 'Pop', null, '{}'),
(68, 'coachella', 'sat', 'Geese', 'gobi', 195, 240, 72, 'Indie Rock', 'Fits your fuzzy indie rock taste', '{"spotify"}'),
(69, 'coachella', 'sat', 'Blondshell', 'outdoor', 190, 235, 85, 'Indie Rock', 'You caught her Sunday at Bonnaroo — recurring favorite', '{"spotify"}'),
(70, 'coachella', 'sat', 'Giveon', 'coachella-stage', 240, 285, 68, 'R&B', 'Close to your R&B listening on SoundCloud', '{"soundcloud"}'),
(71, 'coachella', 'sat', 'Sombr', 'outdoor', 245, 290, 63, 'Indie Pop', null, '{}'),
(72, 'coachella', 'sat', 'Nine Inch Noize', 'sahara', 300, 360, 89, 'Industrial / Electronic', 'New territory but close to your industrial/electronic edges', '{"soundcloud"}'),
(73, 'coachella', 'sat', 'The Strokes', 'coachella-stage', 360, 410, 95, 'Rock', 'You caught them Friday at Bonnaroo — clearly a top artist for you', '{"spotify"}'),
(74, 'coachella', 'sat', 'David Guetta', 'quasar', 360, 450, 45, 'House / EDM', null, '{}'),
(75, 'coachella', 'sat', 'PinkPantheress', 'gobi', 355, 400, 59, 'Pop / UK Garage', null, '{}'),
(76, 'coachella', 'sat', 'Labrinth', 'outdoor', 330, 375, 66, 'Alt R&B / Pop', null, '{}'),
(77, 'coachella', 'sat', 'Interpol', 'mojave', 435, 480, 60, 'Post-Punk', null, '{}'),
(78, 'coachella', 'sat', 'David Byrne', 'outdoor', 440, 490, 58, 'Art Rock', null, '{}'),
(79, 'coachella', 'sat', 'Justin Bieber', 'coachella-stage', 505, 580, 71, 'Pop', null, '{}'),
(80, 'coachella', 'sun', 'Tijuana Panthers', 'coachella-stage', 0, 45, 36, 'Surf Rock', null, '{}'),
(81, 'coachella', 'sun', 'Gigi Perez', 'outdoor', 0, 45, 75, 'Indie Pop', 'Close to your softer indie pop picks', '{"spotify"}'),
(82, 'coachella', 'sun', 'Wet Leg', 'coachella-stage', 45, 90, 97, 'Indie Rock', 'You caught them Friday at Bonnaroo — your #3 most-played artist this year', '{"spotify","soundcloud"}'),
(83, 'coachella', 'sun', 'Clipse', 'outdoor', 75, 120, 74, 'Hip-Hop', 'You caught them Sunday at Bonnaroo too', '{"spotify"}'),
(84, 'coachella', 'sun', 'Major Lazer', 'coachella-stage', 130, 175, 64, 'Dancehall / Electronic', null, '{}'),
(85, 'coachella', 'sun', 'Foster the People', 'outdoor', 165, 210, 69, 'Indie Pop / Rock', null, '{}'),
(86, 'coachella', 'sun', 'Drain', 'gobi', 240, 285, 52, 'Hardcore Punk', null, '{}'),
(87, 'coachella', 'sun', 'Young Thug', 'coachella-stage', 230, 275, 57, 'Hip-Hop', null, '{}'),
(88, 'coachella', 'sun', 'Laufey', 'outdoor', 280, 325, 86, 'Jazz Pop', 'Overlaps with your jazzier, softer listening moods', '{"spotify"}'),
(89, 'coachella', 'sun', 'Glitterer', 'gobi', 375, 420, 65, 'Indie Rock / Punk', null, '{}'),
(90, 'coachella', 'sun', 'Karol G', 'coachella-stage', 355, 430, 80, 'Reggaeton / Latin Pop', 'Outside your usual genres but heavily hyped in your circles', '{"spotify"}'),
(91, 'coachella', 'sun', 'BIGBANG', 'outdoor', 390, 450, 48, 'K-Pop', null, '{}'),
(92, 'coachella', 'fri2', 'Dabeull', 'outdoor', 0, 50, 44, 'French House / Funk', null, '{}'),
(93, 'coachella', 'fri2', 'Youna', 'sahara', 0, 50, 38, 'Pop', null, '{}'),
(94, 'coachella', 'fri2', 'Bob Baker Marionettes', 'gobi', 0, 40, 25, 'Variety / Puppetry', null, '{}'),
(95, 'coachella', 'fri2', 'Wednesday', 'sonora', 0, 40, 78, 'Indie Rock', 'Close to Wet Leg and other fuzzy indie rock you like', '{"spotify"}'),
(96, 'coachella', 'fri2', 'BINI', 'mojave', 15, 60, 41, 'P-Pop', null, '{}'),
(97, 'coachella', 'fri2', 'NewDad', 'gobi', 45, 85, 69, 'Shoegaze / Indie', 'Overlaps with your dreamier indie rock listening', '{"soundcloud"}'),
(98, 'coachella', 'fri2', 'HUGEL', 'sahara', 50, 110, 55, 'House', null, '{}'),
(99, 'coachella', 'fri2', 'Fleshwater', 'sonora', 50, 90, 47, 'Shoegaze / Metal', null, '{}'),
(100, 'coachella', 'fri2', 'Tiga', 'quasar', 60, 180, 62, 'Electro / House', null, '{}'),
(101, 'coachella', 'fri2', 'Lykke Li', 'outdoor', 80, 130, 74, 'Indie Pop', 'Close to Rachel Chinouriri, who you caught at Bonnaroo', '{"spotify"}'),
(102, 'coachella', 'fri2', 'Teddy Swims', 'coachella-stage', 90, 140, 71, 'Soul / Pop', 'Close to your soul/pop crossover picks', '{"spotify"}'),
(103, 'coachella', 'fri2', 'Central Cee', 'mojave', 90, 135, 66, 'UK Hip-Hop', null, '{}'),
(104, 'coachella', 'fri2', 'Joyce Manor', 'gobi', 90, 130, 58, 'Emo / Indie Rock', null, '{}'),
(105, 'coachella', 'fri2', 'The Two Lips', 'sonora', 120, 160, 33, 'Pop', null, '{}'),
(106, 'coachella', 'fri2', 'The xx', 'coachella-stage', 180, 240, 90, 'Indie Electronic', 'Your #1 most-played artist a few years running', '{"spotify","soundcloud"}'),
(107, 'coachella', 'fri2', 'Sabrina Carpenter', 'coachella-stage', 305, 395, 88, 'Pop', 'One of your most-streamed pop artists this year', '{"spotify"}'),
(108, 'coachella', 'fri2', 'Anyma', 'coachella-stage', 480, 570, 93, 'Melodic Techno / Audiovisual', 'Your SoundCloud follows lean heavily into this sound', '{"soundcloud"}'),
(109, 'coachella', 'sat2', 'Jack White', 'mojave', 0, 45, 82, 'Rock / Blues', 'Overlaps with your rock and blues-leaning listening', '{"spotify"}'),
(110, 'coachella', 'sat2', 'Los Hermanos Flores', 'outdoor', 60, 105, 40, 'Latin / Cumbia', null, '{}'),
(111, 'coachella', 'sat2', 'Alex G', 'outdoor', 130, 175, 77, 'Indie Rock', 'Consistent with your lo-fi indie rock taste', '{"spotify"}'),
(112, 'coachella', 'sat2', 'Addison Rae', 'coachella-stage', 150, 195, 54, 'Pop', null, '{}'),
(113, 'coachella', 'sat2', 'Geese', 'gobi', 195, 240, 72, 'Indie Rock', 'Fits your fuzzy indie rock taste', '{"spotify"}'),
(114, 'coachella', 'sat2', 'Blondshell', 'outdoor', 190, 235, 85, 'Indie Rock', 'You caught her Sunday at Bonnaroo — recurring favorite', '{"spotify"}'),
(115, 'coachella', 'sat2', 'Giveon', 'coachella-stage', 240, 285, 68, 'R&B', 'Close to your R&B listening on SoundCloud', '{"soundcloud"}'),
(116, 'coachella', 'sat2', 'Sombr', 'outdoor', 245, 290, 63, 'Indie Pop', null, '{}'),
(117, 'coachella', 'sat2', 'Nine Inch Noize', 'sahara', 300, 360, 89, 'Industrial / Electronic', 'New territory but close to your industrial/electronic edges', '{"soundcloud"}'),
(118, 'coachella', 'sat2', 'The Strokes', 'coachella-stage', 360, 410, 95, 'Rock', 'You caught them Friday at Bonnaroo — clearly a top artist for you', '{"spotify"}'),
(119, 'coachella', 'sat2', 'David Guetta', 'quasar', 360, 450, 45, 'House / EDM', null, '{}'),
(120, 'coachella', 'sat2', 'PinkPantheress', 'gobi', 355, 400, 59, 'Pop / UK Garage', null, '{}'),
(121, 'coachella', 'sat2', 'Labrinth', 'outdoor', 330, 375, 66, 'Alt R&B / Pop', null, '{}'),
(122, 'coachella', 'sat2', 'Interpol', 'mojave', 435, 480, 60, 'Post-Punk', null, '{}'),
(123, 'coachella', 'sat2', 'David Byrne', 'outdoor', 440, 490, 58, 'Art Rock', null, '{}'),
(124, 'coachella', 'sat2', 'Justin Bieber', 'coachella-stage', 505, 580, 71, 'Pop', null, '{}'),
(125, 'coachella', 'sun2', 'Tijuana Panthers', 'coachella-stage', 0, 45, 36, 'Surf Rock', null, '{}'),
(126, 'coachella', 'sun2', 'Gigi Perez', 'outdoor', 0, 45, 75, 'Indie Pop', 'Close to your softer indie pop picks', '{"spotify"}'),
(127, 'coachella', 'sun2', 'Wet Leg', 'coachella-stage', 45, 90, 97, 'Indie Rock', 'You caught them Friday at Bonnaroo — your #3 most-played artist this year', '{"spotify","soundcloud"}'),
(128, 'coachella', 'sun2', 'Clipse', 'outdoor', 75, 120, 74, 'Hip-Hop', 'You caught them Sunday at Bonnaroo too', '{"spotify"}'),
(129, 'coachella', 'sun2', 'Major Lazer', 'coachella-stage', 130, 175, 64, 'Dancehall / Electronic', null, '{}'),
(130, 'coachella', 'sun2', 'Foster the People', 'outdoor', 165, 210, 69, 'Indie Pop / Rock', null, '{}'),
(131, 'coachella', 'sun2', 'Drain', 'gobi', 240, 285, 52, 'Hardcore Punk', null, '{}'),
(132, 'coachella', 'sun2', 'Young Thug', 'coachella-stage', 230, 275, 57, 'Hip-Hop', null, '{}'),
(133, 'coachella', 'sun2', 'Laufey', 'outdoor', 280, 325, 86, 'Jazz Pop', 'Overlaps with your jazzier, softer listening moods', '{"spotify"}'),
(134, 'coachella', 'sun2', 'Glitterer', 'gobi', 375, 420, 65, 'Indie Rock / Punk', null, '{}'),
(135, 'coachella', 'sun2', 'Karol G', 'coachella-stage', 355, 430, 80, 'Reggaeton / Latin Pop', 'Outside your usual genres but heavily hyped in your circles', '{"spotify"}'),
(136, 'coachella', 'sun2', 'BIGBANG', 'outdoor', 390, 450, 48, 'K-Pop', null, '{}'),
(137, 'electric-forest', 'thu', 'EFFIN', 'ranch', 0, 75, 58, 'Bass / Dubstep', null, '{}'),
(138, 'electric-forest', 'thu', 'Midnight Generation', 'ranch', 105, 165, 71, 'Indie Rock', 'You caught them at Bonnaroo too — recurring pick for you', '{"spotify"}'),
(139, 'electric-forest', 'thu', 'Disco Lines', 'ranch', 195, 270, 84, 'Tech House / Bass', 'Overlaps with your tech house listening', '{"soundcloud"}'),
(140, 'electric-forest', 'thu', 'Excision', 'ranch', 360, 450, 93, 'Dubstep', 'Lost Lands'' headliner and a heavy part of your bass rotation', '{"spotify","soundcloud"}'),
(141, 'electric-forest', 'thu', 'Eggy', 'sherwood', 30, 105, 45, 'Jam Band', null, '{}'),
(142, 'electric-forest', 'thu', 'Night Tapes', 'sherwood', 150, 210, 76, 'Dream Pop / Electronic', 'Close to your dreamier indie/electronic crossover picks', '{"spotify"}'),
(143, 'electric-forest', 'thu', 'Alleycvt', 'sherwood', 270, 345, 62, 'Bass', null, '{}'),
(144, 'electric-forest', 'thu', 'Ganja White Night', 'sherwood', 435, 510, 81, 'Dubstep', 'New territory, close to your SoundCloud dubstep follows', '{"soundcloud"}'),
(145, 'electric-forest', 'thu', 'H&RRY', 'tripolee', 0, 75, 55, 'Electronic / House', null, '{}'),
(146, 'electric-forest', 'thu', 'Close Friends Only', 'tripolee', 75, 135, 69, 'Indie Electronic', null, '{}'),
(147, 'electric-forest', 'thu', 'Jackie Hollander', 'tripolee', 135, 195, 73, 'House', 'Fits your house listening on weekends', '{"spotify"}'),
(148, 'electric-forest', 'thu', 'Daniel Allan', 'tripolee', 195, 255, 88, 'Melodic Bass', 'Heavy rotation for you lately', '{"spotify","soundcloud"}'),
(149, 'electric-forest', 'thu', 'DEVAULT', 'tripolee', 255, 315, 48, 'Bass / Dubstep', null, '{}'),
(150, 'electric-forest', 'thu', 'WESTEND', 'tripolee', 315, 375, 60, 'House', null, '{}'),
(151, 'electric-forest', 'thu', 'D.O.D', 'tripolee', 375, 435, 77, 'Techno / Bass', 'Close to your techno/bass crossover taste', '{"soundcloud"}'),
(152, 'electric-forest', 'thu', 'ODD MOB', 'tripolee', 435, 495, 54, 'Bass House', null, '{}'),
(153, 'electric-forest', 'thu', 'Eli Brown', 'tripolee', 495, 570, 90, 'Tech House', 'Your SoundCloud follows lean heavily into UK house/tech', '{"soundcloud"}'),
(154, 'governors-ball', 'sat', 'Jimmyboy', 'verizon', 0, 45, 40, 'Pop', null, '{}'),
(155, 'governors-ball', 'sat', 'Jade LeMac', 'grove', 15, 60, 52, 'Pop', null, '{}'),
(156, 'governors-ball', 'sat', 'Chanpan', 'snapchat', 30, 75, 47, 'Electronic', null, '{}'),
(157, 'governors-ball', 'sat', 'Spacey Jane', 'grove', 120, 165, 70, 'Indie Rock', null, '{}'),
(158, 'governors-ball', 'sat', '2hollis', 'snapchat', 150, 195, 61, 'Alt Pop / Electronic', null, '{}'),
(159, 'governors-ball', 'sat', 'Jane Remover', 'verizon', 180, 225, 65, 'Shoegaze / Digicore', null, '{}'),
(160, 'governors-ball', 'sat', 'Ravyn Lenae', 'verizon', 240, 285, 79, 'R&B', 'Close to your R&B listening on SoundCloud', '{"soundcloud"}'),
(161, 'governors-ball', 'sat', 'Wet Leg', 'grove', 240, 285, 97, 'Indie Rock', 'You caught them at Bonnaroo and Coachella — clearly a favorite', '{"spotify","soundcloud"}'),
(162, 'governors-ball', 'sat', 'Snow Strippers', 'snapchat', 240, 285, 58, 'Electroclash', null, '{}'),
(163, 'governors-ball', 'sat', 'Stray Kids', 'verizon', 510, 585, 55, 'K-Pop', null, '{}'),
(164, 'lollapalooza', 'sat', 'Peace Control', 'perrys', 0, 30, 42, 'Bass', null, '{}'),
(165, 'lollapalooza', 'sat', 'MC4D', 'perrys', 45, 90, 50, 'Trap / Bass', null, '{}'),
(166, 'lollapalooza', 'sat', 'OMNOM', 'perrys', 105, 165, 63, 'Dubstep', null, '{}'),
(167, 'lollapalooza', 'sat', 'AYYBO', 'perrys', 180, 240, 68, 'Hyperpop / Bass', null, '{}'),
(168, 'lollapalooza', 'sat', 'Whethan', 'perrys', 255, 315, 71, 'Electropop', 'Fits your electropop crossover listening', '{"spotify"}'),
(169, 'lollapalooza', 'sat', 'Max Styler', 'perrys', 345, 405, 74, 'Tech House', null, '{}'),
(170, 'lollapalooza', 'sat', 'Alison Wonderland', 'perrys', 420, 480, 85, 'Bass / Pop', 'Your SoundCloud follows lean into this bass/pop crossover', '{"soundcloud"}'),
(171, 'lollapalooza', 'sat', 'Disco Lines', 'perrys', 510, 585, 84, 'Tech House', 'You caught them at Electric Forest too', '{"soundcloud"}'),
(172, 'lollapalooza', 'sat', 'Olivia Dean', 'tmobile', 510, 585, 76, 'Soul / Pop', null, '{}'),
(173, 'lollapalooza', 'sat', 'JENNIE', 'budlight', 535, 600, 60, 'K-Pop', null, '{}'),
(174, 'outside-lands', 'sat', 'Malcolm Todd', 'twinpeaks', 0, 45, 64, 'Indie Pop', null, '{}'),
(175, 'outside-lands', 'sat', 'Djo', 'landsend', 60, 105, 78, 'Indie Rock / Synth Pop', 'Fits your synth-pop leaning indie listening', '{"spotify"}'),
(176, 'outside-lands', 'sat', 'Lucy Dacus', 'twinpeaks', 120, 165, 72, 'Indie Rock', null, '{}'),
(177, 'outside-lands', 'sat', 'Ethel Cain', 'sutro', 180, 240, 81, 'Alt / Gothic Americana', 'New territory, close to your slower indie moods', '{"soundcloud"}'),
(178, 'outside-lands', 'sat', 'Dijon', 'sutro', 255, 300, 69, 'Alt R&B', null, '{}'),
(179, 'outside-lands', 'sat', 'The xx', 'twinpeaks', 310, 370, 90, 'Indie Electronic', 'Your #1 most-played artist a few years running', '{"spotify","soundcloud"}'),
(180, 'outside-lands', 'sat', 'The Strokes', 'landsend', 335, 395, 95, 'Rock', 'You caught them at Bonnaroo and Coachella — clearly a top artist for you', '{"spotify"}'),
(181, 'outside-lands', 'sat', 'PinkPantheress', 'sutro', 345, 405, 59, 'Pop / UK Garage', null, '{}'),
(182, 'acl', 'fri', 'Skrillex', 'millerlite', 120, 195, 89, 'Electronic / Dubstep', 'Big part of your electronic listening history', '{"spotify"}'),
(183, 'acl', 'fri', 'Kings of Leon', 'tmobile-acl', 120, 210, 62, 'Rock', null, '{}'),
(184, 'acl', 'fri', 'Charli XCX', 'honda', 150, 225, 77, 'Pop', null, '{}'),
(185, 'edc-vegas', 'fri', 'Fisher', 'kineticfield', 0, 60, 88, 'Tech House', 'One of your most-played dance artists', '{"spotify"}'),
(186, 'edc-vegas', 'fri', 'Underworld', 'cosmicmeadow', 60, 120, 66, 'Electronic / Techno Legends', null, '{}'),
(187, 'edc-vegas', 'fri', 'Porter Robinson', 'kineticfield', 75, 135, 91, 'Melodic Electronic', 'Heavy rotation for you lately', '{"spotify","soundcloud"}'),
(188, 'edc-vegas', 'fri', 'Subtronics', 'circuitgrounds', 90, 150, 73, 'Dubstep', 'You caught similar acts at Lost Lands too', '{"soundcloud"}'),
(189, 'edc-vegas', 'fri', 'Sara Landry', 'neongarden', 120, 180, 82, 'Techno', 'You caught her at Bonnaroo too', '{"soundcloud"}'),
(190, 'edc-vegas', 'fri', 'Meduza', 'cosmicmeadow', 150, 210, 61, 'Dance / Pop', null, '{}'),
(191, 'edc-vegas', 'fri', 'Vintage Culture', 'circuitgrounds', 180, 240, 75, 'House', 'You caught them at Tomorrowland too', '{"spotify"}'),
(192, 'edc-vegas', 'fri', 'Charlotte de Witte', 'kineticfield', 150, 240, 94, 'Techno', 'Closing kineticFIELD Night 1 — a real highlight for your taste', '{"spotify","soundcloud"}'),
(193, 'tomorrowland', 'fri', 'Vintage Culture', 'mainstage', 0, 90, 75, 'House', 'You caught them at EDC too', '{"spotify"}'),
(194, 'tomorrowland', 'fri', 'Disco Lines', 'mainstage', 90, 150, 84, 'Tech House', 'You caught them at Electric Forest and Lollapalooza too', '{"soundcloud"}'),
(195, 'tomorrowland', 'fri', 'Bassjackers', 'mainstage', 150, 205, 55, 'Big Room', null, '{}'),
(196, 'tomorrowland', 'fri', 'Frank Verstraeten', 'freedom', 150, 240, 48, 'Techno', null, '{}'),
(197, 'tomorrowland', 'fri', 'Henri PFR', 'mainstage', 210, 270, 63, 'Melodic Techno', null, '{}'),
(198, 'tomorrowland', 'fri', 'Max Styler', 'freedom', 240, 330, 74, 'Tech House', 'You caught them at Lollapalooza too', '{"spotify"}'),
(199, 'tomorrowland', 'fri', 'NERVO', 'mainstage', 270, 335, 58, 'Electro House', null, '{}'),
(200, 'tomorrowland', 'fri', 'Miss Monique', 'freedom', 330, 420, 79, 'Melodic Techno', 'New territory, close to your melodic electronic taste', '{"soundcloud"}'),
(201, 'tomorrowland', 'fri', 'Marlon Hoffstadt', 'mainstage', 335, 395, 52, 'Tech House', null, '{}'),
(202, 'tomorrowland', 'fri', 'Mind Against', 'freedom', 420, 510, 86, 'Melodic Techno', 'Heavy rotation for you lately', '{"spotify","soundcloud"}'),
(203, 'tomorrowland', 'fri', 'NOVAH', 'mainstage', 395, 460, 60, 'Progressive House', null, '{}'),
(204, 'tomorrowland', 'fri', 'The Chainsmokers', 'mainstage', 460, 525, 68, 'EDM Pop', null, '{}'),
(205, 'tomorrowland', 'fri', '4444 of a Kind', 'freedom', 510, 570, 57, 'Techno', null, '{}'),
(206, 'tomorrowland', 'fri', 'Sebastian Ingrosso', 'mainstage', 525, 585, 65, 'Progressive House', null, '{}'),
(207, 'tomorrowland', 'fri', 'Holy Priest', 'freedom', 570, 660, 71, 'Techno', null, '{}'),
(208, 'tomorrowland', 'fri', 'Martin Garrix', 'mainstage', 585, 660, 80, 'Progressive House / EDM', 'Closing Mainstage — a genuine highlight for your taste', '{"spotify"}'),
(209, 'lost-lands', 'fri', 'Excision', 'll-mainstage', 0, 120, 93, 'Dubstep', 'A heavy part of your bass rotation', '{"spotify","soundcloud"}'),
(210, 'lost-lands', 'fri', 'Subtronics', 'crater', 60, 120, 73, 'Dubstep', 'You caught them at EDC too', '{"soundcloud"}'),
(211, 'lost-lands', 'fri', 'Wooli', 'll-mainstage', 150, 210, 68, 'Dubstep / Riddim', null, '{}'),
(212, 'lost-lands', 'fri', 'Ganja White Night', 'crater', 150, 210, 81, 'Dubstep', 'You caught them at Electric Forest too', '{"soundcloud"}'),
(213, 'lost-lands', 'fri', 'Seven Lions', 'll-mainstage', 240, 300, 86, 'Melodic Dubstep', 'Fits your melodic bass listening well', '{"spotify"}'),
(214, 'lost-lands', 'fri', 'ALLEYCVT', 'crater', 240, 300, 62, 'Bass', 'You caught them at Electric Forest too', '{"soundcloud"}'),
(215, 'lost-lands', 'fri', 'Flux Pavilion', 'crater', 330, 390, 71, 'Dubstep', null, '{}'),
(216, 'ultra-miami', 'fri', 'Illenium', 'main', 180, 245, null, 'Melodic Dubstep', null, '{}'),
(217, 'ultra-miami', 'fri', 'Bzrp', 'main', 245, 320, null, 'Latin Electronic', null, '{}'),
(218, 'ultra-miami', 'fri', 'Vini Vici', 'worldwide', 180, 240, null, 'Psytrance', null, '{}'),
(219, 'ultra-miami', 'fri', 'Armin van Buuren B2B Marlon Hoffstadt', 'worldwide', 300, 390, null, 'Trance', null, '{}'),
(220, 'ultra-europe', 'fri', 'Subtronics', 'main', 130, 195, null, 'Dubstep', null, '{}'),
(221, 'ultra-europe', 'fri', 'Oliver Heldens', 'main', 195, 275, null, 'Future House', null, '{}'),
(222, 'ultra-europe', 'fri', 'Miss Monique', 'resistance', 180, 300, null, 'Melodic Techno', null, '{}'),
(223, 'ultra-europe', 'fri', 'Adam Beyer', 'resistance', 300, 420, null, 'Techno', null, '{}'),
(243, 'tomorrowland-winter', 'sat', 'Oliver Heldens'' HI-LO b2b Maddix', 'orbyz', 180, 240, null, 'House', null, '{}'),
(244, 'tomorrowland-winter', 'sun', 'Nervo b2b MATTN', 'orbyz', 180, 240, null, 'Electro House', null, '{}'),
(245, 'tomorrowland-winter', 'sun', 'Dimitri Vegas b2b Steve Aoki', 'orbyz', 240, 300, null, 'Big Room / EDM', null, '{}'),
(246, 'edc-orlando', 'fri', 'David Guetta', 'kineticfield', 240, 330, null, 'House / EDM', null, '{}'),
(247, 'edc-orlando', 'sat', 'Kaskade', 'kineticfield', 240, 330, null, 'Progressive House', null, '{}'),
(248, 'edc-orlando', 'sun', 'Martin Garrix', 'kineticfield', 150, 240, null, 'Progressive House / EDM', null, '{}'),
(249, 'edc-orlando', 'sun', 'Hardwell', 'kineticfield', 240, 330, null, 'Big Room / EDM', null, '{}'),
(250, 'edc-mexico', 'fri', 'Chris Lake', 'circuitgrounds', 390, 480, null, 'Tech House', null, '{}'),
(251, 'edc-mexico', 'fri', 'Charlotte de Witte', 'circuitgrounds', 510, 600, null, 'Techno', null, '{}'),
(252, 'edc-mexico', 'sun', 'Anyma', 'kineticfield', 390, 450, null, 'Melodic Techno / Audiovisual', null, '{}'),
(253, 'lollapalooza-argentina', 'fri', 'Lorde', 'samsung', 120, 165, null, 'Art Pop', null, '{}'),
(254, 'lollapalooza-argentina', 'fri', 'Tyler, The Creator', 'flow', 195, 270, null, 'Hip-Hop', null, '{}'),
(255, 'lollapalooza-argentina', 'sun', 'Interpol', 'alternative', 0, 60, null, 'Post-Punk', null, '{}'),
(256, 'lollapalooza-argentina', 'sun', 'Sabrina Carpenter', 'flow', 195, 270, null, 'Pop', null, '{}'),
(257, 'lollapalooza-berlin', 'sat', 'Balu Brigada', 'essence', 90, 130, null, 'Electropop', null, '{}'),
(258, 'lollapalooza-berlin', 'sat', 'Young Miko', 'essence', 180, 225, null, 'Reggaeton / Latin Trap', null, '{}'),
(259, 'lollapalooza-berlin', 'sat', 'Tom Odell', 'essence', 280, 335, null, 'Piano Pop', null, '{}'),
(260, 'lollapalooza-berlin', 'sat', 'Zara Larsson', 'essence', 405, 465, null, 'Pop', null, '{}'),
(261, 'lollapalooza-berlin', 'sat', 'Pitbull', 'essence', 565, 655, null, 'Pop / Latin Hip-Hop', null, '{}'),
(262, 'secret-dreams', 'thu', 'Yoko', 'woods', 0, 40, null, 'Bass', null, '{}'),
(263, 'secret-dreams', 'thu', 'Skysia', 'pg', 40, 85, null, 'Global Bass', null, '{}'),
(264, 'secret-dreams', 'thu', 'Saturna', 'woods', 85, 130, null, 'Bass', null, '{}'),
(265, 'secret-dreams', 'thu', 'Mickman', 'pg', 130, 190, null, 'Electronic', null, '{}'),
(266, 'secret-dreams', 'thu', 'The Werks', 'woods', 190, 260, null, 'Jam / Livetronica', null, '{}'),
(267, 'secret-dreams', 'thu', 'CloZee', 'pg', 260, 330, null, 'Global Bass', null, '{}'),
(268, 'secret-dreams', 'fri', 'Detox Unit', 'woods', 0, 45, null, 'Dubstep', null, '{}'),
(269, 'secret-dreams', 'fri', 'Mr. Bill', 'pg', 45, 100, null, 'Glitch Hop', null, '{}'),
(270, 'secret-dreams', 'fri', 'Opiuo', 'woods', 100, 160, null, 'Glitch Hop', null, '{}'),
(271, 'secret-dreams', 'fri', 'Pigeons Playing Ping Pong', 'pg', 160, 230, null, 'Jam / Funk', null, '{}'),
(272, 'secret-dreams', 'fri', 'Emancipator', 'woods', 230, 290, null, 'Downtempo', null, '{}'),
(273, 'secret-dreams', 'fri', 'Of The Trees', 'pg', 290, 360, null, 'Bass / Glitch Hop', null, '{}'),
(274, 'secret-dreams', 'sat', 'Wonky Llama', 'woods', 0, 50, null, 'Bass', null, '{}'),
(275, 'secret-dreams', 'sat', 'Come Back to Earth', 'pg', 50, 110, null, 'Hip-Hop Tribute (Mac Miller)', null, '{}'),
(276, 'secret-dreams', 'sat', 'EarthGang', 'woods', 110, 170, null, 'Hip-Hop', null, '{}'),
(277, 'secret-dreams', 'sat', 'Daily Bread', 'pg', 170, 230, null, 'Bass / Soul', null, '{}'),
(278, 'secret-dreams', 'sat', 'Pretty Lights', 'woods', 230, 320, null, 'Glitch Hop / Electronic', null, '{}'),
(279, 'secret-dreams', 'sat', 'Pretty Lights', 'pg', 320, 410, null, 'Glitch Hop / Electronic', null, '{}'),
(280, 'secret-dreams', 'sun', 'Flamingosis', 'woods', 0, 50, null, 'Funk / Chillhop', null, '{}'),
(281, 'secret-dreams', 'sun', 'Late Night Radio', 'pg', 50, 110, null, 'Bass / Livetronica', null, '{}'),
(282, 'secret-dreams', 'sun', 'Daily Bread', 'woods', 110, 160, null, 'Bass / Soul', null, '{}'),
(283, 'secret-dreams', 'sun', 'Gramatik', 'pg', 160, 230, null, 'Glitch Hop', null, '{}'),
(284, 'secret-dreams', 'sun', 'Tape B', 'woods', 230, 300, null, 'Bass House', null, '{}'),
(285, 'secret-dreams', 'sun', 'Pretty Lights', 'pg', 300, 390, null, 'Glitch Hop / Electronic', null, '{}'),
(286, 'secret-dreams', 'sun', 'Pretty Lights', 'woods', 390, 480, null, 'Glitch Hop / Electronic', null, '{}')
on conflict (id) do nothing;
