-- Real EDC Mexico 2026 lineup, transcribed directly from the official
-- poster (user-provided). Also corrects the festival's actual dates: the
-- app had "Feb 19-21, 2027" but the real confirmed dates are Feb 20-22,
-- 2026 (Fri/Sat/Sun) -- fixed in App.jsx's FESTIVALS/FESTIVAL_DAYS.
-- Removes the 3 old placeholder rows (they used wrong dates and only
-- covered 2 of the 3 real days) and replaces with the full real lineup.
-- No stage/set-time info is published on the poster itself, so artists
-- are distributed across EDC Mexico's 5 real stages in sequential slots --
-- day/artist assignment is real, exact stage/time is not.

delete from festival_sets where id in (250, 251, 252);

insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(337, 'edc-mexico', 'fri', '3BALLMTY', 'kineticfield', 0, 60, null, null, null, '{}'),
(338, 'edc-mexico', 'fri', '999999999', 'circuitgrounds', 0, 60, null, null, null, '{}'),
(339, 'edc-mexico', 'fri', 'Aaron Sevilla', 'neongarden', 0, 60, null, null, null, '{}'),
(340, 'edc-mexico', 'fri', 'Above & Beyond', 'wasteland', 0, 60, null, 'Trance', null, '{}'),
(341, 'edc-mexico', 'fri', 'Alby ESC', 'stereobloom', 0, 60, null, null, null, '{}'),
(342, 'edc-mexico', 'fri', 'Alessandra Fierro', 'kineticfield', 60, 120, null, null, null, '{}'),
(343, 'edc-mexico', 'fri', 'Alex Wann', 'circuitgrounds', 60, 120, null, null, null, '{}'),
(344, 'edc-mexico', 'fri', 'Alexia Malo', 'neongarden', 60, 120, null, null, null, '{}'),
(345, 'edc-mexico', 'fri', 'Armand Van Helden', 'wasteland', 60, 120, null, 'House', null, '{}'),
(346, 'edc-mexico', 'fri', 'Attik', 'stereobloom', 60, 120, null, null, null, '{}'),
(347, 'edc-mexico', 'fri', 'Atliens', 'kineticfield', 120, 180, null, null, null, '{}'),
(348, 'edc-mexico', 'fri', 'Baggi', 'circuitgrounds', 120, 180, null, null, null, '{}'),
(349, 'edc-mexico', 'fri', 'Bagha Presents: Temple of Pain', 'neongarden', 120, 180, null, null, null, '{}'),
(350, 'edc-mexico', 'fri', 'Belu', 'wasteland', 120, 180, null, null, null, '{}'),
(351, 'edc-mexico', 'fri', 'Blizzard', 'stereobloom', 120, 180, null, null, null, '{}'),
(352, 'edc-mexico', 'fri', 'BSNO', 'kineticfield', 180, 240, null, null, null, '{}'),
(353, 'edc-mexico', 'fri', 'Calussa', 'circuitgrounds', 180, 240, null, null, null, '{}'),
(354, 'edc-mexico', 'fri', 'CamelPhat', 'neongarden', 180, 240, null, 'Melodic House / Techno', null, '{}'),
(355, 'edc-mexico', 'fri', 'Chris Lake', 'wasteland', 180, 240, null, 'Tech House', null, '{}'),
(356, 'edc-mexico', 'fri', 'Cristoph', 'stereobloom', 180, 240, null, null, null, '{}'),
(357, 'edc-mexico', 'fri', 'Crystal B2B Sommer', 'kineticfield', 240, 300, null, null, null, '{}'),
(358, 'edc-mexico', 'fri', 'D''Witches', 'circuitgrounds', 240, 300, null, null, null, '{}'),
(359, 'edc-mexico', 'fri', 'Deer Jade', 'neongarden', 240, 300, null, null, null, '{}'),
(360, 'edc-mexico', 'fri', 'Dezko', 'wasteland', 240, 300, null, null, null, '{}'),
(361, 'edc-mexico', 'fri', 'DJ Diesel', 'stereobloom', 240, 300, null, null, null, '{}'),
(362, 'edc-mexico', 'fri', 'DJ Gigola', 'kineticfield', 300, 360, null, null, null, '{}'),
(363, 'edc-mexico', 'fri', 'Eli & Fur', 'circuitgrounds', 300, 360, null, null, null, '{}'),
(364, 'edc-mexico', 'fri', 'Emisopa', 'neongarden', 300, 360, null, null, null, '{}'),
(365, 'edc-mexico', 'fri', 'Funk Tribu', 'wasteland', 300, 360, null, null, null, '{}'),
(366, 'edc-mexico', 'fri', 'Gareth Emery', 'stereobloom', 300, 360, null, 'Trance', null, '{}'),
(367, 'edc-mexico', 'fri', 'Hardwell', 'kineticfield', 360, 420, null, 'Big Room / EDM', null, '{}'),
(368, 'edc-mexico', 'fri', 'Honeyluv', 'circuitgrounds', 360, 420, null, null, null, '{}'),
(369, 'edc-mexico', 'fri', 'Indira Paganotti', 'neongarden', 360, 420, null, null, null, '{}'),
(370, 'edc-mexico', 'fri', 'Indo Warehouse', 'wasteland', 360, 420, null, null, null, '{}'),
(371, 'edc-mexico', 'fri', 'James Hype', 'stereobloom', 360, 420, null, 'Bass House', null, '{}'),
(372, 'edc-mexico', 'fri', 'Jessica Audiffred', 'kineticfield', 420, 480, null, null, null, '{}'),
(373, 'edc-mexico', 'fri', 'Kai Wachi', 'circuitgrounds', 420, 480, null, null, null, '{}'),
(374, 'edc-mexico', 'fri', 'KI/KI', 'neongarden', 420, 480, null, null, null, '{}'),
(375, 'edc-mexico', 'fri', 'Kinahau', 'wasteland', 420, 480, null, null, null, '{}'),
(376, 'edc-mexico', 'fri', 'Knock2', 'stereobloom', 420, 480, null, 'Bass / Future', null, '{}'),
(377, 'edc-mexico', 'fri', 'Lea Alva', 'kineticfield', 480, 540, null, null, null, '{}'),
(378, 'edc-mexico', 'fri', 'Lex Digital', 'circuitgrounds', 480, 540, null, null, null, '{}'),
(379, 'edc-mexico', 'fri', 'Mad Warriors', 'neongarden', 480, 540, null, null, null, '{}'),
(380, 'edc-mexico', 'fri', 'Magnolia Coronado', 'wasteland', 480, 540, null, null, null, '{}'),
(381, 'edc-mexico', 'fri', 'Mario Santander', 'stereobloom', 480, 540, null, null, null, '{}'),
(382, 'edc-mexico', 'fri', 'Massano', 'kineticfield', 540, 600, null, null, null, '{}'),
(383, 'edc-mexico', 'fri', 'Matt', 'circuitgrounds', 540, 600, null, null, null, '{}'),
(384, 'edc-mexico', 'fri', 'Mau P B2B The Martinez Brothers', 'neongarden', 540, 600, null, null, null, '{}'),
(385, 'edc-mexico', 'fri', 'Max Styler', 'wasteland', 540, 600, null, null, null, '{}'),
(386, 'edc-mexico', 'fri', 'Mind Against', 'stereobloom', 540, 600, null, 'Melodic Techno', null, '{}'),
(387, 'edc-mexico', 'fri', 'Mita Gami (Sunset Set)', 'kineticfield', 600, 660, null, null, null, '{}'),
(388, 'edc-mexico', 'fri', 'Morvius', 'circuitgrounds', 600, 660, null, null, null, '{}'),
(389, 'edc-mexico', 'fri', 'Nils Hoffmann', 'neongarden', 600, 660, null, 'Melodic House', null, '{}'),
(390, 'edc-mexico', 'fri', 'Peces Raros', 'wasteland', 600, 660, null, null, null, '{}'),
(391, 'edc-mexico', 'fri', 'Roni Martinez', 'stereobloom', 600, 660, null, null, null, '{}'),
(392, 'edc-mexico', 'fri', 'Sabina Palma', 'kineticfield', 660, 720, null, null, null, '{}'),
(393, 'edc-mexico', 'fri', 'Saza Fischer', 'circuitgrounds', 660, 720, null, null, null, '{}'),
(394, 'edc-mexico', 'fri', 'Sickmode', 'neongarden', 660, 720, null, null, null, '{}'),
(395, 'edc-mexico', 'fri', 'Sound Rush', 'wasteland', 660, 720, null, null, null, '{}'),
(396, 'edc-mexico', 'fri', 'Sultan + Shepard', 'stereobloom', 660, 720, null, 'Progressive House', null, '{}'),
(397, 'edc-mexico', 'fri', 'The Bloody Beetroots', 'kineticfield', 720, 780, null, 'Electro / Big Beat', null, '{}'),
(398, 'edc-mexico', 'fri', 'The Wookies', 'circuitgrounds', 720, 780, null, null, null, '{}'),
(399, 'edc-mexico', 'fri', 'Valentino Khan', 'neongarden', 720, 780, null, 'Bass House', null, '{}'),
(400, 'edc-mexico', 'fri', 'Vertile', 'wasteland', 720, 780, null, null, null, '{}'),
(401, 'edc-mexico', 'fri', 'Yotto', 'stereobloom', 720, 780, null, 'Melodic House / Techno', null, '{}'),
(402, 'edc-mexico', 'fri', '¥ØUSUK€ ¥UK1MAT$U', 'kineticfield', 780, 840, null, null, null, '{}'),
(403, 'edc-mexico', 'fri', 'Yurgenia', 'circuitgrounds', 780, 840, null, null, null, '{}'),
(404, 'edc-mexico', 'sat', 'Bonthebeat', 'kineticfield', 0, 60, null, null, null, '{}'),
(405, 'edc-mexico', 'sat', 'Adam Beyer', 'circuitgrounds', 0, 60, null, 'Techno', null, '{}'),
(406, 'edc-mexico', 'sat', 'Adam Ten B2B Mita Gami', 'neongarden', 0, 60, null, null, null, '{}'),
(407, 'edc-mexico', 'sat', 'Ahee', 'wasteland', 0, 60, null, null, null, '{}'),
(408, 'edc-mexico', 'sat', 'Alatriste B2B Mara Santiago', 'stereobloom', 0, 60, null, null, null, '{}'),
(409, 'edc-mexico', 'sat', 'Alesso', 'kineticfield', 60, 120, null, 'Progressive House', null, '{}'),
(410, 'edc-mexico', 'sat', 'Alisha', 'circuitgrounds', 60, 120, null, null, null, '{}'),
(411, 'edc-mexico', 'sat', 'Alok', 'neongarden', 60, 120, null, 'Brazilian Bass / Dance Pop', null, '{}'),
(412, 'edc-mexico', 'sat', 'Angerfist', 'wasteland', 60, 120, null, 'Hardcore / Frenchcore', null, '{}'),
(413, 'edc-mexico', 'sat', 'Anna', 'stereobloom', 60, 120, null, null, null, '{}'),
(414, 'edc-mexico', 'sat', 'Archie Hamilton B2B Riordan', 'kineticfield', 120, 180, null, null, null, '{}'),
(415, 'edc-mexico', 'sat', 'Azyr', 'circuitgrounds', 120, 180, null, null, null, '{}'),
(416, 'edc-mexico', 'sat', 'Black Tiger Sex Machine', 'neongarden', 120, 180, null, 'Bass / Electro', null, '{}'),
(417, 'edc-mexico', 'sat', 'Bolo', 'wasteland', 120, 180, null, null, null, '{}'),
(418, 'edc-mexico', 'sat', 'Brosa', 'stereobloom', 120, 180, null, null, null, '{}'),
(419, 'edc-mexico', 'sat', 'Brunello', 'kineticfield', 180, 240, null, null, null, '{}'),
(420, 'edc-mexico', 'sat', 'Cartel de los Hipopótamos', 'circuitgrounds', 180, 240, null, null, null, '{}'),
(421, 'edc-mexico', 'sat', 'Chan', 'neongarden', 180, 240, null, null, null, '{}'),
(422, 'edc-mexico', 'sat', 'Charlotte de Witte', 'wasteland', 180, 240, null, 'Techno', null, '{}'),
(423, 'edc-mexico', 'sat', 'Chris Lorenzo', 'stereobloom', 180, 240, null, 'Bass House', null, '{}'),
(424, 'edc-mexico', 'sat', 'Dan', 'kineticfield', 240, 300, null, null, null, '{}'),
(425, 'edc-mexico', 'sat', 'DANGR', 'circuitgrounds', 240, 300, null, null, null, '{}'),
(426, 'edc-mexico', 'sat', 'Dayana Avila', 'neongarden', 240, 300, null, null, null, '{}'),
(427, 'edc-mexico', 'sat', 'Discip', 'wasteland', 240, 300, null, null, null, '{}'),
(428, 'edc-mexico', 'sat', 'DJ Mir', 'stereobloom', 240, 300, null, null, null, '{}'),
(429, 'edc-mexico', 'sat', 'Dombresky', 'kineticfield', 300, 360, null, null, null, '{}'),
(430, 'edc-mexico', 'sat', 'Dualité', 'circuitgrounds', 300, 360, null, null, null, '{}'),
(431, 'edc-mexico', 'sat', 'Eli Brown', 'neongarden', 300, 360, null, null, null, '{}'),
(432, 'edc-mexico', 'sat', 'Enrico Sangiuliano', 'wasteland', 300, 360, null, 'Techno', null, '{}'),
(433, 'edc-mexico', 'sat', 'Eptic', 'stereobloom', 300, 360, null, null, null, '{}'),
(434, 'edc-mexico', 'sat', 'Fito Silva', 'kineticfield', 360, 420, null, null, null, '{}'),
(435, 'edc-mexico', 'sat', 'Getter', 'circuitgrounds', 360, 420, null, 'Dubstep / Bass', null, '{}'),
(436, 'edc-mexico', 'sat', 'Gravedgr', 'neongarden', 360, 420, null, null, null, '{}'),
(437, 'edc-mexico', 'sat', 'Hajj', 'wasteland', 360, 420, null, null, null, '{}'),
(438, 'edc-mexico', 'sat', 'Hesis', 'stereobloom', 360, 420, null, null, null, '{}'),
(439, 'edc-mexico', 'sat', 'HUGEL', 'kineticfield', 420, 480, null, 'House', null, '{}'),
(440, 'edc-mexico', 'sat', 'Interplanetary Criminal', 'circuitgrounds', 420, 480, null, null, null, '{}'),
(441, 'edc-mexico', 'sat', 'Jenny Anaya', 'neongarden', 420, 480, null, null, null, '{}'),
(442, 'edc-mexico', 'sat', 'Jesús Fernández', 'wasteland', 420, 480, null, null, null, '{}'),
(443, 'edc-mexico', 'sat', 'Joseph Capriati', 'stereobloom', 420, 480, null, 'Techno', null, '{}'),
(444, 'edc-mexico', 'sat', 'Josh Baker', 'kineticfield', 480, 540, null, null, null, '{}'),
(445, 'edc-mexico', 'sat', 'Junkie Kid', 'circuitgrounds', 480, 540, null, 'Bass House', null, '{}'),
(446, 'edc-mexico', 'sat', 'Kassie', 'neongarden', 480, 540, null, null, null, '{}'),
(447, 'edc-mexico', 'sat', 'Kawas', 'wasteland', 480, 540, null, null, null, '{}'),
(448, 'edc-mexico', 'sat', 'Le Twins', 'stereobloom', 480, 540, null, null, null, '{}'),
(449, 'edc-mexico', 'sat', 'Les Castizos', 'kineticfield', 540, 600, null, null, null, '{}'),
(450, 'edc-mexico', 'sat', 'Little D', 'circuitgrounds', 540, 600, null, null, null, '{}'),
(451, 'edc-mexico', 'sat', 'Lokier', 'neongarden', 540, 600, null, null, null, '{}'),
(452, 'edc-mexico', 'sat', 'Loud Luxury', 'wasteland', 540, 600, null, 'House / Pop Dance', null, '{}'),
(453, 'edc-mexico', 'sat', 'Maria Nocheydia', 'stereobloom', 540, 600, null, null, null, '{}'),
(454, 'edc-mexico', 'sat', 'Michael Mayer B2B Rebolledo', 'kineticfield', 600, 660, null, 'Techno / Electro', null, '{}'),
(455, 'edc-mexico', 'sat', 'Mike Posner', 'circuitgrounds', 600, 660, null, null, null, '{}'),
(456, 'edc-mexico', 'sat', 'Mish', 'neongarden', 600, 660, null, null, null, '{}'),
(457, 'edc-mexico', 'sat', 'Patrice Bäumel', 'wasteland', 600, 660, null, 'Melodic Techno', null, '{}'),
(458, 'edc-mexico', 'sat', 'Pawer', 'stereobloom', 600, 660, null, null, null, '{}'),
(459, 'edc-mexico', 'sat', 'Piero Cerritelli', 'kineticfield', 660, 720, null, null, null, '{}'),
(460, 'edc-mexico', 'sat', 'Rigopolar', 'circuitgrounds', 660, 720, null, null, null, '{}'),
(461, 'edc-mexico', 'sat', 'RØZ', 'neongarden', 660, 720, null, null, null, '{}'),
(462, 'edc-mexico', 'sat', 'Sam Feldt', 'wasteland', 660, 720, null, 'Tropical House', null, '{}'),
(463, 'edc-mexico', 'sat', 'Seth Troxler', 'stereobloom', 660, 720, null, 'Techno / House', null, '{}'),
(464, 'edc-mexico', 'sat', 'Shanti Clasing', 'kineticfield', 720, 780, null, null, null, '{}'),
(465, 'edc-mexico', 'sat', 'Sidney Charles', 'circuitgrounds', 720, 780, null, null, null, '{}'),
(466, 'edc-mexico', 'sat', 'Silvie Loto', 'neongarden', 720, 780, null, null, null, '{}'),
(467, 'edc-mexico', 'sat', 'Six Sex', 'wasteland', 720, 780, null, null, null, '{}'),
(468, 'edc-mexico', 'sat', 'Sol Ortega', 'stereobloom', 720, 780, null, null, null, '{}'),
(469, 'edc-mexico', 'sat', 'Sullivan King', 'kineticfield', 780, 840, null, 'Dubstep / Bass Rock', null, '{}'),
(470, 'edc-mexico', 'sat', 'TAAO', 'circuitgrounds', 780, 840, null, null, null, '{}'),
(471, 'edc-mexico', 'sat', 'TBX', 'neongarden', 780, 840, null, null, null, '{}'),
(472, 'edc-mexico', 'sat', 'Villaseñor', 'wasteland', 780, 840, null, null, null, '{}'),
(473, 'edc-mexico', 'sat', 'Xandra', 'stereobloom', 780, 840, null, null, null, '{}'),
(474, 'edc-mexico', 'sun', 'Adalamoon', 'kineticfield', 0, 60, null, null, null, '{}'),
(475, 'edc-mexico', 'sun', 'Adrián Mills B2B Cloudy', 'circuitgrounds', 0, 60, null, null, null, '{}'),
(476, 'edc-mexico', 'sun', 'Ahmed Spins B2B LP Giobbi', 'neongarden', 0, 60, null, null, null, '{}'),
(477, 'edc-mexico', 'sun', 'Alby Loud', 'wasteland', 0, 60, null, null, null, '{}'),
(478, 'edc-mexico', 'sun', 'Ana Morss & Kate Gozz Present: B2Blondes', 'stereobloom', 0, 60, null, null, null, '{}'),
(479, 'edc-mexico', 'sun', 'Andre VII', 'kineticfield', 60, 120, null, null, null, '{}'),
(480, 'edc-mexico', 'sun', 'Anetha B2B Odymel', 'circuitgrounds', 60, 120, null, null, null, '{}'),
(481, 'edc-mexico', 'sun', 'Anyma', 'neongarden', 60, 120, null, 'Melodic Techno / Audiovisual', null, '{}'),
(482, 'edc-mexico', 'sun', 'Aranxa B2B K1', 'wasteland', 60, 120, null, null, null, '{}'),
(483, 'edc-mexico', 'sun', 'Argüello', 'stereobloom', 60, 120, null, null, null, '{}'),
(484, 'edc-mexico', 'sun', 'Audien', 'kineticfield', 120, 180, null, 'Progressive House', null, '{}'),
(485, 'edc-mexico', 'sun', 'Beltran B2B Maetrik aka Maceo Plex', 'circuitgrounds', 120, 180, null, 'Techno / House', null, '{}'),
(486, 'edc-mexico', 'sun', 'Ben Hemsley', 'neongarden', 120, 180, null, null, null, '{}'),
(487, 'edc-mexico', 'sun', 'Ben Sterling', 'wasteland', 120, 180, null, 'House', null, '{}'),
(488, 'edc-mexico', 'sun', 'Calabasa', 'stereobloom', 120, 180, null, null, null, '{}'),
(489, 'edc-mexico', 'sun', 'Carlos Martz', 'kineticfield', 180, 240, null, null, null, '{}'),
(490, 'edc-mexico', 'sun', 'Celice B2B Sadgal', 'circuitgrounds', 180, 240, null, null, null, '{}'),
(491, 'edc-mexico', 'sun', 'Darude', 'neongarden', 180, 240, null, 'Trance / EDM', null, '{}'),
(492, 'edc-mexico', 'sun', 'Dennis Cruz', 'wasteland', 180, 240, null, 'Tech House', null, '{}'),
(493, 'edc-mexico', 'sun', 'DJ Alan Rosales B2B DJ Mouse', 'stereobloom', 180, 240, null, null, null, '{}'),
(494, 'edc-mexico', 'sun', 'Djibouti', 'kineticfield', 240, 300, null, null, null, '{}'),
(495, 'edc-mexico', 'sun', 'Ezya', 'circuitgrounds', 240, 300, null, null, null, '{}'),
(496, 'edc-mexico', 'sun', 'Fanny', 'neongarden', 240, 300, null, null, null, '{}'),
(497, 'edc-mexico', 'sun', 'Felipe Gordon', 'wasteland', 240, 300, null, null, null, '{}'),
(498, 'edc-mexico', 'sun', 'Fenrick B2B Prada2000', 'stereobloom', 240, 300, null, null, null, '{}'),
(499, 'edc-mexico', 'sun', 'Fumi B2B Serafina', 'kineticfield', 300, 360, null, null, null, '{}'),
(500, 'edc-mexico', 'sun', 'GRiZ', 'circuitgrounds', 300, 360, null, 'Funk / Electronic', null, '{}'),
(501, 'edc-mexico', 'sun', 'Gusty DJ', 'neongarden', 300, 360, null, null, null, '{}'),
(502, 'edc-mexico', 'sun', 'Hayla', 'wasteland', 300, 360, null, null, null, '{}'),
(503, 'edc-mexico', 'sun', 'Holy Priest', 'stereobloom', 300, 360, null, null, null, '{}'),
(504, 'edc-mexico', 'sun', 'Ima', 'kineticfield', 360, 420, null, null, null, '{}'),
(505, 'edc-mexico', 'sun', 'Infected Mushroom', 'circuitgrounds', 360, 420, null, 'Psytrance', null, '{}'),
(506, 'edc-mexico', 'sun', 'Isoxo', 'neongarden', 360, 420, null, null, null, '{}'),
(507, 'edc-mexico', 'sun', 'Jamie Jones', 'wasteland', 360, 420, null, 'Tech House', null, '{}'),
(508, 'edc-mexico', 'sun', 'Jeffrey Sutorius', 'stereobloom', 360, 420, null, null, null, '{}'),
(509, 'edc-mexico', 'sun', 'Jigitz', 'kineticfield', 420, 480, null, null, null, '{}'),
(510, 'edc-mexico', 'sun', 'John Summit', 'circuitgrounds', 420, 480, null, 'House', null, '{}'),
(511, 'edc-mexico', 'sun', 'JSTJR', 'neongarden', 420, 480, null, null, null, '{}'),
(512, 'edc-mexico', 'sun', 'Karlo', 'wasteland', 420, 480, null, null, null, '{}'),
(513, 'edc-mexico', 'sun', 'Kevin Brand', 'stereobloom', 420, 480, null, null, null, '{}'),
(514, 'edc-mexico', 'sun', 'Kevin De Vries', 'kineticfield', 480, 540, null, 'Melodic Techno / House', null, '{}'),
(515, 'edc-mexico', 'sun', 'Key4050', 'circuitgrounds', 480, 540, null, null, null, '{}'),
(516, 'edc-mexico', 'sun', 'Level Up', 'neongarden', 480, 540, null, null, null, '{}'),
(517, 'edc-mexico', 'sun', 'Levity', 'wasteland', 480, 540, null, null, null, '{}'),
(518, 'edc-mexico', 'sun', 'Lo Stine', 'stereobloom', 480, 540, null, null, null, '{}'),
(519, 'edc-mexico', 'sun', 'Los Dutis', 'kineticfield', 540, 600, null, null, null, '{}'),
(520, 'edc-mexico', 'sun', 'Malugi', 'circuitgrounds', 540, 600, null, null, null, '{}'),
(521, 'edc-mexico', 'sun', 'Matty Ralph', 'neongarden', 540, 600, null, null, null, '{}'),
(522, 'edc-mexico', 'sun', 'Mayte Mx', 'wasteland', 540, 600, null, null, null, '{}'),
(523, 'edc-mexico', 'sun', 'Mike Epsse', 'stereobloom', 540, 600, null, null, null, '{}'),
(524, 'edc-mexico', 'sun', 'Mila', 'kineticfield', 600, 660, null, null, null, '{}'),
(525, 'edc-mexico', 'sun', 'MNTY', 'circuitgrounds', 600, 660, null, null, null, '{}'),
(526, 'edc-mexico', 'sun', 'Nana Nina', 'neongarden', 600, 660, null, null, null, '{}'),
(527, 'edc-mexico', 'sun', 'Noise Mafia B2B Peterblue', 'wasteland', 600, 660, null, null, null, '{}'),
(528, 'edc-mexico', 'sun', 'Novah', 'stereobloom', 600, 660, null, null, null, '{}'),
(529, 'edc-mexico', 'sun', 'Pahua', 'kineticfield', 660, 720, null, null, null, '{}'),
(530, 'edc-mexico', 'sun', 'Pato Shoucair', 'circuitgrounds', 660, 720, null, null, null, '{}'),
(531, 'edc-mexico', 'sun', 'Rafatel', 'neongarden', 660, 720, null, null, null, '{}'),
(532, 'edc-mexico', 'sun', 'Restricted', 'wasteland', 660, 720, null, null, null, '{}'),
(533, 'edc-mexico', 'sun', 'Roman Messer', 'stereobloom', 660, 720, null, 'Trance', null, '{}'),
(534, 'edc-mexico', 'sun', 'Rossi.', 'kineticfield', 720, 780, null, null, null, '{}'),
(535, 'edc-mexico', 'sun', 'Sammy Virji', 'circuitgrounds', 720, 780, null, null, null, '{}'),
(536, 'edc-mexico', 'sun', 'San Holo (Wholesome Riddim Set)', 'neongarden', 720, 780, null, 'Electronic / Indie Dance', null, '{}'),
(537, 'edc-mexico', 'sun', 'Sander van Doorn', 'wasteland', 720, 780, null, 'Progressive House / Techno', null, '{}'),
(538, 'edc-mexico', 'sun', 'Sebaxxss', 'stereobloom', 720, 780, null, null, null, '{}'),
(539, 'edc-mexico', 'sun', 'Steve Angello', 'kineticfield', 780, 840, null, 'Progressive House', null, '{}'),
(540, 'edc-mexico', 'sun', 'Tape B', 'circuitgrounds', 780, 840, null, 'Bass House', null, '{}'),
(541, 'edc-mexico', 'sun', 'Tom & Collins', 'neongarden', 780, 840, null, null, null, '{}'),
(542, 'edc-mexico', 'sun', 'Trym', 'wasteland', 780, 840, null, null, null, '{}'),
(543, 'edc-mexico', 'sun', 'Ugly Lungs', 'stereobloom', 780, 840, null, null, null, '{}'),
(544, 'edc-mexico', 'sun', 'Vini Vici', 'kineticfield', 840, 900, null, 'Psytrance', null, '{}'),
(545, 'edc-mexico', 'sun', 'Westend', 'circuitgrounds', 840, 900, null, null, null, '{}'),
(546, 'edc-mexico', 'sun', 'Yazz Escobar', 'neongarden', 840, 900, null, null, null, '{}'),
(547, 'edc-mexico', 'sun', 'Yissel de Anda', 'wasteland', 840, 900, null, null, null, '{}'),
(548, 'edc-mexico', 'sun', 'Zedd', 'stereobloom', 840, 900, null, 'Electro Pop / EDM', null, '{}')
on conflict (id) do nothing;
