-- Real Reading & Leeds 2026 lineup (Aug 27-30), transcribed directly from
-- readingfestival.com/lineup -- every artist's real day + stage assignment
-- comes straight from the official site. Set times aren't published this
-- close to the show (only day/stage are), so each stage gets sequential
-- 60-min placeholder slots from noon, with the three known headliner
-- pairs (Charli XCX/Fontaines D.C. Fri, Dave/Raye Sat, Florence + The
-- Machine/Chase & Status Sun -- confirmed via the official poster) placed
-- in the closing slot on the Grid (main stage) rather than wherever they'd
-- fall alphabetically. Day 1 (Thu) is arrival/campsite-only -- no artists
-- play, consistent with Reading & Leeds' real format -- so only fri/sat/sun
-- appear here.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(549, 'reading-leeds', 'fri', 'Beth McCarthy', 'grid', 720, 780, null, null, null, '{}'),
(550, 'reading-leeds', 'fri', 'Declan Mckenna', 'grid', 780, 840, null, 'Indie Rock', null, '{}'),
(551, 'reading-leeds', 'fri', 'James Marriott', 'grid', 840, 900, null, null, null, '{}'),
(552, 'reading-leeds', 'fri', 'Keo', 'grid', 900, 960, null, null, null, '{}'),
(553, 'reading-leeds', 'fri', 'Skepta', 'grid', 960, 1020, null, 'Grime', null, '{}'),
(554, 'reading-leeds', 'fri', 'Charli XCX', 'grid', 1020, 1080, null, 'Pop / Hyperpop', null, '{}'),
(555, 'reading-leeds', 'fri', 'Fontaines D.C.', 'grid', 1080, 1140, null, 'Post-Punk', null, '{}'),
(556, 'reading-leeds', 'fri', 'Adéla', 'gallery', 720, 780, null, null, null, '{}'),
(557, 'reading-leeds', 'fri', 'DJ EJ', 'gallery', 780, 840, null, null, null, '{}'),
(558, 'reading-leeds', 'fri', 'Geese', 'gallery', 840, 900, null, 'Indie Rock', null, '{}'),
(559, 'reading-leeds', 'fri', 'JD Cliffe', 'gallery', 900, 960, null, null, null, '{}'),
(560, 'reading-leeds', 'fri', 'Josh Baker', 'gallery', 960, 1020, null, null, null, '{}'),
(561, 'reading-leeds', 'fri', 'SINN6R', 'gallery', 1020, 1080, null, null, null, '{}'),
(562, 'reading-leeds', 'fri', 'Skye Newman', 'gallery', 1080, 1140, null, null, null, '{}'),
(563, 'reading-leeds', 'fri', 'Djammin', 'warehouse', 720, 780, null, null, null, '{}'),
(564, 'reading-leeds', 'fri', 'Julian Fijma', 'warehouse', 780, 840, null, null, null, '{}'),
(565, 'reading-leeds', 'fri', 'Luuk Van Dijk', 'warehouse', 840, 900, null, null, null, '{}'),
(566, 'reading-leeds', 'fri', 'Meeshy', 'warehouse', 900, 960, null, null, null, '{}'),
(567, 'reading-leeds', 'fri', 'Omar+', 'warehouse', 960, 1020, null, null, null, '{}'),
(568, 'reading-leeds', 'fri', 'Riordan', 'warehouse', 1020, 1080, null, null, null, '{}'),
(569, 'reading-leeds', 'fri', 'Silva Bumpa', 'warehouse', 1080, 1140, null, null, null, '{}'),
(570, 'reading-leeds', 'fri', 'Skepta B2B Prospa', 'warehouse', 1140, 1200, null, null, null, '{}'),
(571, 'reading-leeds', 'fri', 'Bleech 9:3', 'ballroom', 720, 780, null, null, null, '{}'),
(572, 'reading-leeds', 'fri', 'Cardinals', 'ballroom', 780, 840, null, null, null, '{}'),
(573, 'reading-leeds', 'fri', 'Clementine Douglas', 'ballroom', 840, 900, null, null, null, '{}'),
(574, 'reading-leeds', 'fri', 'Florence Road', 'ballroom', 900, 960, null, null, null, '{}'),
(575, 'reading-leeds', 'fri', 'Overpass', 'ballroom', 960, 1020, null, null, null, '{}'),
(576, 'reading-leeds', 'fri', 'Unpeople', 'ballroom', 1020, 1080, null, null, null, '{}'),
(577, 'reading-leeds', 'fri', 'YT', 'ballroom', 1080, 1140, null, null, null, '{}'),
(578, 'reading-leeds', 'fri', 'Camille Blackman', 'canopy', 720, 780, null, null, null, '{}'),
(579, 'reading-leeds', 'fri', 'Day We Ran', 'canopy', 780, 840, null, null, null, '{}'),
(580, 'reading-leeds', 'fri', 'People I''ve Met', 'canopy', 840, 900, null, null, null, '{}'),
(581, 'reading-leeds', 'fri', 'The Guest List', 'canopy', 900, 960, null, null, null, '{}'),
(582, 'reading-leeds', 'fri', 'Villanelle', 'canopy', 960, 1020, null, null, null, '{}'),
(583, 'reading-leeds', 'sat', 'Absolutely', 'grid', 720, 780, null, null, null, '{}'),
(584, 'reading-leeds', 'sat', 'Jade', 'grid', 780, 840, null, 'Pop', null, '{}'),
(585, 'reading-leeds', 'sat', 'Maisie Peters', 'grid', 840, 900, null, 'Pop', null, '{}'),
(586, 'reading-leeds', 'sat', 'Slayyyter', 'grid', 900, 960, null, 'Hyperpop', null, '{}'),
(587, 'reading-leeds', 'sat', 'sombr', 'grid', 960, 1020, null, 'Indie Pop', null, '{}'),
(588, 'reading-leeds', 'sat', 'Dave', 'grid', 1020, 1080, null, 'UK Hip-Hop', null, '{}'),
(589, 'reading-leeds', 'sat', 'Raye', 'grid', 1080, 1140, null, 'Pop / R&B', null, '{}'),
(590, 'reading-leeds', 'sat', 'Ceebo', 'gallery', 720, 780, null, null, null, '{}'),
(591, 'reading-leeds', 'sat', 'Clara La San', 'gallery', 780, 840, null, null, null, '{}'),
(592, 'reading-leeds', 'sat', 'Duke Dumont', 'gallery', 840, 900, null, 'House', null, '{}'),
(593, 'reading-leeds', 'sat', 'Gunna', 'gallery', 900, 960, null, 'Hip-Hop', null, '{}'),
(594, 'reading-leeds', 'sat', 'Kingfishr', 'gallery', 960, 1020, null, 'Folk Rock', null, '{}'),
(595, 'reading-leeds', 'sat', 'Nine Vicious', 'gallery', 1020, 1080, null, null, null, '{}'),
(596, 'reading-leeds', 'sat', 'Say Now', 'gallery', 1080, 1140, null, null, null, '{}'),
(597, 'reading-leeds', 'sat', 'Viagra Boys', 'gallery', 1140, 1200, null, 'Post-Punk', null, '{}'),
(598, 'reading-leeds', 'sat', 'In Parallel', 'warehouse', 720, 780, null, null, null, '{}'),
(599, 'reading-leeds', 'sat', 'Joss Dean b2b Nafe Smallz', 'warehouse', 780, 840, null, null, null, '{}'),
(600, 'reading-leeds', 'sat', 'Mall Grab', 'warehouse', 840, 900, null, 'House / Techno', null, '{}'),
(601, 'reading-leeds', 'sat', 'Max Dean b2b Luke Dean', 'warehouse', 900, 960, null, null, null, '{}'),
(602, 'reading-leeds', 'sat', 'Rossi.', 'warehouse', 960, 1020, null, null, null, '{}'),
(603, 'reading-leeds', 'sat', 'Tommy Phillips', 'warehouse', 1020, 1080, null, null, null, '{}'),
(604, 'reading-leeds', 'sat', 'Bar Italia', 'ballroom', 720, 780, null, 'Indie Rock', null, '{}'),
(605, 'reading-leeds', 'sat', 'Fliss', 'ballroom', 780, 840, null, null, null, '{}'),
(606, 'reading-leeds', 'sat', 'Frost Children', 'ballroom', 840, 900, null, null, null, '{}'),
(607, 'reading-leeds', 'sat', 'Jane Remover', 'ballroom', 900, 960, null, 'Digicore / Shoegaze', null, '{}'),
(608, 'reading-leeds', 'sat', 'Niko B', 'ballroom', 960, 1020, null, null, null, '{}'),
(609, 'reading-leeds', 'sat', 'Radio Free Alice', 'ballroom', 1020, 1080, null, null, null, '{}'),
(610, 'reading-leeds', 'sat', 'SPEED', 'ballroom', 1080, 1140, null, null, null, '{}'),
(611, 'reading-leeds', 'sat', 'Cruz Beckham and the Breakers', 'canopy', 720, 780, null, null, null, '{}'),
(612, 'reading-leeds', 'sat', 'Finessekid', 'canopy', 780, 840, null, null, null, '{}'),
(613, 'reading-leeds', 'sat', 'Kibo', 'canopy', 840, 900, null, null, null, '{}'),
(614, 'reading-leeds', 'sat', 'Ruby Roberts', 'canopy', 900, 960, null, null, null, '{}'),
(615, 'reading-leeds', 'sat', 'Seb Lowe', 'canopy', 960, 1020, null, null, null, '{}'),
(616, 'reading-leeds', 'sun', '54 Ultra', 'grid', 720, 780, null, null, null, '{}'),
(617, 'reading-leeds', 'sun', 'Arthur Hill', 'grid', 780, 840, null, null, null, '{}'),
(618, 'reading-leeds', 'sun', 'Loyle Carner', 'grid', 840, 900, null, 'UK Hip-Hop', null, '{}'),
(619, 'reading-leeds', 'sun', 'Role Model', 'grid', 900, 960, null, 'Pop', null, '{}'),
(620, 'reading-leeds', 'sun', 'Chase & Status Live', 'grid', 960, 1020, null, 'Drum & Bass', null, '{}'),
(621, 'reading-leeds', 'sun', 'Florence + The Machine', 'grid', 1020, 1080, null, 'Indie Rock', null, '{}'),
(622, 'reading-leeds', 'sun', 'After', 'gallery', 720, 780, null, null, null, '{}'),
(623, 'reading-leeds', 'sun', 'Chris Stassy', 'gallery', 780, 840, null, null, null, '{}'),
(624, 'reading-leeds', 'sun', 'Holly Humberstone', 'gallery', 840, 900, null, 'Indie Pop', null, '{}'),
(625, 'reading-leeds', 'sun', 'Julia Wolf', 'gallery', 900, 960, null, 'Alt-Pop', null, '{}'),
(626, 'reading-leeds', 'sun', 'Kettama', 'gallery', 960, 1020, null, null, null, '{}'),
(627, 'reading-leeds', 'sun', 'Kneecap', 'gallery', 1020, 1080, null, 'Hip-Hop', null, '{}'),
(628, 'reading-leeds', 'sun', 'Men I Trust', 'gallery', 1080, 1140, null, 'Indie Pop', null, '{}'),
(629, 'reading-leeds', 'sun', 'Mulaa Joans', 'gallery', 1140, 1200, null, null, null, '{}'),
(630, 'reading-leeds', 'sun', 'Bou', 'warehouse', 720, 780, null, 'Drum & Bass', null, '{}'),
(631, 'reading-leeds', 'sun', 'Hamdi', 'warehouse', 780, 840, null, null, null, '{}'),
(632, 'reading-leeds', 'sun', 'Hedex', 'warehouse', 840, 900, null, 'Drum & Bass', null, '{}'),
(633, 'reading-leeds', 'sun', 'Hybrid Minds', 'warehouse', 900, 960, null, 'Drum & Bass', null, '{}'),
(634, 'reading-leeds', 'sun', 'Notion', 'warehouse', 960, 1020, null, null, null, '{}'),
(635, 'reading-leeds', 'sun', 'Saint Ludo', 'warehouse', 1020, 1080, null, null, null, '{}'),
(636, 'reading-leeds', 'sun', 'SOTA', 'warehouse', 1080, 1140, null, null, null, '{}'),
(637, 'reading-leeds', 'sun', 'Betty', 'ballroom', 720, 780, null, null, null, '{}'),
(638, 'reading-leeds', 'sun', 'Chloe Qisha', 'ballroom', 780, 840, null, null, null, '{}'),
(639, 'reading-leeds', 'sun', 'Dexter In The Newsagent', 'ballroom', 840, 900, null, null, null, '{}'),
(640, 'reading-leeds', 'sun', 'Paris Paloma', 'ballroom', 900, 960, null, 'Folk', null, '{}'),
(641, 'reading-leeds', 'sun', 'Westside Cowboy', 'ballroom', 960, 1020, null, null, null, '{}'),
(642, 'reading-leeds', 'sun', 'WHATMORE', 'ballroom', 1020, 1080, null, null, null, '{}'),
(643, 'reading-leeds', 'sun', 'Wisp', 'ballroom', 1080, 1140, null, null, null, '{}'),
(644, 'reading-leeds', 'sun', 'Alex Spencer', 'canopy', 720, 780, null, null, null, '{}'),
(645, 'reading-leeds', 'sun', 'December 10', 'canopy', 780, 840, null, null, null, '{}'),
(646, 'reading-leeds', 'sun', 'Kilu', 'canopy', 840, 900, null, null, null, '{}'),
(647, 'reading-leeds', 'sun', 'Violet Grohl', 'canopy', 900, 960, null, null, null, '{}')
on conflict (id) do nothing;
