-- Real Rock in Rio 2026 lineup (Rio de Janeiro), transcribed directly from
-- rockinrio.com/rio/pt-br/line-up/'s own day-by-day filter -- a biannual,
-- two-weekend festival: Sep 4-7 + Sep 11-13, 2026 (7 real days total).
-- Six stages, all named exactly as the official site lists them (Palco
-- Mundo/Sunset, New Dance Order, Espaço Favela, Global Village, Supernova).
-- Set times aren't published yet -- each stage gets sequential 60-min
-- placeholder slots from noon, with the site's own top-billed headliner
-- per stage/day (listed first on the official page, same descending-
-- billing convention observed on Reading & Leeds' site) placed in the
-- closing slot instead of wherever it'd land alphabetically.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(648, 'rock-in-rio', 'fri', 'Nova Twins', 'mainstage', 720, 780, null, 'Punk / Rock', null, '{}'),
(649, 'rock-in-rio', 'fri', 'Rise Against', 'mainstage', 780, 840, null, 'Punk Rock', null, '{}'),
(650, 'rock-in-rio', 'fri', 'The Hives', 'mainstage', 840, 900, null, 'Garage Rock', null, '{}'),
(651, 'rock-in-rio', 'fri', 'Foo Fighters', 'mainstage', 900, 960, null, 'Rock', null, '{}'),
(652, 'rock-in-rio', 'fri', 'Detonautas convida Biquini', 'sunset', 720, 780, null, null, null, '{}'),
(653, 'rock-in-rio', 'fri', 'Di Ferrero', 'sunset', 780, 840, null, null, null, '{}'),
(654, 'rock-in-rio', 'fri', 'Hot Mulk', 'sunset', 840, 900, null, null, null, '{}'),
(655, 'rock-in-rio', 'fri', 'Capital Inicial convida Dado Villa-Lobos', 'sunset', 900, 960, null, null, null, '{}'),
(656, 'rock-in-rio', 'fri', 'Atkö', 'newdanceorder', 720, 780, null, null, null, '{}'),
(657, 'rock-in-rio', 'fri', 'Cat Dealers', 'newdanceorder', 780, 840, null, null, null, '{}'),
(658, 'rock-in-rio', 'fri', 'Giu x Carola', 'newdanceorder', 840, 900, null, null, null, '{}'),
(659, 'rock-in-rio', 'fri', 'Steve Angello', 'newdanceorder', 900, 960, null, null, null, '{}'),
(660, 'rock-in-rio', 'fri', 'GBZ7N', 'favela', 720, 780, null, null, null, '{}'),
(661, 'rock-in-rio', 'fri', 'Hitmaker', 'favela', 780, 840, null, null, null, '{}'),
(662, 'rock-in-rio', 'fri', 'Rodrigo do CN', 'favela', 840, 900, null, null, null, '{}'),
(663, 'rock-in-rio', 'fri', 'Giovanna Moraes', 'globalvillage', 720, 780, null, null, null, '{}'),
(664, 'rock-in-rio', 'fri', 'Leela', 'globalvillage', 780, 840, null, null, null, '{}'),
(665, 'rock-in-rio', 'fri', 'Paulinho Moska', 'globalvillage', 840, 900, null, null, null, '{}'),
(666, 'rock-in-rio', 'fri', 'Chady', 'supernova', 720, 780, null, null, null, '{}'),
(667, 'rock-in-rio', 'fri', 'Rock in Gil com Larissa Luz', 'supernova', 780, 840, null, null, null, '{}'),
(668, 'rock-in-rio', 'fri', 'Venere vai Venus', 'supernova', 840, 900, null, null, null, '{}'),
(669, 'rock-in-rio', 'fri', 'Diogo Defante', 'supernova', 900, 960, null, null, null, '{}'),
(670, 'rock-in-rio', 'sat', 'Bring Me The Horizon', 'mainstage', 720, 780, null, 'Metalcore', null, '{}'),
(671, 'rock-in-rio', 'sat', 'MGK', 'mainstage', 780, 840, null, 'Pop Punk / Hip-Hop', null, '{}'),
(672, 'rock-in-rio', 'sat', 'Sepultura', 'mainstage', 840, 900, null, 'Thrash Metal', null, '{}'),
(673, 'rock-in-rio', 'sat', 'Avenged Sevenfold', 'mainstage', 900, 960, null, 'Metal', null, '{}'),
(674, 'rock-in-rio', 'sat', 'Black Panterá convida Nervosa', 'sunset', 720, 780, null, null, null, '{}'),
(675, 'rock-in-rio', 'sat', 'Malvada convida Day Limns', 'sunset', 780, 840, null, null, null, '{}'),
(676, 'rock-in-rio', 'sat', 'Poppy', 'sunset', 840, 900, null, 'Alt Metal / Pop', null, '{}'),
(677, 'rock-in-rio', 'sat', 'Bad Omens', 'sunset', 900, 960, null, 'Metalcore', null, '{}'),
(678, 'rock-in-rio', 'sat', 'Camila Jun x Eli Iwasa', 'newdanceorder', 720, 780, null, null, null, '{}'),
(679, 'rock-in-rio', 'sat', 'Victor Lou', 'newdanceorder', 780, 840, null, null, null, '{}'),
(680, 'rock-in-rio', 'sat', 'Volkoder', 'newdanceorder', 840, 900, null, null, null, '{}'),
(681, 'rock-in-rio', 'sat', 'James Hype', 'newdanceorder', 900, 960, null, 'House', null, '{}'),
(682, 'rock-in-rio', 'sat', 'Canto Cego', 'favela', 720, 780, null, null, null, '{}'),
(683, 'rock-in-rio', 'sat', 'Quantum', 'favela', 780, 840, null, null, null, '{}'),
(684, 'rock-in-rio', 'sat', 'Major RD', 'favela', 840, 900, null, null, null, '{}'),
(685, 'rock-in-rio', 'sat', 'Noturnall + Russell Allen', 'globalvillage', 720, 780, null, null, null, '{}'),
(686, 'rock-in-rio', 'sat', 'Rhegia', 'globalvillage', 780, 840, null, null, null, '{}'),
(687, 'rock-in-rio', 'sat', 'Korzus', 'globalvillage', 840, 900, null, null, null, '{}'),
(688, 'rock-in-rio', 'sat', 'LVCAS', 'supernova', 720, 780, null, null, null, '{}'),
(689, 'rock-in-rio', 'sat', 'MC Taya', 'supernova', 780, 840, null, null, null, '{}'),
(690, 'rock-in-rio', 'sat', 'Supercombo', 'supernova', 840, 900, null, null, null, '{}'),
(691, 'rock-in-rio', 'sat', 'Zerobadass', 'supernova', 900, 960, null, null, null, '{}'),
(692, 'rock-in-rio', 'sat', 'Supernova', 'supernova', 960, 1020, null, null, null, '{}'),
(693, 'rock-in-rio', 'sun', 'Barão Vermelho (Enconto Formação Original) convida Fernando Magalhães', 'mainstage', 720, 780, null, null, null, '{}'),
(694, 'rock-in-rio', 'sun', 'Black Eyed Peas', 'mainstage', 780, 840, null, 'Hip-Hop / Pop', null, '{}'),
(695, 'rock-in-rio', 'sun', 'Nelly', 'mainstage', 840, 900, null, 'Hip-Hop', null, '{}'),
(696, 'rock-in-rio', 'sun', 'Calvin Harris', 'mainstage', 900, 960, null, 'House / EDM', null, '{}'),
(697, 'rock-in-rio', 'sun', 'BaianaSystem', 'sunset', 720, 780, null, null, null, '{}'),
(698, 'rock-in-rio', 'sun', 'Calema', 'sunset', 780, 840, null, null, null, '{}'),
(699, 'rock-in-rio', 'sun', 'Jota Quest toca Tim Maia', 'sunset', 840, 900, null, null, null, '{}'),
(700, 'rock-in-rio', 'sun', 'Ne-Yo', 'sunset', 900, 960, null, 'R&B', null, '{}'),
(701, 'rock-in-rio', 'sun', 'Casa Bonita | Brisotti & Viot', 'newdanceorder', 720, 780, null, null, null, '{}'),
(702, 'rock-in-rio', 'sun', 'Liu', 'newdanceorder', 780, 840, null, null, null, '{}'),
(703, 'rock-in-rio', 'sun', 'Sofi Tukker', 'newdanceorder', 840, 900, null, 'Dance Pop', null, '{}'),
(704, 'rock-in-rio', 'sun', 'Meduza', 'newdanceorder', 900, 960, null, 'House', null, '{}'),
(705, 'rock-in-rio', 'sun', 'Budah', 'favela', 720, 780, null, null, null, '{}'),
(706, 'rock-in-rio', 'sun', 'Rael', 'favela', 780, 840, null, null, null, '{}'),
(707, 'rock-in-rio', 'sun', 'Xamã', 'favela', 840, 900, null, null, null, '{}'),
(708, 'rock-in-rio', 'sun', 'Bento Gil convida Flor Gil', 'globalvillage', 720, 780, null, null, null, '{}'),
(709, 'rock-in-rio', 'sun', 'Mãeana', 'globalvillage', 780, 840, null, null, null, '{}'),
(710, 'rock-in-rio', 'sun', 'Mohamed Ramadan', 'globalvillage', 840, 900, null, null, null, '{}'),
(711, 'rock-in-rio', 'sun', 'Bayside Kings', 'supernova', 720, 780, null, null, null, '{}'),
(712, 'rock-in-rio', 'sun', 'Matanza Ritual', 'supernova', 780, 840, null, null, null, '{}'),
(713, 'rock-in-rio', 'sun', 'O Escritório', 'supernova', 840, 900, null, null, null, '{}'),
(714, 'rock-in-rio', 'sun', 'João Gordo & Asteroides Trio', 'supernova', 900, 960, null, null, null, '{}'),
(715, 'rock-in-rio', 'mon', 'Gilberto Gil', 'mainstage', 720, 780, null, 'MPB', null, '{}'),
(716, 'rock-in-rio', 'mon', 'Jon Batiste', 'mainstage', 780, 840, null, 'Jazz / Soul', null, '{}'),
(717, 'rock-in-rio', 'mon', 'Luísa Sonza convida Roberto Menescal', 'mainstage', 840, 900, null, null, null, '{}'),
(718, 'rock-in-rio', 'mon', 'Elton John', 'mainstage', 900, 960, null, 'Pop / Rock', null, '{}'),
(719, 'rock-in-rio', 'mon', 'Péricles canta Motown', 'sunset', 720, 780, null, null, null, '{}'),
(720, 'rock-in-rio', 'mon', 'Roupa Nova convida Guilherme Arantes', 'sunset', 780, 840, null, null, null, '{}'),
(721, 'rock-in-rio', 'mon', 'Vanessa da Mata convida Rubel', 'sunset', 840, 900, null, null, null, '{}'),
(722, 'rock-in-rio', 'mon', 'Laufey', 'sunset', 900, 960, null, 'Jazz Pop', null, '{}'),
(723, 'rock-in-rio', 'mon', 'Aline Rocha', 'newdanceorder', 720, 780, null, null, null, '{}'),
(724, 'rock-in-rio', 'mon', 'Leo Janeiro & Simo Not Simon', 'newdanceorder', 780, 840, null, null, null, '{}'),
(725, 'rock-in-rio', 'mon', 'Max Styler', 'newdanceorder', 840, 900, null, null, null, '{}'),
(726, 'rock-in-rio', 'mon', 'Fatboy Slim', 'newdanceorder', 900, 960, null, 'Big Beat', null, '{}'),
(727, 'rock-in-rio', 'mon', 'Mart''nália', 'favela', 720, 780, null, null, null, '{}'),
(728, 'rock-in-rio', 'mon', 'Tiee', 'favela', 780, 840, null, null, null, '{}'),
(729, 'rock-in-rio', 'mon', 'Belo', 'favela', 840, 900, null, null, null, '{}'),
(730, 'rock-in-rio', 'mon', 'Joyce Moreno, Leila Pinheiro e Fernanda Takai', 'globalvillage', 720, 780, null, null, null, '{}'),
(731, 'rock-in-rio', 'mon', 'Wanda Sá', 'globalvillage', 780, 840, null, null, null, '{}'),
(732, 'rock-in-rio', 'mon', 'João Bosco', 'globalvillage', 840, 900, null, null, null, '{}'),
(733, 'rock-in-rio', 'mon', 'Maui', 'supernova', 720, 780, null, null, null, '{}'),
(734, 'rock-in-rio', 'mon', 'Melly', 'supernova', 780, 840, null, null, null, '{}'),
(735, 'rock-in-rio', 'mon', 'Zeca Veloso', 'supernova', 840, 900, null, null, null, '{}'),
(736, 'rock-in-rio', 'mon', 'Alee', 'supernova', 900, 960, null, null, null, '{}'),
(737, 'rock-in-rio', 'fri2', 'Alok – Keep Art Human', 'mainstage', 720, 780, null, 'Brazilian Bass', null, '{}'),
(738, 'rock-in-rio', 'fri2', 'Hwasa', 'mainstage', 780, 840, null, 'K-Pop', null, '{}'),
(739, 'rock-in-rio', 'fri2', 'NEXZ', 'mainstage', 840, 900, null, null, null, '{}'),
(740, 'rock-in-rio', 'fri2', 'Stray Kids', 'mainstage', 900, 960, null, 'K-Pop', null, '{}'),
(741, 'rock-in-rio', 'fri2', 'Jota.Pê convida Luedji Luna e Zaynara', 'sunset', 720, 780, null, null, null, '{}'),
(742, 'rock-in-rio', 'fri2', 'Os Garotin convidam Duquesa', 'sunset', 780, 840, null, null, null, '{}'),
(743, 'rock-in-rio', 'fri2', 'PJ Morton', 'sunset', 840, 900, null, null, null, '{}'),
(744, 'rock-in-rio', 'fri2', 'Jamiroquai', 'sunset', 900, 960, null, 'Funk / Acid Jazz', null, '{}'),
(745, 'rock-in-rio', 'fri2', 'Anna', 'newdanceorder', 720, 780, null, null, null, '{}'),
(746, 'rock-in-rio', 'fri2', 'Departamento', 'newdanceorder', 780, 840, null, null, null, '{}'),
(747, 'rock-in-rio', 'fri2', 'Omiki', 'newdanceorder', 840, 900, null, null, null, '{}'),
(748, 'rock-in-rio', 'fri2', 'Ski Aggu', 'newdanceorder', 900, 960, null, null, null, '{}'),
(749, 'rock-in-rio', 'fri2', 'Neelix & Vegas', 'newdanceorder', 960, 1020, null, null, null, '{}'),
(750, 'rock-in-rio', 'fri2', 'Caio Luccas', 'favela', 720, 780, null, null, null, '{}'),
(751, 'rock-in-rio', 'fri2', 'Puterrier & MC Carol', 'favela', 780, 840, null, null, null, '{}'),
(752, 'rock-in-rio', 'fri2', 'MC Cabelinho convida Tz da Coronel', 'favela', 840, 900, null, null, null, '{}'),
(753, 'rock-in-rio', 'fri2', 'Lambateria com Félix Robatto', 'globalvillage', 720, 780, null, null, null, '{}'),
(754, 'rock-in-rio', 'fri2', 'Rio Bronx', 'globalvillage', 780, 840, null, null, null, '{}'),
(755, 'rock-in-rio', 'fri2', 'Soulidified', 'globalvillage', 840, 900, null, null, null, '{}'),
(756, 'rock-in-rio', 'fri2', 'Ananda', 'supernova', 720, 780, null, null, null, '{}'),
(757, 'rock-in-rio', 'fri2', 'Isa Buzzi', 'supernova', 780, 840, null, null, null, '{}'),
(758, 'rock-in-rio', 'fri2', 'Muse Maya', 'supernova', 840, 900, null, null, null, '{}'),
(759, 'rock-in-rio', 'fri2', 'Nandatsunami', 'supernova', 900, 960, null, null, null, '{}'),
(760, 'rock-in-rio', 'sat2', 'Demi Lovato', 'mainstage', 720, 780, null, 'Pop', null, '{}'),
(761, 'rock-in-rio', 'sat2', 'J Balvin', 'mainstage', 780, 840, null, 'Reggaeton', null, '{}'),
(762, 'rock-in-rio', 'sat2', 'Pedro Sampaio', 'mainstage', 840, 900, null, 'Funk / Pop', null, '{}'),
(763, 'rock-in-rio', 'sat2', 'Maroon 5', 'mainstage', 900, 960, null, 'Pop Rock', null, '{}'),
(764, 'rock-in-rio', 'sat2', 'Criolo, Amaro & Dino', 'sunset', 720, 780, null, null, null, '{}'),
(765, 'rock-in-rio', 'sat2', 'Gilsons convidam Daniela Mercury e Olodum', 'sunset', 780, 840, null, null, null, '{}'),
(766, 'rock-in-rio', 'sat2', 'João Gomes & Orquestra Brasileira', 'sunset', 840, 900, null, null, null, '{}'),
(767, 'rock-in-rio', 'sat2', 'Mumford & Sons', 'sunset', 900, 960, null, 'Folk Rock', null, '{}'),
(768, 'rock-in-rio', 'sat2', 'Adam Sellouk', 'newdanceorder', 720, 780, null, null, null, '{}'),
(769, 'rock-in-rio', 'sat2', 'Bhaskar', 'newdanceorder', 780, 840, null, null, null, '{}'),
(770, 'rock-in-rio', 'sat2', 'Ekanta & Swarup', 'newdanceorder', 840, 900, null, null, null, '{}'),
(771, 'rock-in-rio', 'sat2', 'Gabe', 'newdanceorder', 900, 960, null, null, null, '{}'),
(772, 'rock-in-rio', 'sat2', 'Alok & Family pres. Rave The World', 'newdanceorder', 960, 1020, null, null, null, '{}'),
(773, 'rock-in-rio', 'sat2', 'Priscila Senna', 'favela', 720, 780, null, null, null, '{}'),
(774, 'rock-in-rio', 'sat2', 'Soul de Brasileiro', 'favela', 780, 840, null, null, null, '{}'),
(775, 'rock-in-rio', 'sat2', 'Timbalada', 'favela', 840, 900, null, null, null, '{}'),
(776, 'rock-in-rio', 'sat2', 'Badi Assad', 'globalvillage', 720, 780, null, null, null, '{}'),
(777, 'rock-in-rio', 'sat2', 'Hamilton de Holanda', 'globalvillage', 780, 840, null, null, null, '{}'),
(778, 'rock-in-rio', 'sat2', 'Mestrinho', 'globalvillage', 840, 900, null, null, null, '{}'),
(779, 'rock-in-rio', 'sat2', 'Celo DUT', 'supernova', 720, 780, null, null, null, '{}'),
(780, 'rock-in-rio', 'sat2', 'Milo J', 'supernova', 780, 840, null, null, null, '{}'),
(781, 'rock-in-rio', 'sat2', 'Yago Oproprio', 'supernova', 840, 900, null, null, null, '{}'),
(782, 'rock-in-rio', 'sat2', 'Delacruz', 'supernova', 900, 960, null, null, null, '{}'),
(783, 'rock-in-rio', 'sun2', 'Halsey', 'mainstage', 720, 780, null, 'Pop', null, '{}'),
(784, 'rock-in-rio', 'sun2', 'Ivete Sangalo', 'mainstage', 780, 840, null, 'Axé', null, '{}'),
(785, 'rock-in-rio', 'sun2', 'Lola Young', 'mainstage', 840, 900, null, 'Pop / Soul', null, '{}'),
(786, 'rock-in-rio', 'sun2', 'Twenty One Pilots', 'mainstage', 900, 960, null, 'Alt-Pop / Rock', null, '{}'),
(787, 'rock-in-rio', 'sun2', 'Carol Biazin convida Joyce Alane', 'sunset', 720, 780, null, null, null, '{}'),
(788, 'rock-in-rio', 'sun2', 'Joelma convida Viviane Batidão', 'sunset', 780, 840, null, null, null, '{}'),
(789, 'rock-in-rio', 'sun2', 'Marina Sena convida Céu', 'sunset', 840, 900, null, null, null, '{}'),
(790, 'rock-in-rio', 'sun2', 'Zara Larsson', 'sunset', 900, 960, null, 'Pop', null, '{}'),
(791, 'rock-in-rio', 'sun2', 'Dawn Patrol | Maz, Antdot, Riascode, Bakka', 'newdanceorder', 720, 780, null, null, null, '{}'),
(792, 'rock-in-rio', 'sun2', 'Illusionize', 'newdanceorder', 780, 840, null, null, null, '{}'),
(793, 'rock-in-rio', 'sun2', 'Roddy Lima', 'newdanceorder', 840, 900, null, null, null, '{}'),
(794, 'rock-in-rio', 'sun2', 'John Summit', 'newdanceorder', 900, 960, null, 'House', null, '{}'),
(795, 'rock-in-rio', 'sun2', 'Marvvila', 'favela', 720, 780, null, null, null, '{}'),
(796, 'rock-in-rio', 'sun2', 'Suel', 'favela', 780, 840, null, null, null, '{}'),
(797, 'rock-in-rio', 'sun2', 'Dennis', 'favela', 840, 900, null, null, null, '{}'),
(798, 'rock-in-rio', 'sun2', 'Kynnie', 'globalvillage', 720, 780, null, null, null, '{}'),
(799, 'rock-in-rio', 'sun2', 'Lucy Alves', 'globalvillage', 780, 840, null, null, null, '{}'),
(800, 'rock-in-rio', 'sun2', 'Haley Smalls', 'globalvillage', 840, 900, null, null, null, '{}'),
(801, 'rock-in-rio', 'sun2', 'AR Baby', 'supernova', 720, 780, null, null, null, '{}'),
(802, 'rock-in-rio', 'sun2', 'Bruna Black', 'supernova', 780, 840, null, null, null, '{}'),
(803, 'rock-in-rio', 'sun2', 'Sant', 'supernova', 840, 900, null, null, null, '{}'),
(804, 'rock-in-rio', 'sun2', 'Lourena', 'supernova', 900, 960, null, null, null, '{}')
on conflict (id) do nothing;
