-- Real Louder Than Life 2026 lineup (Louisville, KY, Sep 17-20), with real
-- published set times -- transcribed directly from therockfather.com's
-- "Louder Than Life 2026 Set Times Are Here" article (exact clock times
-- per stage per day, not placeholders). 198 sets across 4 days and all 7
-- official stages (Louder, Life, Decibel, Reverb, Loudmouth, Impact, Big
-- Bourbon Bar). start_min/end_min are offsets from the day's 10:45am gate
-- time (FESTIVAL_DAYS startMin), computed from each act's real start time
-- and the next act's start time on the same stage; the last act of each
-- stage/day gets a 75-minute default since no closing time is published.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(805, 'louder-than-life', 'thu', 'The Violent Hour', 'louder', 70, 125, null, null, null, '{}'),
(806, 'louder-than-life', 'thu', 'Metal Church', 'louder', 125, 190, null, null, null, '{}'),
(807, 'louder-than-life', 'thu', 'Suicidal Tendencies', 'louder', 190, 270, null, null, null, '{}'),
(808, 'louder-than-life', 'thu', 'Anthrax', 'louder', 270, 360, null, 'Thrash Metal', null, '{}'),
(809, 'louder-than-life', 'thu', 'Alice Cooper', 'louder', 360, 470, null, 'Shock Rock', null, '{}'),
(810, 'louder-than-life', 'thu', 'Megadeth', 'louder', 470, 600, null, 'Thrash Metal', null, '{}'),
(811, 'louder-than-life', 'thu', 'Iron Maiden', 'louder', 600, 675, null, 'Heavy Metal', null, '{}'),
(812, 'louder-than-life', 'thu', 'Chained Saint', 'life', 45, 95, null, null, null, '{}'),
(813, 'louder-than-life', 'thu', 'Mac Sabbath', 'life', 95, 155, null, null, null, '{}'),
(814, 'louder-than-life', 'thu', 'Gwar', 'life', 155, 225, null, null, null, '{}'),
(815, 'louder-than-life', 'thu', 'Machine Head', 'life', 225, 315, null, 'Groove Metal', null, '{}'),
(816, 'louder-than-life', 'thu', 'Sabaton', 'life', 315, 415, null, 'Power Metal', null, '{}'),
(817, 'louder-than-life', 'thu', 'Danzig', 'life', 415, 525, null, 'Metal', null, '{}'),
(818, 'louder-than-life', 'thu', 'Pantera', 'life', 525, 600, null, 'Groove Metal', null, '{}'),
(819, 'louder-than-life', 'thu', 'The Ataris', 'decibel', 165, 235, null, null, null, '{}'),
(820, 'louder-than-life', 'thu', 'Lit', 'decibel', 235, 305, null, null, null, '{}'),
(821, 'louder-than-life', 'thu', 'Bowling For Soup', 'decibel', 305, 380, null, 'Pop Punk', null, '{}'),
(822, 'louder-than-life', 'thu', 'Alkaline Trio', 'decibel', 380, 470, null, null, null, '{}'),
(823, 'louder-than-life', 'thu', 'Hot Mulligan', 'decibel', 470, 570, null, null, null, '{}'),
(824, 'louder-than-life', 'thu', 'Jimmy Eat World', 'decibel', 570, 680, null, 'Emo / Rock', null, '{}'),
(825, 'louder-than-life', 'thu', 'Rise Against', 'decibel', 680, 755, null, 'Punk Rock', null, '{}'),
(826, 'louder-than-life', 'thu', 'Zero 9:36', 'reverb', 130, 200, null, null, null, '{}'),
(827, 'louder-than-life', 'thu', 'Adelitas Way', 'reverb', 200, 270, null, null, null, '{}'),
(828, 'louder-than-life', 'thu', 'The Rasmus', 'reverb', 270, 345, null, null, null, '{}'),
(829, 'louder-than-life', 'thu', 'Red', 'reverb', 345, 425, null, null, null, '{}'),
(830, 'louder-than-life', 'thu', 'From Ashes to New', 'reverb', 425, 520, null, null, null, '{}'),
(831, 'louder-than-life', 'thu', 'Starset', 'reverb', 520, 625, null, 'Rock', null, '{}'),
(832, 'louder-than-life', 'thu', 'Skillet', 'reverb', 625, 700, null, 'Christian Rock', null, '{}'),
(833, 'louder-than-life', 'thu', 'Vianova', 'loudmouth', 150, 230, null, null, null, '{}'),
(834, 'louder-than-life', 'thu', 'Cane Hill', 'loudmouth', 230, 310, null, null, null, '{}'),
(835, 'louder-than-life', 'thu', 'Like Moths To Flames', 'loudmouth', 310, 395, null, null, null, '{}'),
(836, 'louder-than-life', 'thu', 'Volumes', 'loudmouth', 395, 470, null, null, null, '{}'),
(837, 'louder-than-life', 'thu', 'Erra', 'loudmouth', 470, 570, null, null, null, '{}'),
(838, 'louder-than-life', 'thu', 'Currents', 'loudmouth', 570, 680, null, null, null, '{}'),
(839, 'louder-than-life', 'thu', 'Fit For A King', 'loudmouth', 680, 755, null, null, null, '{}'),
(840, 'louder-than-life', 'thu', 'King 810', 'impact', 75, 135, null, null, null, '{}'),
(841, 'louder-than-life', 'thu', 'Signs of the Swarm', 'impact', 135, 200, null, null, null, '{}'),
(842, 'louder-than-life', 'thu', 'Born of Osiris', 'impact', 200, 270, null, null, null, '{}'),
(843, 'louder-than-life', 'thu', 'Emmure', 'impact', 270, 350, null, null, null, '{}'),
(844, 'louder-than-life', 'thu', 'The Acacia Strain', 'impact', 350, 425, null, null, null, '{}'),
(845, 'louder-than-life', 'thu', 'After The Burial', 'impact', 425, 625, null, null, null, '{}'),
(846, 'louder-than-life', 'thu', 'Chelsea Grin', 'impact', 625, 700, null, null, null, '{}'),
(847, 'louder-than-life', 'thu', 'Set For Tomorrow', 'bigbourbon', 45, 105, null, null, null, '{}'),
(848, 'louder-than-life', 'thu', 'Sent By Ravens', 'bigbourbon', 105, 165, null, null, null, '{}'),
(849, 'louder-than-life', 'thu', 'Holy Wars', 'bigbourbon', 165, 255, null, null, null, '{}'),
(850, 'louder-than-life', 'thu', 'Dark Divine', 'bigbourbon', 255, 340, null, null, null, '{}'),
(851, 'louder-than-life', 'thu', 'Elijah', 'bigbourbon', 340, 395, null, null, null, '{}'),
(852, 'louder-than-life', 'thu', 'Archers', 'bigbourbon', 395, 515, null, null, null, '{}'),
(853, 'louder-than-life', 'thu', 'Thousand Below', 'bigbourbon', 515, 590, null, null, null, '{}'),
(854, 'louder-than-life', 'fri', 'The Red Jumpsuit Apparatus', 'louder', 80, 150, null, null, null, '{}'),
(855, 'louder-than-life', 'fri', 'L.S. Dunes', 'louder', 150, 220, null, null, null, '{}'),
(856, 'louder-than-life', 'fri', 'We The Kings', 'louder', 220, 305, null, null, null, '{}'),
(857, 'louder-than-life', 'fri', 'Coheed and Cambria', 'louder', 305, 405, null, 'Prog Rock', null, '{}'),
(858, 'louder-than-life', 'fri', 'Taking Back Sunday', 'louder', 405, 505, null, 'Emo', null, '{}'),
(859, 'louder-than-life', 'fri', 'A Day To Remember', 'louder', 505, 640, null, 'Metalcore / Pop Punk', null, '{}'),
(860, 'louder-than-life', 'fri', 'My Chemical Romance', 'louder', 640, 715, null, 'Emo / Rock', null, '{}'),
(861, 'louder-than-life', 'fri', 'IVRI', 'life', 45, 115, null, null, null, '{}'),
(862, 'louder-than-life', 'fri', 'Lacey Sturm', 'life', 115, 185, null, null, null, '{}'),
(863, 'louder-than-life', 'fri', 'Get Scared', 'life', 185, 260, null, null, null, '{}'),
(864, 'louder-than-life', 'fri', 'Loathe', 'life', 260, 355, null, null, null, '{}'),
(865, 'louder-than-life', 'fri', 'Sleeping With Sirens', 'life', 355, 455, null, 'Post-Hardcore', null, '{}'),
(866, 'louder-than-life', 'fri', 'The Used', 'life', 455, 570, null, 'Post-Hardcore', null, '{}'),
(867, 'louder-than-life', 'fri', 'Pierce The Veil', 'life', 570, 645, null, 'Post-Hardcore', null, '{}'),
(868, 'louder-than-life', 'fri', 'American Monster', 'decibel', 180, 250, null, null, null, '{}'),
(869, 'louder-than-life', 'fri', 'Showing Teeth', 'decibel', 250, 320, null, null, null, '{}'),
(870, 'louder-than-life', 'fri', 'Vana', 'decibel', 320, 390, null, null, null, '{}'),
(871, 'louder-than-life', 'fri', 'Scene Queen', 'decibel', 390, 460, null, null, null, '{}'),
(872, 'louder-than-life', 'fri', 'Dead Poet Society', 'decibel', 460, 570, null, null, null, '{}'),
(873, 'louder-than-life', 'fri', 'The Warning', 'decibel', 570, 675, null, null, null, '{}'),
(874, 'louder-than-life', 'fri', 'The Pretty Reckless', 'decibel', 675, 750, null, 'Rock', null, '{}'),
(875, 'louder-than-life', 'fri', 'Death Valley Dreams', 'reverb', 145, 215, null, null, null, '{}'),
(876, 'louder-than-life', 'fri', 'Butcher Babies', 'reverb', 215, 285, null, null, null, '{}'),
(877, 'louder-than-life', 'fri', 'Mushroomhead', 'reverb', 285, 355, null, null, null, '{}'),
(878, 'louder-than-life', 'fri', 'Soulfly', 'reverb', 355, 425, null, null, null, '{}'),
(879, 'louder-than-life', 'fri', 'Blue Medusa feat. Alissa White-Gluz', 'reverb', 425, 520, null, null, null, '{}'),
(880, 'louder-than-life', 'fri', 'Cavalera', 'reverb', 520, 620, null, 'Thrash Metal', null, '{}'),
(881, 'louder-than-life', 'fri', 'Chad Gray', 'reverb', 620, 695, null, null, null, '{}'),
(882, 'louder-than-life', 'fri', 'Cenobia', 'loudmouth', 115, 170, null, null, null, '{}'),
(883, 'louder-than-life', 'fri', 'Nevertel', 'loudmouth', 170, 235, null, null, null, '{}'),
(884, 'louder-than-life', 'fri', 'Wind Walkers', 'loudmouth', 235, 290, null, null, null, '{}'),
(885, 'louder-than-life', 'fri', 'Rain City Drive', 'loudmouth', 290, 345, null, null, null, '{}'),
(886, 'louder-than-life', 'fri', 'The Word Alive', 'loudmouth', 345, 400, null, null, null, '{}'),
(887, 'louder-than-life', 'fri', 'Holding Absence', 'loudmouth', 400, 460, null, null, null, '{}'),
(888, 'louder-than-life', 'fri', 'President', 'loudmouth', 460, 535, null, null, null, '{}'),
(889, 'louder-than-life', 'fri', 'Gates To Hell', 'impact', 210, 265, null, null, null, '{}'),
(890, 'louder-than-life', 'fri', 'Missing Link', 'impact', 265, 320, null, null, null, '{}'),
(891, 'louder-than-life', 'fri', 'Koyo', 'impact', 320, 375, null, null, null, '{}'),
(892, 'louder-than-life', 'fri', 'Twitching Tongues', 'impact', 375, 430, null, null, null, '{}'),
(893, 'louder-than-life', 'fri', 'Angel Du$t', 'impact', 430, 485, null, null, null, '{}'),
(894, 'louder-than-life', 'fri', 'Haywire', 'impact', 485, 570, null, null, null, '{}'),
(895, 'louder-than-life', 'fri', 'TBA', 'impact', 570, 645, null, null, null, '{}'),
(896, 'louder-than-life', 'fri', 'Billy McNicol', 'bigbourbon', 80, 145, null, null, null, '{}'),
(897, 'louder-than-life', 'fri', '40 Below Summer', 'bigbourbon', 145, 195, null, null, null, '{}'),
(898, 'louder-than-life', 'fri', 'Earshot', 'bigbourbon', 195, 250, null, null, null, '{}'),
(899, 'louder-than-life', 'fri', 'Primer 55', 'bigbourbon', 250, 320, null, null, null, '{}'),
(900, 'louder-than-life', 'fri', 'Dry Kill Logic', 'bigbourbon', 320, 375, null, null, null, '{}'),
(901, 'louder-than-life', 'fri', 'Jeff Hardy', 'bigbourbon', 375, 495, null, null, null, '{}'),
(902, 'louder-than-life', 'fri', 'Soil', 'bigbourbon', 495, 570, null, null, null, '{}'),
(903, 'louder-than-life', 'sat', 'Josey Scott: The Original Voice of Saliva', 'louder', 80, 150, null, null, null, '{}'),
(904, 'louder-than-life', 'sat', 'Alien Ant Farm', 'louder', 150, 225, null, null, null, '{}'),
(905, 'louder-than-life', 'sat', 'P.O.D.', 'louder', 225, 320, null, 'Nu Metal', null, '{}'),
(906, 'louder-than-life', 'sat', 'Tom Morello', 'louder', 320, 420, null, 'Rock', null, '{}'),
(907, 'louder-than-life', 'sat', 'Bilmuri', 'louder', 420, 525, null, null, null, '{}'),
(908, 'louder-than-life', 'sat', 'Sublime', 'louder', 525, 660, null, 'Ska Punk', null, '{}'),
(909, 'louder-than-life', 'sat', 'Limp Bizkit', 'louder', 660, 735, null, 'Nu Metal', null, '{}'),
(910, 'louder-than-life', 'sat', 'TX2', 'life', 45, 115, null, null, null, '{}'),
(911, 'louder-than-life', 'sat', 'The Funeral Portrait', 'life', 115, 185, null, null, null, '{}'),
(912, 'louder-than-life', 'sat', 'Set It Off', 'life', 185, 270, null, null, null, '{}'),
(913, 'louder-than-life', 'sat', 'Nothing More', 'life', 270, 370, null, null, null, '{}'),
(914, 'louder-than-life', 'sat', 'Ice Nine Kills', 'life', 370, 470, null, 'Metalcore', null, '{}'),
(915, 'louder-than-life', 'sat', 'Babymetal', 'life', 470, 580, null, 'Metal / J-Pop', null, '{}'),
(916, 'louder-than-life', 'sat', 'Papa Roach', 'life', 580, 655, null, 'Nu Metal', null, '{}'),
(917, 'louder-than-life', 'sat', 'Diamante', 'decibel', 45, 115, null, null, null, '{}'),
(918, 'louder-than-life', 'sat', 'Kami Kehoe', 'decibel', 115, 185, null, null, null, '{}'),
(919, 'louder-than-life', 'sat', 'Icon For Hire', 'decibel', 185, 255, null, null, null, '{}'),
(920, 'louder-than-life', 'sat', 'Orianthi', 'decibel', 255, 340, null, null, null, '{}'),
(921, 'louder-than-life', 'sat', 'Lindsey Stirling', 'decibel', 340, 440, null, 'Violin / Electronic', null, '{}'),
(922, 'louder-than-life', 'sat', 'In This Moment', 'decibel', 440, 540, null, 'Metal', null, '{}'),
(923, 'louder-than-life', 'sat', 'Halestorm', 'decibel', 540, 615, null, 'Hard Rock', null, '{}'),
(924, 'louder-than-life', 'sat', 'Emarosa', 'reverb', 80, 150, null, null, null, '{}'),
(925, 'louder-than-life', 'sat', 'Scary Kids Scaring Kids', 'reverb', 150, 220, null, null, null, '{}'),
(926, 'louder-than-life', 'sat', 'Hail The Sun', 'reverb', 220, 295, null, null, null, '{}'),
(927, 'louder-than-life', 'sat', 'Thursday', 'reverb', 295, 390, null, 'Post-Hardcore', null, '{}'),
(928, 'louder-than-life', 'sat', 'Chiodos', 'reverb', 390, 490, null, null, null, '{}'),
(929, 'louder-than-life', 'sat', 'Dance Gavin Dance', 'reverb', 490, 595, null, 'Post-Hardcore', null, '{}'),
(930, 'louder-than-life', 'sat', 'Circa Survive', 'reverb', 595, 670, null, 'Prog Rock', null, '{}'),
(931, 'louder-than-life', 'sat', 'Freeze The Fall', 'loudmouth', 115, 165, null, null, null, '{}'),
(932, 'louder-than-life', 'sat', 'Heavy//Hitter', 'loudmouth', 165, 220, null, null, null, '{}'),
(933, 'louder-than-life', 'sat', 'Silly Goose', 'loudmouth', 220, 275, null, null, null, '{}'),
(934, 'louder-than-life', 'sat', 'Fox Lake', 'loudmouth', 275, 330, null, null, null, '{}'),
(935, 'louder-than-life', 'sat', 'Peeling Flesh', 'loudmouth', 330, 395, null, null, null, '{}'),
(936, 'louder-than-life', 'sat', 'Spite', 'loudmouth', 395, 460, null, null, null, '{}'),
(937, 'louder-than-life', 'sat', 'Boundaries', 'loudmouth', 460, 530, null, null, null, '{}'),
(938, 'louder-than-life', 'sat', 'Kublai Khan TX', 'loudmouth', 530, 605, null, 'Metalcore', null, '{}'),
(939, 'louder-than-life', 'sat', 'Codefendants', 'impact', 135, 190, null, null, null, '{}'),
(940, 'louder-than-life', 'sat', 'Many Eyes', 'impact', 190, 245, null, null, null, '{}'),
(941, 'louder-than-life', 'sat', 'The Barbarians of California', 'impact', 245, 305, null, null, null, '{}'),
(942, 'louder-than-life', 'sat', 'H2O', 'impact', 305, 365, null, null, null, '{}'),
(943, 'louder-than-life', 'sat', 'Madball', 'impact', 365, 430, null, null, null, '{}'),
(944, 'louder-than-life', 'sat', 'Agnostic Front', 'impact', 430, 500, null, null, null, '{}'),
(945, 'louder-than-life', 'sat', 'Blood For Blood', 'impact', 500, 575, null, null, null, '{}'),
(946, 'louder-than-life', 'sat', 'As You Were', 'bigbourbon', 180, 230, null, null, null, '{}'),
(947, 'louder-than-life', 'sat', 'Doobie', 'bigbourbon', 230, 280, null, null, null, '{}'),
(948, 'louder-than-life', 'sat', 'No Resolve', 'bigbourbon', 280, 335, null, null, null, '{}'),
(949, 'louder-than-life', 'sat', 'Spoken', 'bigbourbon', 335, 390, null, null, null, '{}'),
(950, 'louder-than-life', 'sat', 'Otherwise', 'bigbourbon', 390, 445, null, null, null, '{}'),
(951, 'louder-than-life', 'sat', 'Tantric', 'bigbourbon', 445, 505, null, null, null, '{}'),
(952, 'louder-than-life', 'sat', 'Texas Hippie Coalition', 'bigbourbon', 505, 560, null, null, null, '{}'),
(953, 'louder-than-life', 'sat', 'Powerman 5000', 'bigbourbon', 560, 635, null, null, null, '{}'),
(954, 'louder-than-life', 'sun', 'Rivers of Nihil', 'louder', 45, 135, null, null, null, '{}'),
(955, 'louder-than-life', 'sun', 'Toadies', 'louder', 135, 210, null, null, null, '{}'),
(956, 'louder-than-life', 'sun', 'Filter', 'louder', 210, 300, null, null, null, '{}'),
(957, 'louder-than-life', 'sun', 'Ministry', 'louder', 300, 400, null, 'Industrial Metal', null, '{}'),
(958, 'louder-than-life', 'sun', 'The Mars Volta', 'louder', 400, 505, null, 'Prog Rock', null, '{}'),
(959, 'louder-than-life', 'sun', 'Danny Elfman', 'louder', 505, 640, null, 'Film Score / Rock', null, '{}'),
(960, 'louder-than-life', 'sun', 'Tool', 'louder', 640, 715, null, 'Prog Metal', null, '{}'),
(961, 'louder-than-life', 'sun', 'Between The Buried and Me', 'life', 100, 170, null, null, null, '{}'),
(962, 'louder-than-life', 'sun', 'Animals as Leaders', 'life', 170, 250, null, null, null, '{}'),
(963, 'louder-than-life', 'sun', 'Dethklok', 'life', 250, 350, null, null, null, '{}'),
(964, 'louder-than-life', 'sun', 'Black Label Society', 'life', 350, 450, null, 'Metal', null, '{}'),
(965, 'louder-than-life', 'sun', 'Mastodon', 'life', 450, 570, null, 'Metal', null, '{}'),
(966, 'louder-than-life', 'sun', 'Gojira', 'life', 570, 645, null, 'Metal', null, '{}'),
(967, 'louder-than-life', 'sun', 'Austin Carlile', 'decibel', 45, 115, null, null, null, '{}'),
(968, 'louder-than-life', 'sun', 'Caskets', 'decibel', 115, 185, null, null, null, '{}'),
(969, 'louder-than-life', 'sun', 'I See Stars', 'decibel', 185, 255, null, null, null, '{}'),
(970, 'louder-than-life', 'sun', 'Escape The Fate', 'decibel', 255, 325, null, null, null, '{}'),
(971, 'louder-than-life', 'sun', 'Atreyu', 'decibel', 325, 405, null, 'Metalcore', null, '{}'),
(972, 'louder-than-life', 'sun', 'Black Veil Brides', 'decibel', 405, 490, null, null, null, '{}'),
(973, 'louder-than-life', 'sun', 'Killswitch Engage', 'decibel', 490, 580, null, 'Metalcore', null, '{}'),
(974, 'louder-than-life', 'sun', 'The Prodigy', 'decibel', 580, 655, null, 'Electronic / Rock', null, '{}'),
(975, 'louder-than-life', 'sun', 'He Is Legend', 'reverb', 80, 150, null, null, null, '{}'),
(976, 'louder-than-life', 'sun', 'Maylene and the Sons of Disaster', 'reverb', 150, 220, null, null, null, '{}'),
(977, 'louder-than-life', 'sun', 'Emery', 'reverb', 220, 290, null, null, null, '{}'),
(978, 'louder-than-life', 'sun', 'Haste The Day', 'reverb', 290, 365, null, null, null, '{}'),
(979, 'louder-than-life', 'sun', 'Alexisonfire', 'reverb', 365, 450, null, 'Post-Hardcore', null, '{}'),
(980, 'louder-than-life', 'sun', 'Thrice', 'reverb', 450, 535, null, 'Rock', null, '{}'),
(981, 'louder-than-life', 'sun', 'Underoath', 'reverb', 535, 610, null, 'Post-Hardcore', null, '{}'),
(982, 'louder-than-life', 'sun', 'Sace6', 'loudmouth', 150, 220, null, null, null, '{}'),
(983, 'louder-than-life', 'sun', 'The Pretty Wild', 'loudmouth', 220, 290, null, null, null, '{}'),
(984, 'louder-than-life', 'sun', 'Arrows In Action', 'loudmouth', 290, 365, null, null, null, '{}'),
(985, 'louder-than-life', 'sun', 'Holywatr', 'loudmouth', 365, 495, null, null, null, '{}'),
(986, 'louder-than-life', 'sun', 'Jutes', 'loudmouth', 495, 600, null, null, null, '{}'),
(987, 'louder-than-life', 'sun', 'The Home Team', 'loudmouth', 600, 680, null, null, null, '{}'),
(988, 'louder-than-life', 'sun', 'Sleep Theory', 'loudmouth', 680, 755, null, null, null, '{}'),
(989, 'louder-than-life', 'sun', 'Surfaced', 'impact', 115, 185, null, null, null, '{}'),
(990, 'louder-than-life', 'sun', 'Boltcutter', 'impact', 185, 255, null, null, null, '{}'),
(991, 'louder-than-life', 'sun', 'Corpse Pile', 'impact', 255, 325, null, null, null, '{}'),
(992, 'louder-than-life', 'sun', '200 Stab Wounds', 'impact', 325, 405, null, null, null, '{}'),
(993, 'louder-than-life', 'sun', 'End It', 'impact', 405, 490, null, null, null, '{}'),
(994, 'louder-than-life', 'sun', 'Locked Shut', 'impact', 490, 580, null, null, null, '{}'),
(995, 'louder-than-life', 'sun', 'Sunami', 'impact', 580, 655, null, null, null, '{}'),
(996, 'louder-than-life', 'sun', 'Future Palace', 'bigbourbon', 180, 315, null, null, null, '{}'),
(997, 'louder-than-life', 'sun', 'Dreamwake', 'bigbourbon', 315, 400, null, null, null, '{}'),
(998, 'louder-than-life', 'sun', 'Resolve', 'bigbourbon', 400, 455, null, null, null, '{}'),
(999, 'louder-than-life', 'sun', 'Downswing', 'bigbourbon', 455, 520, null, null, null, '{}'),
(1000, 'louder-than-life', 'sun', 'Aviana', 'bigbourbon', 520, 575, null, null, null, '{}'),
(1001, 'louder-than-life', 'sun', 'Greyhaven', 'bigbourbon', 575, 645, null, null, null, '{}'),
(1002, 'louder-than-life', 'sun', '156/Silence', 'bigbourbon', 645, 720, null, null, null, '{}')
on conflict (id) do nothing;
