-- Bourbon & Beyond 2026 (Highland Festival Grounds at KY Expo Center,
-- Louisville, Sep 24-27) -- real per-artist set times for all 5 official
-- stages (Oak, Barrel, 100 Proof, Revival, The Bluegrass Situation) across
-- all 4 real days, extracted directly from bourbonandbeyond.com's own
-- interactive TIMELINE schedule widget (all 20 day/stage combinations).
-- Note: the official 2026 lineup poster (musicfestivalwizard.com mirror)
-- lists "Joan Jett and the Blackhearts" as a Thursday headliner-tier act,
-- but she does not appear anywhere in the live TIMELINE widget across any
-- of the 5 stages -- likely a lineup change since the poster's original
-- announcement. Not included here since no confirmed stage/time exists for
-- her in the actual schedule data (same rule as elsewhere: no guessing).
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(1123, 'bourbon-and-beyond', 'thu', 'Langhorne Slim', 'oak', 60, 90, null, 'Folk Rock', null, '{}'),
(1124, 'bourbon-and-beyond', 'thu', 'The Return Of Jackie & Judy', 'oak', 135, 170, null, null, null, '{}'),
(1125, 'bourbon-and-beyond', 'thu', 'Gary Clark Jr.', 'oak', 225, 270, null, 'Blues Rock', null, '{}'),
(1126, 'bourbon-and-beyond', 'thu', 'Live', 'oak', 325, 375, null, 'Alt Rock', null, '{}'),
(1127, 'bourbon-and-beyond', 'thu', 'The War on Drugs', 'oak', 440, 495, null, 'Indie Rock', null, '{}'),
(1128, 'bourbon-and-beyond', 'thu', 'Foo Fighters', 'oak', 565, 685, null, 'Rock', null, '{}'),
(1129, 'bourbon-and-beyond', 'thu', 'Congress The Band', 'barrel', 30, 60, null, null, null, '{}'),
(1130, 'bourbon-and-beyond', 'thu', 'The Stews', 'barrel', 100, 130, null, null, null, '{}'),
(1131, 'bourbon-and-beyond', 'thu', 'Cheap Trick', 'barrel', 175, 220, null, 'Rock', null, '{}'),
(1132, 'bourbon-and-beyond', 'thu', '4 Non Blondes', 'barrel', 275, 320, null, 'Rock', null, '{}'),
(1133, 'bourbon-and-beyond', 'thu', 'Goose', 'barrel', 380, 435, null, 'Jam Band', null, '{}'),
(1134, 'bourbon-and-beyond', 'thu', 'Queens of the Stone Age', 'barrel', 500, 560, null, 'Rock', null, '{}'),
(1135, 'bourbon-and-beyond', 'thu', 'Stanley Simmons', '100proof', 115, 145, null, null, null, '{}'),
(1136, 'bourbon-and-beyond', 'thu', 'Kevian Kraemer', '100proof', 185, 215, null, null, null, '{}'),
(1137, 'bourbon-and-beyond', 'thu', 'Howie Day', '100proof', 255, 285, null, null, null, '{}'),
(1138, 'bourbon-and-beyond', 'thu', 'Nine Days', '100proof', 325, 355, null, 'Rock', null, '{}'),
(1139, 'bourbon-and-beyond', 'thu', 'Plain White T''s', '100proof', 405, 450, null, 'Pop Rock', null, '{}'),
(1140, 'bourbon-and-beyond', 'thu', 'The Fray', '100proof', 510, 560, null, 'Pop Rock', null, '{}'),
(1141, 'bourbon-and-beyond', 'thu', 'Penelope Road', 'revival', 150, 180, null, null, null, '{}'),
(1142, 'bourbon-and-beyond', 'thu', 'S.G. Goodman', 'revival', 220, 250, null, null, null, '{}'),
(1143, 'bourbon-and-beyond', 'thu', 'hey, nothing', 'revival', 290, 320, null, null, null, '{}'),
(1144, 'bourbon-and-beyond', 'thu', 'Couch', 'revival', 360, 400, null, null, null, '{}'),
(1145, 'bourbon-and-beyond', 'thu', 'Lindsey Stirling', 'revival', 455, 505, null, 'Electronic / Violin', null, '{}'),
(1146, 'bourbon-and-beyond', 'thu', 'Caitlynne Curtis', 'bluegrass', 45, 75, null, null, null, '{}'),
(1147, 'bourbon-and-beyond', 'thu', 'As You Were', 'bluegrass', 105, 135, null, null, null, '{}'),
(1148, 'bourbon-and-beyond', 'thu', 'Wood Box Heroes', 'bluegrass', 165, 195, null, null, null, '{}'),
(1149, 'bourbon-and-beyond', 'thu', 'Mason Via', 'bluegrass', 225, 255, null, null, null, '{}'),
(1150, 'bourbon-and-beyond', 'thu', 'Magoo', 'bluegrass', 285, 315, null, null, null, '{}'),
(1151, 'bourbon-and-beyond', 'thu', 'Sierra Hull', 'bluegrass', 345, 385, null, 'Bluegrass', null, '{}'),
(1152, 'bourbon-and-beyond', 'fri', 'Noah Rinker', 'oak', 65, 105, null, null, null, '{}'),
(1153, 'bourbon-and-beyond', 'fri', 'The Devil Makes Three', 'oak', 155, 195, null, 'Americana', null, '{}'),
(1154, 'bourbon-and-beyond', 'fri', 'Angus and Julia Stone', 'oak', 245, 285, null, 'Indie Folk', null, '{}'),
(1155, 'bourbon-and-beyond', 'fri', 'Father John Misty', 'oak', 340, 390, null, 'Indie Folk', null, '{}'),
(1156, 'bourbon-and-beyond', 'fri', 'Foster The People', 'oak', 450, 510, null, 'Indie Pop', null, '{}'),
(1157, 'bourbon-and-beyond', 'fri', 'Mumford & Sons', 'oak', 590, 680, null, 'Folk Rock', null, '{}'),
(1158, 'bourbon-and-beyond', 'fri', 'Nathan Bess', 'barrel', 30, 60, null, null, null, '{}'),
(1159, 'bourbon-and-beyond', 'fri', 'Gabriella Rose', 'barrel', 110, 150, null, null, null, '{}'),
(1160, 'bourbon-and-beyond', 'fri', 'St. Paul & The Broken Bones', 'barrel', 200, 240, null, 'Soul', null, '{}'),
(1161, 'bourbon-and-beyond', 'fri', 'Marcus King Band', 'barrel', 290, 335, null, 'Blues Rock', null, '{}'),
(1162, 'bourbon-and-beyond', 'fri', 'Of Monsters and Men', 'barrel', 395, 445, null, 'Indie Folk', null, '{}'),
(1163, 'bourbon-and-beyond', 'fri', 'Kacey Musgraves', 'barrel', 515, 585, null, 'Country / Pop', null, '{}'),
(1164, 'bourbon-and-beyond', 'fri', 'Ben Chapman', '100proof', 105, 135, null, null, null, '{}'),
(1165, 'bourbon-and-beyond', 'fri', 'Sawyer Hill', '100proof', 180, 215, null, null, null, '{}'),
(1166, 'bourbon-and-beyond', 'fri', 'Henrik', '100proof', 260, 295, null, null, null, '{}'),
(1167, 'bourbon-and-beyond', 'fri', 'Maoli', '100proof', 345, 390, null, null, null, '{}'),
(1168, 'bourbon-and-beyond', 'fri', 'The Flaming Lips', '100proof', 450, 510, null, 'Psychedelic Rock', null, '{}'),
(1169, 'bourbon-and-beyond', 'fri', 'Palmyra', 'revival', 70, 100, null, null, null, '{}'),
(1170, 'bourbon-and-beyond', 'fri', 'Jason Scott & The High Heat', 'revival', 140, 175, null, null, null, '{}'),
(1171, 'bourbon-and-beyond', 'fri', 'Amigo The Devil', 'revival', 220, 255, null, null, null, '{}'),
(1172, 'bourbon-and-beyond', 'fri', 'Jet', 'revival', 300, 340, null, 'Rock', null, '{}'),
(1173, 'bourbon-and-beyond', 'fri', 'Violent Femmes', 'revival', 395, 445, null, 'Alt Rock', null, '{}'),
(1174, 'bourbon-and-beyond', 'fri', 'Fireside Collective', 'bluegrass', 140, 170, null, null, null, '{}'),
(1175, 'bourbon-and-beyond', 'fri', 'Rainbow Girls', 'bluegrass', 220, 250, null, null, null, '{}'),
(1176, 'bourbon-and-beyond', 'fri', 'Shelby Means', 'bluegrass', 275, 305, null, null, null, '{}'),
(1177, 'bourbon-and-beyond', 'fri', 'Kitchen Dwellers', 'bluegrass', 330, 360, null, null, null, '{}'),
(1178, 'bourbon-and-beyond', 'fri', 'Yachtley Crew', 'bluegrass', 400, 445, null, null, null, '{}'),
(1179, 'bourbon-and-beyond', 'sat', 'Bryan Martin', 'oak', 65, 100, null, null, null, '{}'),
(1180, 'bourbon-and-beyond', 'sat', 'Buffalo Traffic Jam', 'oak', 145, 180, null, null, null, '{}'),
(1181, 'bourbon-and-beyond', 'sat', 'Durand Jones & The Indications', 'oak', 225, 270, null, 'Soul', null, '{}'),
(1182, 'bourbon-and-beyond', 'sat', 'Charley Crockett', 'oak', 330, 380, null, 'Country', null, '{}'),
(1183, 'bourbon-and-beyond', 'sat', 'Jason Isbell and the 400 Unit', 'oak', 450, 510, null, 'Americana', null, '{}'),
(1184, 'bourbon-and-beyond', 'sat', 'Chris Stapleton', 'oak', 590, 680, null, 'Country', null, '{}'),
(1185, 'bourbon-and-beyond', 'sat', 'Atlus', 'barrel', 30, 60, null, null, null, '{}'),
(1186, 'bourbon-and-beyond', 'sat', 'Avery Anna', 'barrel', 105, 140, null, null, null, '{}'),
(1187, 'bourbon-and-beyond', 'sat', 'Maddox Batson', 'barrel', 185, 220, null, null, null, '{}'),
(1188, 'bourbon-and-beyond', 'sat', 'Cameron Whitcomb', 'barrel', 275, 325, null, 'Country', null, '{}'),
(1189, 'bourbon-and-beyond', 'sat', 'Jessie Murph', 'barrel', 385, 445, null, 'Pop / Country', null, '{}'),
(1190, 'bourbon-and-beyond', 'sat', 'The Red Clay Strays', 'barrel', 515, 585, null, 'Southern Rock', null, '{}'),
(1191, 'bourbon-and-beyond', 'sat', 'Levi Turner', '100proof', 110, 140, null, null, null, '{}'),
(1192, 'bourbon-and-beyond', 'sat', 'The Creekers', '100proof', 180, 215, null, null, null, '{}'),
(1193, 'bourbon-and-beyond', 'sat', 'Kaitlin Butts', '100proof', 255, 290, null, null, null, '{}'),
(1194, 'bourbon-and-beyond', 'sat', 'Matt Hansen', '100proof', 335, 375, null, null, null, '{}'),
(1195, 'bourbon-and-beyond', 'sat', 'Stella Lefty', '100proof', 435, 475, null, null, null, '{}'),
(1196, 'bourbon-and-beyond', 'sat', 'Noah Cyrus', '100proof', 535, 585, null, 'Country / Pop', null, '{}'),
(1197, 'bourbon-and-beyond', 'sat', 'Rattlesnake Milk', 'revival', 145, 175, null, null, null, '{}'),
(1198, 'bourbon-and-beyond', 'sat', 'Haircut 100', 'revival', 220, 250, null, null, null, '{}'),
(1199, 'bourbon-and-beyond', 'sat', 'Cracker', 'revival', 295, 330, null, null, null, '{}'),
(1200, 'bourbon-and-beyond', 'sat', 'Adam Ant', 'revival', 380, 430, null, 'New Wave', null, '{}'),
(1201, 'bourbon-and-beyond', 'sat', 'Squeeze', 'revival', 480, 530, null, 'New Wave / Rock', null, '{}'),
(1202, 'bourbon-and-beyond', 'sat', 'Still Unknown', 'bluegrass', 215, 245, null, null, null, '{}'),
(1203, 'bourbon-and-beyond', 'sat', 'The Fretliners', 'bluegrass', 270, 300, null, null, null, '{}'),
(1204, 'bourbon-and-beyond', 'sat', 'Meels', 'bluegrass', 325, 355, null, null, null, '{}'),
(1205, 'bourbon-and-beyond', 'sat', 'The Infamous Stringdusters', 'bluegrass', 380, 410, null, 'Bluegrass', null, '{}'),
(1206, 'bourbon-and-beyond', 'sat', 'Yachtley Crew', 'bluegrass', 450, 495, null, null, null, '{}'),
(1207, 'bourbon-and-beyond', 'sun', 'Uncle Lucius', 'oak', 50, 80, null, null, null, '{}'),
(1208, 'bourbon-and-beyond', 'sun', 'Sons of Legion', 'oak', 120, 160, null, null, null, '{}'),
(1209, 'bourbon-and-beyond', 'sun', 'Amos Lee', 'oak', 210, 250, null, 'Singer-Songwriter', null, '{}'),
(1210, 'bourbon-and-beyond', 'sun', 'Portugal. The Man', 'oak', 300, 340, null, 'Alt Rock', null, '{}'),
(1211, 'bourbon-and-beyond', 'sun', 'Counting Crows', 'oak', 395, 445, null, 'Rock', null, '{}'),
(1212, 'bourbon-and-beyond', 'sun', 'Dave Matthews Band', 'oak', 515, 625, null, 'Rock', null, '{}'),
(1213, 'bourbon-and-beyond', 'sun', 'Hunter Hawkins', 'barrel', 15, 45, null, null, null, '{}'),
(1214, 'bourbon-and-beyond', 'sun', 'Ryman', 'barrel', 85, 115, null, null, null, '{}'),
(1215, 'bourbon-and-beyond', 'sun', 'Fitz and the Tantrums', 'barrel', 165, 205, null, 'Indie Pop', null, '{}'),
(1216, 'bourbon-and-beyond', 'sun', 'Max McNown', 'barrel', 255, 295, null, null, null, '{}'),
(1217, 'bourbon-and-beyond', 'sun', 'Jesse Welles', 'barrel', 345, 390, null, null, null, '{}'),
(1218, 'bourbon-and-beyond', 'sun', 'Hootie & the Blowfish', 'barrel', 450, 510, null, 'Rock', null, '{}'),
(1219, 'bourbon-and-beyond', 'sun', 'The Verve Pipe', '100proof', 20, 50, null, 'Alt Rock', null, '{}'),
(1220, 'bourbon-and-beyond', 'sun', 'Tonic', '100proof', 90, 120, null, 'Rock', null, '{}'),
(1221, 'bourbon-and-beyond', 'sun', 'Vertical Horizon', '100proof', 170, 205, null, 'Alt Rock', null, '{}'),
(1222, 'bourbon-and-beyond', 'sun', 'Our Lady Peace', '100proof', 250, 290, null, 'Alt Rock', null, '{}'),
(1223, 'bourbon-and-beyond', 'sun', 'Better Than Ezra', '100proof', 350, 395, null, 'Alt Rock', null, '{}'),
(1224, 'bourbon-and-beyond', 'sun', 'Clover County', 'revival', 55, 85, null, null, null, '{}'),
(1225, 'bourbon-and-beyond', 'sun', 'Paula Cole', 'revival', 125, 165, null, 'Singer-Songwriter', null, '{}'),
(1226, 'bourbon-and-beyond', 'sun', 'World Famous Pets', 'revival', 210, 240, null, null, null, '{}'),
(1227, 'bourbon-and-beyond', 'sun', 'Joan Osborne', 'revival', 295, 345, null, 'Rock / Soul', null, '{}'),
(1228, 'bourbon-and-beyond', 'sun', 'Lisa Loeb', 'revival', 400, 450, null, 'Singer-Songwriter', null, '{}'),
(1229, 'bourbon-and-beyond', 'sun', 'Vickie Vaughn Band', 'bluegrass', 215, 245, null, null, null, '{}'),
(1230, 'bourbon-and-beyond', 'sun', 'Caleb & Reeb', 'bluegrass', 275, 305, null, null, null, '{}'),
(1231, 'bourbon-and-beyond', 'sun', 'The Steel Wheels', 'bluegrass', 335, 365, null, 'Bluegrass', null, '{}'),
(1232, 'bourbon-and-beyond', 'sun', 'Daniel Donato''s Cosmic Country', 'bluegrass', 395, 435, null, 'Country', null, '{}'),
(1233, 'bourbon-and-beyond', 'sun', 'Yachtley Crew', 'bluegrass', 470, 515, null, null, null, '{}')
on conflict (id) do nothing;
