-- Aftershock 2026 (Discovery Park, Sacramento, Oct 1-4) -- real per-artist
-- set times for all 5 official stages (Aftershock, Shockwave, The Point,
-- Faultline, Epicenter) across all 4 real days, transcribed from the
-- festival's own official schedule release as republished verbatim by
-- metalinjection.net (140+ artists, 143 total sets). End times are
-- inferred as "next set's start minus a 5-min changeover" on the same
-- stage/day (standard back-to-back festival scheduling, not a guess about
-- which artist plays when); each stage's final set of the day gets a
-- fixed default length (90 min for the four main stages, 60 for the
-- smaller Epicenter stage) since there's no following set to infer from.
-- Note: the official 2026 lineup poster (musicfestivalwizard.com mirror)
-- lists "Ladrones" on Thursday's Faultline Stage instead of/alongside
-- Primer 55, but the official schedule release only confirms Primer 55
-- with a time. Trusting the schedule (the more current, operational
-- source) over the poster here, per the same rule as elsewhere.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(1304, 'aftershock', 'thu', 'Free Throw', 'aftershock', 25, 75, null, null, null, '{}'),
(1305, 'aftershock', 'thu', 'Lit', 'aftershock', 80, 145, null, null, null, '{}'),
(1306, 'aftershock', 'thu', 'We The Kings', 'aftershock', 150, 220, null, null, null, '{}'),
(1307, 'aftershock', 'thu', 'Mayday Parade', 'aftershock', 225, 305, null, 'Pop Punk', null, '{}'),
(1308, 'aftershock', 'thu', 'Hot Mulligan', 'aftershock', 310, 405, null, 'Emo / Pop Punk', null, '{}'),
(1309, 'aftershock', 'thu', 'Sublime', 'aftershock', 410, 530, null, 'Ska / Reggae Rock', null, '{}'),
(1310, 'aftershock', 'thu', 'My Chemical Romance', 'aftershock', 535, 625, null, 'Rock', null, '{}'),
(1311, 'aftershock', 'thu', 'Leap', 'shockwave', 0, 45, null, null, null, '{}'),
(1312, 'aftershock', 'thu', 'L.S. Dunes', 'shockwave', 50, 110, null, null, null, '{}'),
(1313, 'aftershock', 'thu', 'Hawthorne Heights', 'shockwave', 115, 180, null, null, null, '{}'),
(1314, 'aftershock', 'thu', 'The Starting Line', 'shockwave', 185, 260, null, null, null, '{}'),
(1315, 'aftershock', 'thu', 'New Found Glory', 'shockwave', 265, 355, null, 'Pop Punk', null, '{}'),
(1316, 'aftershock', 'thu', 'The Used', 'shockwave', 360, 465, null, 'Alt Rock', null, '{}'),
(1317, 'aftershock', 'thu', 'The Offspring', 'shockwave', 470, 560, null, 'Punk Rock', null, '{}'),
(1318, 'aftershock', 'thu', 'The Violent Hour', 'thepoint', 35, 90, null, null, null, '{}'),
(1319, 'aftershock', 'thu', 'Red', 'thepoint', 95, 155, null, null, null, '{}'),
(1320, 'aftershock', 'thu', 'Finger Eleven', 'thepoint', 160, 220, null, null, null, '{}'),
(1321, 'aftershock', 'thu', 'Apocalyptica', 'thepoint', 225, 290, null, null, null, '{}'),
(1322, 'aftershock', 'thu', 'Theory Of A Deadman', 'thepoint', 295, 365, null, null, null, '{}'),
(1323, 'aftershock', 'thu', 'Nothing More', 'thepoint', 370, 480, null, null, null, '{}'),
(1324, 'aftershock', 'thu', 'The Pretty Reckless', 'thepoint', 485, 575, null, 'Rock', null, '{}'),
(1325, 'aftershock', 'thu', 'Primer 55', 'faultline', 5, 60, null, null, null, '{}'),
(1326, 'aftershock', 'thu', 'Brujeria', 'faultline', 65, 125, null, null, null, '{}'),
(1327, 'aftershock', 'thu', 'Unloco', 'faultline', 130, 190, null, null, null, '{}'),
(1328, 'aftershock', 'thu', 'Ill Nino', 'faultline', 195, 260, null, null, null, '{}'),
(1329, 'aftershock', 'thu', 'The Union Underground', 'faultline', 265, 335, null, null, null, '{}'),
(1330, 'aftershock', 'thu', 'Coal Chamber', 'faultline', 340, 430, null, null, null, '{}'),
(1331, 'aftershock', 'thu', 'Sevendust', 'faultline', 435, 525, null, 'Alt Metal', null, '{}'),
(1332, 'aftershock', 'thu', 'Killswitch Engage', 'faultline', 530, 620, null, 'Metalcore', null, '{}'),
(1333, 'aftershock', 'thu', 'Wind Walkers', 'epicenter', 80, 145, null, null, null, '{}'),
(1334, 'aftershock', 'thu', 'The Word Alive', 'epicenter', 150, 220, null, null, null, '{}'),
(1335, 'aftershock', 'thu', 'Caskets', 'epicenter', 225, 305, null, null, null, '{}'),
(1336, 'aftershock', 'thu', 'Holding Absence', 'epicenter', 310, 405, null, null, null, '{}'),
(1337, 'aftershock', 'thu', 'From Ashes To New', 'epicenter', 410, 575, null, null, null, '{}'),
(1338, 'aftershock', 'thu', 'Starset', 'epicenter', 580, 640, null, 'Alt Metal', null, '{}'),
(1339, 'aftershock', 'fri', 'Silly Goose', 'aftershock', 0, 45, null, null, null, '{}'),
(1340, 'aftershock', 'fri', 'Drowning Pool', 'aftershock', 50, 105, null, null, null, '{}'),
(1341, 'aftershock', 'fri', 'P.O.D.', 'aftershock', 110, 190, null, null, null, '{}'),
(1342, 'aftershock', 'fri', 'Insane Clown Posse', 'aftershock', 195, 280, null, null, null, '{}'),
(1343, 'aftershock', 'fri', 'Cypress Hill', 'aftershock', 285, 380, null, 'Hip-Hop', null, '{}'),
(1344, 'aftershock', 'fri', 'Public Enemy', 'aftershock', 385, 480, null, 'Hip-Hop', null, '{}'),
(1345, 'aftershock', 'fri', 'Wu-Tang Clan', 'aftershock', 485, 610, null, 'Hip-Hop', null, '{}'),
(1346, 'aftershock', 'fri', 'Limp Bizkit', 'aftershock', 615, 705, null, 'Nu Metal', null, '{}'),
(1347, 'aftershock', 'fri', 'Haarper', 'shockwave', 25, 75, null, null, null, '{}'),
(1348, 'aftershock', 'fri', 'Haywire', 'shockwave', 80, 150, null, null, null, '{}'),
(1349, 'aftershock', 'fri', 'Drain', 'shockwave', 155, 235, null, null, null, '{}'),
(1350, 'aftershock', 'fri', 'Kublai Khan TX', 'shockwave', 240, 330, null, null, null, '{}'),
(1351, 'aftershock', 'fri', 'Three 6 Mafia', 'shockwave', 335, 430, null, null, null, '{}'),
(1352, 'aftershock', 'fri', 'Slaughter To Prevail', 'shockwave', 435, 545, null, null, null, '{}'),
(1353, 'aftershock', 'fri', '$uicideboy$', 'shockwave', 550, 640, null, 'Hip-Hop / Trap Metal', null, '{}'),
(1354, 'aftershock', 'fri', 'Eyes Set To Kill', 'thepoint', 75, 130, null, null, null, '{}'),
(1355, 'aftershock', 'fri', 'Alesana', 'thepoint', 135, 190, null, null, null, '{}'),
(1356, 'aftershock', 'fri', 'Finch', 'thepoint', 195, 255, null, null, null, '{}'),
(1357, 'aftershock', 'fri', 'Atreyu', 'thepoint', 260, 325, null, null, null, '{}'),
(1358, 'aftershock', 'fri', 'Senses Fail', 'thepoint', 330, 395, null, null, null, '{}'),
(1359, 'aftershock', 'fri', 'Alexisonfire', 'thepoint', 400, 465, null, 'Post-Hardcore', null, '{}'),
(1360, 'aftershock', 'fri', 'Underoath', 'thepoint', 470, 555, null, 'Metalcore', null, '{}'),
(1361, 'aftershock', 'fri', 'Coheed And Cambria', 'thepoint', 560, 650, null, 'Prog Rock', null, '{}'),
(1362, 'aftershock', 'fri', 'Vianova', 'faultline', 105, 160, null, null, null, '{}'),
(1363, 'aftershock', 'fri', 'Psychostick', 'faultline', 165, 225, null, null, null, '{}'),
(1364, 'aftershock', 'fri', 'Nekrogoblikon', 'faultline', 230, 295, null, null, null, '{}'),
(1365, 'aftershock', 'fri', 'Blue Medusa feat. Alissa White-Gluz', 'faultline', 300, 360, null, null, null, '{}'),
(1366, 'aftershock', 'fri', 'Cradle Of Filth', 'faultline', 365, 505, null, 'Symphonic Black Metal', null, '{}'),
(1367, 'aftershock', 'fri', 'Chad Gray', 'faultline', 510, 610, null, null, null, '{}'),
(1368, 'aftershock', 'fri', 'Dethklok', 'faultline', 615, 705, null, 'Death Metal', null, '{}'),
(1369, 'aftershock', 'fri', 'Rivers Of Nihil', 'epicenter', 50, 105, null, null, null, '{}'),
(1370, 'aftershock', 'fri', 'Peelingflesh', 'epicenter', 110, 190, null, null, null, '{}'),
(1371, 'aftershock', 'fri', 'Bodysnatcher', 'epicenter', 195, 280, null, null, null, '{}'),
(1372, 'aftershock', 'fri', 'Spite', 'epicenter', 285, 380, null, null, null, '{}'),
(1373, 'aftershock', 'fri', 'The Black Dahlia Murder', 'epicenter', 385, 485, null, 'Melodic Death Metal', null, '{}'),
(1374, 'aftershock', 'fri', 'Paleface Swiss', 'epicenter', 490, 550, null, null, null, '{}'),
(1375, 'aftershock', 'sat', 'Fear, And Loathing In Las Vegas', 'aftershock', 0, 55, null, null, null, '{}'),
(1376, 'aftershock', 'sat', 'ivri', 'aftershock', 60, 115, null, null, null, '{}'),
(1377, 'aftershock', 'sat', 'Blessthefall', 'aftershock', 120, 190, null, null, null, '{}'),
(1378, 'aftershock', 'sat', 'Set It Off', 'aftershock', 195, 270, null, null, null, '{}'),
(1379, 'aftershock', 'sat', 'Chiodos', 'aftershock', 275, 360, null, null, null, '{}'),
(1380, 'aftershock', 'sat', 'Sleeping With Sirens', 'aftershock', 365, 465, null, 'Post-Hardcore', null, '{}'),
(1381, 'aftershock', 'sat', 'Babymetal', 'aftershock', 470, 590, null, 'Metal / J-Pop', null, '{}'),
(1382, 'aftershock', 'sat', 'Pierce The Veil', 'aftershock', 595, 685, null, 'Post-Hardcore', null, '{}'),
(1383, 'aftershock', 'sat', 'Austin Carlile', 'shockwave', 30, 85, null, null, null, '{}'),
(1384, 'aftershock', 'sat', 'Escape The Fate', 'shockwave', 90, 150, null, null, null, '{}'),
(1385, 'aftershock', 'sat', 'The Devil Wears Prada', 'shockwave', 155, 230, null, null, null, '{}'),
(1386, 'aftershock', 'sat', 'The Wonder Years', 'shockwave', 235, 315, null, 'Pop Punk', null, '{}'),
(1387, 'aftershock', 'sat', 'Wage War', 'shockwave', 320, 410, null, null, null, '{}'),
(1388, 'aftershock', 'sat', 'The Story So Far', 'shockwave', 415, 520, null, 'Pop Punk', null, '{}'),
(1389, 'aftershock', 'sat', 'A Day To Remember', 'shockwave', 525, 615, null, 'Pop Punk / Metalcore', null, '{}'),
(1390, 'aftershock', 'sat', 'TBD - Twitch Winner', 'thepoint', 60, 115, null, null, null, '{}'),
(1391, 'aftershock', 'sat', 'Doobie', 'thepoint', 120, 175, null, null, null, '{}'),
(1392, 'aftershock', 'sat', 'Pentagram', 'thepoint', 180, 250, null, null, null, '{}'),
(1393, 'aftershock', 'sat', 'Melvins', 'thepoint', 255, 325, null, 'Sludge Metal', null, '{}'),
(1394, 'aftershock', 'sat', 'Kylesa', 'thepoint', 330, 405, null, null, null, '{}'),
(1395, 'aftershock', 'sat', 'Corrosion Of Conformity', 'thepoint', 410, 490, null, 'Sludge Metal', null, '{}'),
(1396, 'aftershock', 'sat', 'Down', 'thepoint', 495, 605, null, 'Sludge Metal', null, '{}'),
(1397, 'aftershock', 'sat', 'Black Label Society', 'thepoint', 610, 700, null, 'Heavy Metal', null, '{}'),
(1398, 'aftershock', 'sat', 'The Fall Of Troy', 'faultline', 0, 45, null, null, null, '{}'),
(1399, 'aftershock', 'sat', 'Emery', 'faultline', 50, 95, null, null, null, '{}'),
(1400, 'aftershock', 'sat', 'Horse The Band', 'faultline', 100, 150, null, null, null, '{}'),
(1401, 'aftershock', 'sat', 'Armor For Sleep', 'faultline', 155, 205, null, null, null, '{}'),
(1402, 'aftershock', 'sat', 'Saosin', 'faultline', 210, 305, null, null, null, '{}'),
(1403, 'aftershock', 'sat', 'Thursday', 'faultline', 310, 370, null, 'Post-Hardcore', null, '{}'),
(1404, 'aftershock', 'sat', 'La Dispute', 'faultline', 375, 455, null, 'Post-Hardcore', null, '{}'),
(1405, 'aftershock', 'sat', 'Circa Survive', 'faultline', 460, 550, null, 'Prog Rock', null, '{}'),
(1406, 'aftershock', 'sat', 'Gideon', 'epicenter', 40, 105, null, null, null, '{}'),
(1407, 'aftershock', 'sat', 'Stick To Your Guns', 'epicenter', 110, 185, null, null, null, '{}'),
(1408, 'aftershock', 'sat', 'The Acacia Strain', 'epicenter', 190, 265, null, null, null, '{}'),
(1409, 'aftershock', 'sat', 'After The Burial', 'epicenter', 270, 355, null, null, null, '{}'),
(1410, 'aftershock', 'sat', 'Counterparts', 'epicenter', 360, 460, null, null, null, '{}'),
(1411, 'aftershock', 'sat', 'The Ghost Inside', 'epicenter', 465, 525, null, null, null, '{}'),
(1412, 'aftershock', 'sun', 'CKY', 'aftershock', 25, 75, null, null, null, '{}'),
(1413, 'aftershock', 'sun', 'Helmet', 'aftershock', 80, 145, null, null, null, '{}'),
(1414, 'aftershock', 'sun', 'Buckethead', 'aftershock', 150, 225, null, null, null, '{}'),
(1415, 'aftershock', 'sun', 'Zakk Sabbath', 'aftershock', 230, 305, null, null, null, '{}'),
(1416, 'aftershock', 'sun', 'AFI', 'aftershock', 310, 400, null, 'Punk Rock', null, '{}'),
(1417, 'aftershock', 'sun', 'Danny Elfman', 'aftershock', 405, 530, null, 'Alternative / Film Score', null, '{}'),
(1418, 'aftershock', 'sun', 'Tool', 'aftershock', 535, 625, null, 'Prog Metal', null, '{}'),
(1419, 'aftershock', 'sun', 'Toadies', 'shockwave', 0, 45, null, null, null, '{}'),
(1420, 'aftershock', 'sun', 'Oleander', 'shockwave', 50, 110, null, null, null, '{}'),
(1421, 'aftershock', 'sun', 'Filter', 'shockwave', 115, 190, null, 'Industrial Rock', null, '{}'),
(1422, 'aftershock', 'sun', 'Wolfmother', 'shockwave', 195, 265, null, 'Rock', null, '{}'),
(1423, 'aftershock', 'sun', 'Highly Suspect', 'shockwave', 270, 350, null, 'Alt Rock', null, '{}'),
(1424, 'aftershock', 'sun', 'Stone Temple Pilots', 'shockwave', 355, 465, null, 'Alt Rock', null, '{}'),
(1425, 'aftershock', 'sun', 'Queens of the Stone Age', 'shockwave', 470, 560, null, 'Rock', null, '{}'),
(1426, 'aftershock', 'sun', 'Codefendants', 'thepoint', 50, 110, null, null, null, '{}'),
(1427, 'aftershock', 'sun', 'Cro-Mags', 'thepoint', 115, 190, null, null, null, '{}'),
(1428, 'aftershock', 'sun', 'Municipal Waste', 'thepoint', 195, 260, null, null, null, '{}'),
(1429, 'aftershock', 'sun', 'Soulfly', 'thepoint', 265, 320, null, null, null, '{}'),
(1430, 'aftershock', 'sun', 'Cavalera', 'thepoint', 325, 395, null, null, null, '{}'),
(1431, 'aftershock', 'sun', 'Suicidal Tendencies', 'thepoint', 400, 480, null, 'Thrash Metal', null, '{}'),
(1432, 'aftershock', 'sun', 'Body Count', 'thepoint', 485, 575, null, 'Metal / Hip-Hop', null, '{}'),
(1433, 'aftershock', 'sun', 'I Set My Friends On Fire', 'faultline', 25, 75, null, null, null, '{}'),
(1434, 'aftershock', 'sun', 'Emarosa', 'faultline', 80, 130, null, null, null, '{}'),
(1435, 'aftershock', 'sun', 'Drop Dead, Gorgeous', 'faultline', 135, 185, null, null, null, '{}'),
(1436, 'aftershock', 'sun', 'I See Stars', 'faultline', 190, 245, null, null, null, '{}'),
(1437, 'aftershock', 'sun', 'Hail The Sun', 'faultline', 250, 355, null, null, null, '{}'),
(1438, 'aftershock', 'sun', 'From First To Last', 'faultline', 360, 440, null, null, null, '{}'),
(1439, 'aftershock', 'sun', 'The Home Team', 'faultline', 445, 515, null, null, null, '{}'),
(1440, 'aftershock', 'sun', 'Dance Gavin Dance', 'faultline', 520, 610, null, 'Post-Hardcore', null, '{}'),
(1441, 'aftershock', 'sun', 'Cenobia', 'epicenter', 80, 150, null, null, null, '{}'),
(1442, 'aftershock', 'sun', 'The Pretty Wild', 'epicenter', 155, 225, null, null, null, '{}'),
(1443, 'aftershock', 'sun', 'Holywatr', 'epicenter', 230, 310, null, null, null, '{}'),
(1444, 'aftershock', 'sun', 'Jutes', 'epicenter', 315, 395, null, null, null, '{}'),
(1445, 'aftershock', 'sun', 'President', 'epicenter', 400, 575, null, null, null, '{}'),
(1446, 'aftershock', 'sun', 'Sleep Theory', 'epicenter', 580, 640, null, null, null, '{}')
on conflict (id) do nothing;
