-- Lost Lands doesn't publish per-artist stage/set times this far out (only
-- a day-level lineup) -- confirmed against the official site, EDM press,
-- and two independent fan-aggregator sites (Festival Dust, FrontStage
-- Festivals), all of which point to the festival's own app for exact
-- times "closer to the event." 040_lost_lands_remove_bad_sets.sql already
-- removed the earlier fabricated/wrong festival_sets rows for this reason,
-- which correctly avoided lying about times -- but left the festival with
-- no way to actually build a schedule at all.
--
-- The real fix: let a set exist with just an artist + day, no time/stage,
-- so someone can mark which artists they want to see today and have it
-- upgrade to a real timed schedule automatically once the festival
-- publishes one (same festival_id/artist/day rows just get their
-- stage_id/start_min/end_min filled in later -- no new schema needed).
alter table festival_sets alter column stage_id drop not null;
alter table festival_sets alter column start_min drop not null;
alter table festival_sets alter column end_min drop not null;

-- Real Lost Lands 2026 lineup, transcribed directly from the official
-- poster (public/festival-lineups/lost-lands.jpg) -- all 201 acts across
-- Wed-Sun. No stage/time/genre/match data invented; those columns are
-- NULL until Lost Lands actually publishes them.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(1500, 'lost-lands', 'wed', 'Barely Alive', null, null, null, null, null, null, '{}'),
(1501, 'lost-lands', 'wed', 'Calcium B2B Mad Dubz', null, null, null, null, null, null, '{}'),
(1502, 'lost-lands', 'wed', 'Caspa', null, null, null, null, null, null, '{}'),
(1503, 'lost-lands', 'wed', 'Chassi', null, null, null, null, null, null, '{}'),
(1504, 'lost-lands', 'wed', 'Distinct Motive', null, null, null, null, null, null, '{}'),
(1505, 'lost-lands', 'wed', 'Emorfik B2B Usaybflow', null, null, null, null, null, null, '{}'),
(1506, 'lost-lands', 'wed', 'Gardella', null, null, null, null, null, null, '{}'),
(1507, 'lost-lands', 'wed', 'Hairitage', null, null, null, null, null, null, '{}'),
(1508, 'lost-lands', 'wed', 'Hershe', null, null, null, null, null, null, '{}'),
(1509, 'lost-lands', 'wed', 'Hydraulix', null, null, null, null, null, null, '{}'),
(1510, 'lost-lands', 'wed', 'Izzy Vadim', null, null, null, null, null, null, '{}'),
(1511, 'lost-lands', 'wed', 'Jaenga', null, null, null, null, null, null, '{}'),
(1512, 'lost-lands', 'wed', 'Mile32', null, null, null, null, null, null, '{}'),
(1513, 'lost-lands', 'wed', 'Mport', null, null, null, null, null, null, '{}'),
(1514, 'lost-lands', 'wed', 'Muerte', null, null, null, null, null, null, '{}'),
(1515, 'lost-lands', 'wed', 'Nikita, The Wicked', null, null, null, null, null, null, '{}'),
(1516, 'lost-lands', 'wed', 'Riot Ten', null, null, null, null, null, null, '{}'),
(1517, 'lost-lands', 'wed', 'Smoakland', null, null, null, null, null, null, '{}'),
(1518, 'lost-lands', 'thu', 'Alienpark', null, null, null, null, null, null, '{}'),
(1519, 'lost-lands', 'thu', 'Deadcrow', null, null, null, null, null, null, '{}'),
(1520, 'lost-lands', 'thu', 'Dirt Monkey', null, null, null, null, null, null, '{}'),
(1521, 'lost-lands', 'thu', 'Funtcase', null, null, null, null, null, null, '{}'),
(1522, 'lost-lands', 'thu', 'Machaki', null, null, null, null, null, null, '{}'),
(1523, 'lost-lands', 'thu', 'Mindset', null, null, null, null, null, null, '{}'),
(1524, 'lost-lands', 'thu', 'Phrva', null, null, null, null, null, null, '{}'),
(1525, 'lost-lands', 'thu', 'Rsun', null, null, null, null, null, null, '{}'),
(1526, 'lost-lands', 'thu', 'Rzrkt', null, null, null, null, null, null, '{}'),
(1527, 'lost-lands', 'thu', 'Super Future', null, null, null, null, null, null, '{}'),
(1528, 'lost-lands', 'thu', 'Zen Selekta', null, null, null, null, null, null, '{}'),
(1529, 'lost-lands', 'fri', '$J', null, null, null, null, null, null, '{}'),
(1530, 'lost-lands', 'fri', 'Austeria', null, null, null, null, null, null, '{}'),
(1531, 'lost-lands', 'fri', 'Badklaat', null, null, null, null, null, null, '{}'),
(1532, 'lost-lands', 'fri', 'Basstripper', null, null, null, null, null, null, '{}'),
(1533, 'lost-lands', 'fri', 'Bear Grillz', null, null, null, null, null, null, '{}'),
(1534, 'lost-lands', 'fri', 'Benda', null, null, null, null, null, null, '{}'),
(1535, 'lost-lands', 'fri', 'Borgore', null, null, null, null, null, null, '{}'),
(1536, 'lost-lands', 'fri', 'Canabliss', null, null, null, null, null, null, '{}'),
(1537, 'lost-lands', 'fri', 'Casey Club', null, null, null, null, null, null, '{}'),
(1538, 'lost-lands', 'fri', 'Crizzly', null, null, null, null, null, null, '{}'),
(1539, 'lost-lands', 'fri', 'Dion Timmer', null, null, null, null, null, null, '{}'),
(1540, 'lost-lands', 'fri', 'Dirtysnatcha', null, null, null, null, null, null, '{}'),
(1541, 'lost-lands', 'fri', 'Doctor P', null, null, null, null, null, null, '{}'),
(1542, 'lost-lands', 'fri', 'Dodge & Fuski', null, null, null, null, null, null, '{}'),
(1543, 'lost-lands', 'fri', 'Dr. Ushuu', null, null, null, null, null, null, '{}'),
(1544, 'lost-lands', 'fri', 'Drinkurwater', null, null, null, null, null, null, '{}'),
(1545, 'lost-lands', 'fri', 'Dubscribe', null, null, null, null, null, null, '{}'),
(1546, 'lost-lands', 'fri', 'Excision (2 Hour Set)', null, null, null, null, null, null, '{}'),
(1547, 'lost-lands', 'fri', 'Future Exit', null, null, null, null, null, null, '{}'),
(1548, 'lost-lands', 'fri', 'Hol!', null, null, null, null, null, null, '{}'),
(1549, 'lost-lands', 'fri', 'Infekt B2B Samplifire', null, null, null, null, null, null, '{}'),
(1550, 'lost-lands', 'fri', 'Ivy Lab', null, null, null, null, null, null, '{}'),
(1551, 'lost-lands', 'fri', 'Izadi', null, null, null, null, null, null, '{}'),
(1552, 'lost-lands', 'fri', 'Jantsen', null, null, null, null, null, null, '{}'),
(1553, 'lost-lands', 'fri', 'Jkyl & Hyde', null, null, null, null, null, null, '{}'),
(1554, 'lost-lands', 'fri', 'Kliptic', null, null, null, null, null, null, '{}'),
(1555, 'lost-lands', 'fri', 'Klo', null, null, null, null, null, null, '{}'),
(1556, 'lost-lands', 'fri', 'Lazrus', null, null, null, null, null, null, '{}'),
(1557, 'lost-lands', 'fri', 'Levity', null, null, null, null, null, null, '{}'),
(1558, 'lost-lands', 'fri', 'Liquid Stranger', null, null, null, null, null, null, '{}'),
(1559, 'lost-lands', 'fri', 'Lumasi', null, null, null, null, null, null, '{}'),
(1560, 'lost-lands', 'fri', 'Neumonic', null, null, null, null, null, null, '{}'),
(1561, 'lost-lands', 'fri', 'Nghtmre', null, null, null, null, null, null, '{}'),
(1562, 'lost-lands', 'fri', 'Nimda', null, null, null, null, null, null, '{}'),
(1563, 'lost-lands', 'fri', 'Oliverse', null, null, null, null, null, null, '{}'),
(1564, 'lost-lands', 'fri', 'Paper Skies', null, null, null, null, null, null, '{}'),
(1565, 'lost-lands', 'fri', 'Pegboard Nerds', null, null, null, null, null, null, '{}'),
(1566, 'lost-lands', 'fri', 'Poni', null, null, null, null, null, null, '{}'),
(1567, 'lost-lands', 'fri', 'Probcause', null, null, null, null, null, null, '{}'),
(1568, 'lost-lands', 'fri', 'Ravenscoon', null, null, null, null, null, null, '{}'),
(1569, 'lost-lands', 'fri', 'Reaper', null, null, null, null, null, null, '{}'),
(1570, 'lost-lands', 'fri', 'Richard Finger', null, null, null, null, null, null, '{}'),
(1571, 'lost-lands', 'fri', 'Riot', null, null, null, null, null, null, '{}'),
(1572, 'lost-lands', 'fri', 'Seth David', null, null, null, null, null, null, '{}'),
(1573, 'lost-lands', 'fri', 'Shlump', null, null, null, null, null, null, '{}'),
(1574, 'lost-lands', 'fri', 'Sigma', null, null, null, null, null, null, '{}'),
(1575, 'lost-lands', 'fri', 'Sippy', null, null, null, null, null, null, '{}'),
(1576, 'lost-lands', 'fri', 'Subsonic', null, null, null, null, null, null, '{}'),
(1577, 'lost-lands', 'fri', 'Sullivan King B2B Ray Volpe', null, null, null, null, null, null, '{}'),
(1578, 'lost-lands', 'fri', 'The Resistance', null, null, null, null, null, null, '{}'),
(1579, 'lost-lands', 'fri', 'Twopercent', null, null, null, null, null, null, '{}'),
(1580, 'lost-lands', 'fri', 'Tynan', null, null, null, null, null, null, '{}'),
(1581, 'lost-lands', 'fri', 'Vampa', null, null, null, null, null, null, '{}'),
(1582, 'lost-lands', 'fri', 'VKTM', null, null, null, null, null, null, '{}'),
(1583, 'lost-lands', 'fri', 'The Widdler', null, null, null, null, null, null, '{}'),
(1584, 'lost-lands', 'fri', 'Wiley', null, null, null, null, null, null, '{}'),
(1585, 'lost-lands', 'fri', 'Wooli (Sunset Set)', null, null, null, null, null, null, '{}'),
(1586, 'lost-lands', 'fri', 'Xotix', null, null, null, null, null, null, '{}'),
(1587, 'lost-lands', 'fri', 'Yookie', null, null, null, null, null, null, '{}'),
(1588, 'lost-lands', 'fri', 'Zero', null, null, null, null, null, null, '{}'),
(1589, 'lost-lands', 'sat', '2dy4', null, null, null, null, null, null, '{}'),
(1590, 'lost-lands', 'sat', 'Aeon:Mode B2B Blossom', null, null, null, null, null, null, '{}'),
(1591, 'lost-lands', 'sat', 'All The Reason', null, null, null, null, null, null, '{}'),
(1592, 'lost-lands', 'sat', 'Au5', null, null, null, null, null, null, '{}'),
(1593, 'lost-lands', 'sat', 'Audiofreq', null, null, null, null, null, null, '{}'),
(1594, 'lost-lands', 'sat', 'Bella Renee', null, null, null, null, null, null, '{}'),
(1595, 'lost-lands', 'sat', 'Big Florida', null, null, null, null, null, null, '{}'),
(1596, 'lost-lands', 'sat', 'Bou', null, null, null, null, null, null, '{}'),
(1597, 'lost-lands', 'sat', 'Brainrack', null, null, null, null, null, null, '{}'),
(1598, 'lost-lands', 'sat', 'Capochino', null, null, null, null, null, null, '{}'),
(1599, 'lost-lands', 'sat', 'Chozen', null, null, null, null, null, null, '{}'),
(1600, 'lost-lands', 'sat', 'Craze B2B Dieselboy', null, null, null, null, null, null, '{}'),
(1601, 'lost-lands', 'sat', 'Crumb Pit', null, null, null, null, null, null, '{}'),
(1602, 'lost-lands', 'sat', 'Cyclops', null, null, null, null, null, null, '{}'),
(1603, 'lost-lands', 'sat', 'Darksiderz B2B Madgrrl', null, null, null, null, null, null, '{}'),
(1604, 'lost-lands', 'sat', 'Delta Heavy', null, null, null, null, null, null, '{}'),
(1605, 'lost-lands', 'sat', 'Dirtyphonics', null, null, null, null, null, null, '{}'),
(1606, 'lost-lands', 'sat', 'Dr. Fresch', null, null, null, null, null, null, '{}'),
(1607, 'lost-lands', 'sat', 'Effin', null, null, null, null, null, null, '{}'),
(1608, 'lost-lands', 'sat', 'Flosstradamus', null, null, null, null, null, null, '{}'),
(1609, 'lost-lands', 'sat', 'Flux Pavilion', null, null, null, null, null, null, '{}'),
(1610, 'lost-lands', 'sat', 'Ganja White Night', null, null, null, null, null, null, '{}'),
(1611, 'lost-lands', 'sat', 'Ghengar', null, null, null, null, null, null, '{}'),
(1612, 'lost-lands', 'sat', 'Gladde Paling', null, null, null, null, null, null, '{}'),
(1613, 'lost-lands', 'sat', 'Green Matter', null, null, null, null, null, null, '{}'),
(1614, 'lost-lands', 'sat', 'Hedex', null, null, null, null, null, null, '{}'),
(1615, 'lost-lands', 'sat', 'Heyz', null, null, null, null, null, null, '{}'),
(1616, 'lost-lands', 'sat', 'Hvdes', null, null, null, null, null, null, '{}'),
(1617, 'lost-lands', 'sat', 'Illenium', null, null, null, null, null, null, '{}'),
(1618, 'lost-lands', 'sat', 'Imanu', null, null, null, null, null, null, '{}'),
(1619, 'lost-lands', 'sat', 'Ivory', null, null, null, null, null, null, '{}'),
(1620, 'lost-lands', 'sat', 'Jessica Audiffred', null, null, null, null, null, null, '{}'),
(1621, 'lost-lands', 'sat', 'Josh Teed', null, null, null, null, null, null, '{}'),
(1622, 'lost-lands', 'sat', 'Kai Wachi', null, null, null, null, null, null, '{}'),
(1623, 'lost-lands', 'sat', 'Layz', null, null, null, null, null, null, '{}'),
(1624, 'lost-lands', 'sat', 'Leotrix', null, null, null, null, null, null, '{}'),
(1625, 'lost-lands', 'sat', 'Lil Texas', null, null, null, null, null, null, '{}'),
(1626, 'lost-lands', 'sat', 'Lowcation', null, null, null, null, null, null, '{}'),
(1627, 'lost-lands', 'sat', 'Mefjus + Daxta MC', null, null, null, null, null, null, '{}'),
(1628, 'lost-lands', 'sat', 'Mozey', null, null, null, null, null, null, '{}'),
(1629, 'lost-lands', 'sat', 'Myrias', null, null, null, null, null, null, '{}'),
(1630, 'lost-lands', 'sat', 'Mythm', null, null, null, null, null, null, '{}'),
(1631, 'lost-lands', 'sat', 'Neotek', null, null, null, null, null, null, '{}'),
(1632, 'lost-lands', 'sat', 'Noetika', null, null, null, null, null, null, '{}'),
(1633, 'lost-lands', 'sat', 'Phaseone', null, null, null, null, null, null, '{}'),
(1634, 'lost-lands', 'sat', 'Prosecute', null, null, null, null, null, null, '{}'),
(1635, 'lost-lands', 'sat', 'Saint Miller', null, null, null, null, null, null, '{}'),
(1636, 'lost-lands', 'sat', 'Seven Lions (Sunset Set)', null, null, null, null, null, null, '{}'),
(1637, 'lost-lands', 'sat', 'Slander', null, null, null, null, null, null, '{}'),
(1638, 'lost-lands', 'sat', 'Space Wizard', null, null, null, null, null, null, '{}'),
(1639, 'lost-lands', 'sat', 'Stoned Level', null, null, null, null, null, null, '{}'),
(1640, 'lost-lands', 'sat', 'Subtronics B2B Level Up', null, null, null, null, null, null, '{}'),
(1641, 'lost-lands', 'sat', 'Tisoki', null, null, null, null, null, null, '{}'),
(1642, 'lost-lands', 'sat', 'Truth', null, null, null, null, null, null, '{}'),
(1643, 'lost-lands', 'sat', 'Tokyo Machine', null, null, null, null, null, null, '{}'),
(1644, 'lost-lands', 'sat', 'Whales', null, null, null, null, null, null, '{}'),
(1645, 'lost-lands', 'sat', 'Whethan', null, null, null, null, null, null, '{}'),
(1646, 'lost-lands', 'sat', 'Wraz', null, null, null, null, null, null, '{}'),
(1647, 'lost-lands', 'sat', 'Zingara', null, null, null, null, null, null, '{}'),
(1648, 'lost-lands', 'sat', 'Zomboy', null, null, null, null, null, null, '{}'),
(1649, 'lost-lands', 'sun', 'Adventure Club (Throwback Set)', null, null, null, null, null, null, '{}'),
(1650, 'lost-lands', 'sun', 'Arlo', null, null, null, null, null, null, '{}'),
(1651, 'lost-lands', 'sun', 'ARMNHMR', null, null, null, null, null, null, '{}'),
(1652, 'lost-lands', 'sun', 'Atliens', null, null, null, null, null, null, '{}'),
(1653, 'lost-lands', 'sun', 'Avello', null, null, null, null, null, null, '{}'),
(1654, 'lost-lands', 'sun', 'Boogie T', null, null, null, null, null, null, '{}'),
(1655, 'lost-lands', 'sun', 'Champagne Drip', null, null, null, null, null, null, '{}'),
(1656, 'lost-lands', 'sun', 'Codd Dubz', null, null, null, null, null, null, '{}'),
(1657, 'lost-lands', 'sun', 'Crankdat B2B Alleycvt', null, null, null, null, null, null, '{}'),
(1658, 'lost-lands', 'sun', 'Crystal Skies', null, null, null, null, null, null, '{}'),
(1659, 'lost-lands', 'sun', 'Distant Matter', null, null, null, null, null, null, '{}'),
(1660, 'lost-lands', 'sun', 'Dream Takers', null, null, null, null, null, null, '{}'),
(1661, 'lost-lands', 'sun', 'Eptic B2B Lyny', null, null, null, null, null, null, '{}'),
(1662, 'lost-lands', 'sun', 'Excision (Detox)', null, null, null, null, null, null, '{}'),
(1663, 'lost-lands', 'sun', 'Excision B2B Space Laces', null, null, null, null, null, null, '{}'),
(1664, 'lost-lands', 'sun', 'Finnuh', null, null, null, null, null, null, '{}'),
(1665, 'lost-lands', 'sun', 'Ghastly', null, null, null, null, null, null, '{}'),
(1666, 'lost-lands', 'sun', 'Grabbitz', null, null, null, null, null, null, '{}'),
(1667, 'lost-lands', 'sun', 'Haliene', null, null, null, null, null, null, '{}'),
(1668, 'lost-lands', 'sun', 'Hostage Situation', null, null, null, null, null, null, '{}'),
(1669, 'lost-lands', 'sun', 'Hurtbox', null, null, null, null, null, null, '{}'),
(1670, 'lost-lands', 'sun', 'Killmatter', null, null, null, null, null, null, '{}'),
(1671, 'lost-lands', 'sun', 'Know Good', null, null, null, null, null, null, '{}'),
(1672, 'lost-lands', 'sun', 'Kompany', null, null, null, null, null, null, '{}'),
(1673, 'lost-lands', 'sun', 'Krewella', null, null, null, null, null, null, '{}'),
(1674, 'lost-lands', 'sun', 'Luci', null, null, null, null, null, null, '{}'),
(1675, 'lost-lands', 'sun', 'Mad Dubz', null, null, null, null, null, null, '{}'),
(1676, 'lost-lands', 'sun', 'Modal Nodes', null, null, null, null, null, null, '{}'),
(1677, 'lost-lands', 'sun', 'OG Nixin', null, null, null, null, null, null, '{}'),
(1678, 'lost-lands', 'sun', 'Onara', null, null, null, null, null, null, '{}'),
(1679, 'lost-lands', 'sun', 'Passport', null, null, null, null, null, null, '{}'),
(1680, 'lost-lands', 'sun', 'Pretty Sweet', null, null, null, null, null, null, '{}'),
(1681, 'lost-lands', 'sun', 'Remk', null, null, null, null, null, null, '{}'),
(1682, 'lost-lands', 'sun', 'Roi*', null, null, null, null, null, null, '{}'),
(1683, 'lost-lands', 'sun', 'Ryns', null, null, null, null, null, null, '{}'),
(1684, 'lost-lands', 'sun', 'Sisto', null, null, null, null, null, null, '{}'),
(1685, 'lost-lands', 'sun', 'Skilah', null, null, null, null, null, null, '{}'),
(1686, 'lost-lands', 'sun', 'Sodown', null, null, null, null, null, null, '{}'),
(1687, 'lost-lands', 'sun', 'Sportmode', null, null, null, null, null, null, '{}'),
(1688, 'lost-lands', 'sun', 'Sqishi', null, null, null, null, null, null, '{}'),
(1689, 'lost-lands', 'sun', 'Stumpi', null, null, null, null, null, null, '{}'),
(1690, 'lost-lands', 'sun', 'Taiki Nulight', null, null, null, null, null, null, '{}'),
(1691, 'lost-lands', 'sun', 'Trivecta', null, null, null, null, null, null, '{}'),
(1692, 'lost-lands', 'sun', 'Usaybflow', null, null, null, null, null, null, '{}'),
(1693, 'lost-lands', 'sun', 'Virtual Riot', null, null, null, null, null, null, '{}'),
(1694, 'lost-lands', 'sun', 'Warlord', null, null, null, null, null, null, '{}'),
(1695, 'lost-lands', 'sun', 'Wax Motif', null, null, null, null, null, null, '{}'),
(1696, 'lost-lands', 'sun', 'William Black', null, null, null, null, null, null, '{}'),
(1697, 'lost-lands', 'sun', 'Wonkywilla', null, null, null, null, null, null, '{}'),
(1698, 'lost-lands', 'sun', 'Yetep', null, null, null, null, null, null, '{}'),
(1699, 'lost-lands', 'sun', 'YVM3', null, null, null, null, null, null, '{}'),
(1700, 'lost-lands', 'sun', 'Zoey808', null, null, null, null, null, null, '{}');
