-- Adds Bass Canyon (Excision's festival, The Gorge Amphitheatre, George,
-- WA), Aug 14-16, 2026 -- already happened as of this writing (~2 weeks
-- ago), added as a real historical record, same pattern as Coachella/
-- Governors Ball/Outside Lands etc. already in FESTIVALS.
--
-- 88-set schedule transcribed from basscanyon.com's own official "Set
-- Times" graphic (via thedailyfrequency.com's Aug 13 2026 recap). That
-- graphic lists only each set's START time (latest-first) -- end_min for
-- every set below is the *next* real, sourced start time on that same
-- stage, so it's exact, not estimated. Only the final (closing) set per
-- stage/day has no following set to derive an end from, so those are left
-- end_min: null rather than guessed. Cross-checked artist-for-artist
-- against the festival's separate "Daily Lineups" poster -- 30/30/28 acts
-- per day, exact match both independent official sources.
--
-- Three real stages: Canyon, Hilltop, Starlight (companion FESTIVAL_STAGES
-- entry in src/App.jsx). genre/match/sounds_like left null, same as every
-- other real-schedule festival added this session.
insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(2300, 'bass-canyon', 'fri', 'Brainrack B2B Wiley', 'canyon', 30, 80, null, null, null, '{}'),
(2301, 'bass-canyon', 'fri', 'Capochino', 'canyon', 80, 125, null, null, null, '{}'),
(2302, 'bass-canyon', 'fri', 'Heyz', 'canyon', 125, 170, null, null, null, '{}'),
(2303, 'bass-canyon', 'fri', 'Calcium', 'canyon', 170, 220, null, null, null, '{}'),
(2304, 'bass-canyon', 'fri', 'Trivecta', 'canyon', 220, 270, null, null, null, '{}'),
(2305, 'bass-canyon', 'fri', 'Dion Timmer', 'canyon', 270, 320, null, null, null, '{}'),
(2306, 'bass-canyon', 'fri', 'Mersiv (Sunset Set)', 'canyon', 320, 370, null, null, null, '{}'),
(2307, 'bass-canyon', 'fri', 'Level Up', 'canyon', 370, 420, null, null, null, '{}'),
(2308, 'bass-canyon', 'fri', 'NGHTMRE', 'canyon', 420, 480, null, null, null, '{}'),
(2309, 'bass-canyon', 'fri', 'Sullivan King', 'canyon', 480, 550, null, null, null, '{}'),
(2310, 'bass-canyon', 'fri', 'Excision', 'canyon', 550, null, null, null, null, '{}'),
(2311, 'bass-canyon', 'fri', 'Vaski', 'hilltop', 0, 60, null, null, null, '{}'),
(2312, 'bass-canyon', 'fri', 'Badklaat', 'hilltop', 60, 120, null, null, null, '{}'),
(2313, 'bass-canyon', 'fri', 'Pegboard Nerds', 'hilltop', 120, 180, null, null, null, '{}'),
(2314, 'bass-canyon', 'fri', 'Funtcase', 'hilltop', 180, 240, null, null, null, '{}'),
(2315, 'bass-canyon', 'fri', 'Bear Grillz', 'hilltop', 240, 300, null, null, null, '{}'),
(2316, 'bass-canyon', 'fri', 'Borgore', 'hilltop', 300, 360, null, null, null, '{}'),
(2317, 'bass-canyon', 'fri', 'Virtual Riot', 'hilltop', 360, 420, null, null, null, '{}'),
(2318, 'bass-canyon', 'fri', 'Barely Alive', 'hilltop', 420, 480, null, null, null, '{}'),
(2319, 'bass-canyon', 'fri', 'Big Gigantic', 'hilltop', 480, 540, null, null, null, '{}'),
(2320, 'bass-canyon', 'fri', 'Dodge & Fuski', 'hilltop', 540, null, null, null, null, '{}'),
(2321, 'bass-canyon', 'fri', 'Hexxa', 'starlight', 30, 90, null, null, null, '{}'),
(2322, 'bass-canyon', 'fri', '$J', 'starlight', 90, 150, null, null, null, '{}'),
(2323, 'bass-canyon', 'fri', 'Versa', 'starlight', 150, 210, null, null, null, '{}'),
(2324, 'bass-canyon', 'fri', 'Usaybflow', 'starlight', 210, 270, null, null, null, '{}'),
(2325, 'bass-canyon', 'fri', 'Emorfik', 'starlight', 270, 330, null, null, null, '{}'),
(2326, 'bass-canyon', 'fri', 'Ivory', 'starlight', 330, 390, null, null, null, '{}'),
(2327, 'bass-canyon', 'fri', 'Hostage Situation', 'starlight', 390, 450, null, null, null, '{}'),
(2328, 'bass-canyon', 'fri', 'Stoog3s', 'starlight', 450, 510, null, null, null, '{}'),
(2329, 'bass-canyon', 'fri', 'The Resistance', 'starlight', 510, null, null, null, null, '{}'),
(2330, 'bass-canyon', 'sat', 'Neotek', 'canyon', 30, 80, null, null, null, '{}'),
(2331, 'bass-canyon', 'sat', 'Tynan', 'canyon', 80, 130, null, null, null, '{}'),
(2332, 'bass-canyon', 'sat', 'Smoakland', 'canyon', 130, 180, null, null, null, '{}'),
(2333, 'bass-canyon', 'sat', 'Jkyl & Hyde', 'canyon', 180, 230, null, null, null, '{}'),
(2334, 'bass-canyon', 'sat', 'Kill Safari', 'canyon', 230, 280, null, null, null, '{}'),
(2335, 'bass-canyon', 'sat', 'William Black', 'canyon', 280, 330, null, null, null, '{}'),
(2336, 'bass-canyon', 'sat', 'Ganja White Night (Sunset Set)', 'canyon', 330, 390, null, null, null, '{}'),
(2337, 'bass-canyon', 'sat', 'Alleycvt', 'canyon', 390, 445, null, null, null, '{}'),
(2338, 'bass-canyon', 'sat', 'Ray Volpe', 'canyon', 445, 500, null, null, null, '{}'),
(2339, 'bass-canyon', 'sat', 'Crankdat B2B Wooli', 'canyon', 500, 560, null, null, null, '{}'),
(2340, 'bass-canyon', 'sat', 'Illenium B2B Dabin', 'canyon', 560, null, null, null, null, '{}'),
(2341, 'bass-canyon', 'sat', 'Paper Skies', 'hilltop', 0, 60, null, null, null, '{}'),
(2342, 'bass-canyon', 'sat', 'Austeria', 'hilltop', 60, 120, null, null, null, '{}'),
(2343, 'bass-canyon', 'sat', 'Phrva', 'hilltop', 120, 180, null, null, null, '{}'),
(2344, 'bass-canyon', 'sat', 'Smith.', 'hilltop', 180, 240, null, null, null, '{}'),
(2345, 'bass-canyon', 'sat', 'Sumthin Sumthin', 'hilltop', 240, 300, null, null, null, '{}'),
(2346, 'bass-canyon', 'sat', 'Dennett', 'hilltop', 300, 360, null, null, null, '{}'),
(2347, 'bass-canyon', 'sat', 'Tripp St.', 'hilltop', 360, 420, null, null, null, '{}'),
(2348, 'bass-canyon', 'sat', 'Super Future', 'hilltop', 420, 480, null, null, null, '{}'),
(2349, 'bass-canyon', 'sat', 'Canabliss', 'hilltop', 480, 555, null, null, null, '{}'),
(2350, 'bass-canyon', 'sat', 'Ravenscoon B2B Jantsen', 'hilltop', 555, null, null, null, null, '{}'),
(2351, 'bass-canyon', 'sat', 'Siren', 'starlight', 30, 90, null, null, null, '{}'),
(2352, 'bass-canyon', 'sat', 'Crumb Pit', 'starlight', 90, 150, null, null, null, '{}'),
(2353, 'bass-canyon', 'sat', 'Justin Hawkes', 'starlight', 150, 210, null, null, null, '{}'),
(2354, 'bass-canyon', 'sat', 'Liquid Smoak', 'starlight', 210, 270, null, null, null, '{}'),
(2355, 'bass-canyon', 'sat', 'Muzz', 'starlight', 270, 330, null, null, null, '{}'),
(2356, 'bass-canyon', 'sat', 'Culture Shock', 'starlight', 330, 390, null, null, null, '{}'),
(2357, 'bass-canyon', 'sat', 'Sigma w/ Armanni Reign', 'starlight', 390, 450, null, null, null, '{}'),
(2358, 'bass-canyon', 'sat', 'Dirtyphonics', 'starlight', 450, 510, null, null, null, '{}'),
(2359, 'bass-canyon', 'sat', 'Kanine', 'starlight', 510, null, null, null, null, '{}'),
(2360, 'bass-canyon', 'sun', 'Flozone', 'canyon', 25, 75, null, null, null, '{}'),
(2361, 'bass-canyon', 'sun', 'Luci', 'canyon', 75, 125, null, null, null, '{}'),
(2362, 'bass-canyon', 'sun', 'Richard Finger', 'canyon', 125, 175, null, null, null, '{}'),
(2363, 'bass-canyon', 'sun', 'Eazybaked', 'canyon', 175, 225, null, null, null, '{}'),
(2364, 'bass-canyon', 'sun', 'Ghengar', 'canyon', 225, 275, null, null, null, '{}'),
(2365, 'bass-canyon', 'sun', 'Atliens', 'canyon', 275, 325, null, null, null, '{}'),
(2366, 'bass-canyon', 'sun', 'Excision (Detox Set)', 'canyon', 325, 375, null, null, null, '{}'),
(2367, 'bass-canyon', 'sun', 'Inzo', 'canyon', 375, 430, null, null, null, '{}'),
(2368, 'bass-canyon', 'sun', 'Voyd', 'canyon', 430, 500, null, null, null, '{}'),
(2369, 'bass-canyon', 'sun', 'Excision B2B Slander', 'canyon', 500, null, null, null, null, '{}'),
(2370, 'bass-canyon', 'sun', 'Machaki', 'hilltop', 0, 65, null, null, null, '{}'),
(2371, 'bass-canyon', 'sun', 'Z3lla', 'hilltop', 65, 125, null, null, null, '{}'),
(2372, 'bass-canyon', 'sun', 'Pretty Sweet', 'hilltop', 125, 180, null, null, null, '{}'),
(2373, 'bass-canyon', 'sun', 'Rossy', 'hilltop', 180, 235, null, null, null, '{}'),
(2374, 'bass-canyon', 'sun', 'Seth David', 'hilltop', 235, 290, null, null, null, '{}'),
(2375, 'bass-canyon', 'sun', 'Nikita, The Wicked', 'hilltop', 290, 345, null, null, null, '{}'),
(2376, 'bass-canyon', 'sun', 'Whipped Cream', 'hilltop', 345, 400, null, null, null, '{}'),
(2377, 'bass-canyon', 'sun', 'Avello', 'hilltop', 400, 455, null, null, null, '{}'),
(2378, 'bass-canyon', 'sun', 'Ghastly', 'hilltop', 455, 510, null, null, null, '{}'),
(2379, 'bass-canyon', 'sun', 'Klo', 'hilltop', 510, null, null, null, null, '{}'),
(2380, 'bass-canyon', 'sun', 'Otsukare', 'starlight', 30, 90, null, null, null, '{}'),
(2381, 'bass-canyon', 'sun', 'Izadi', 'starlight', 90, 150, null, null, null, '{}'),
(2382, 'bass-canyon', 'sun', 'Dream Takers', 'starlight', 150, 210, null, null, null, '{}'),
(2383, 'bass-canyon', 'sun', 'All The Reason', 'starlight', 210, 270, null, null, null, '{}'),
(2384, 'bass-canyon', 'sun', 'Twopercent', 'starlight', 270, 330, null, null, null, '{}'),
(2385, 'bass-canyon', 'sun', 'Hekler', 'starlight', 330, 390, null, null, null, '{}'),
(2386, 'bass-canyon', 'sun', 'Dømina', 'starlight', 390, 450, null, null, null, '{}'),
(2387, 'bass-canyon', 'sun', 'Yosuf', 'starlight', 450, null, null, null, null, '{}');
