-- Movement Detroit 2026 (May 23-25, Hart Plaza, Detroit, MI) --
-- 118 rows across sat/sun/mon, 6 stages (Movement, Waterfront, Stargate,
-- Underground, Pyramid, Detroit).
--
-- Transcribed verbatim from DJ Mag's "Movement Detroit 2026 set times
-- announced" article (djmag.com/news/movement-detroit-2026-set-times-announced),
-- which published Paxahau's complete stage-by-stage timetable for all 3
-- days. Both start AND end times were explicitly published for every
-- single set -- nothing here is inferred/estimated. The official
-- movementfestival.com site itself never publishes a public set-times
-- page (per its own FAQ, exact times are an official-app-only feature),
-- so this article is the primary real source used.
--
-- start_min/end_min are relative to each day's FESTIVAL_DAYS startMin
-- (all 3 days: 2:00 PM / 840 min since midnight -- the earliest
-- confirmed stage start every day).

insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(2400, 'movement-detroit', 'sat', 'Audion (Live)', 'movement', 120, 180, null, null, null, '{}'),
(2401, 'movement-detroit', 'sat', 'Voices From The Lake', 'movement', 180, 270, null, null, null, '{}'),
(2402, 'movement-detroit', 'sat', 'Borderland (Live)', 'movement', 270, 330, null, null, null, '{}'),
(2403, 'movement-detroit', 'sat', 'Collabs3000 (Chris Liebing & Speedy J)', 'movement', 330, 420, null, null, null, '{}'),
(2404, 'movement-detroit', 'sat', '999999999', 'movement', 420, 510, null, null, null, '{}'),
(2405, 'movement-detroit', 'sat', 'Sara Landry', 'movement', 510, 600, null, null, null, '{}'),
(2406, 'movement-detroit', 'sat', 'AK', 'waterfront', 60, 120, null, null, null, '{}'),
(2407, 'movement-detroit', 'sat', 'JMT', 'waterfront', 120, 180, null, null, null, '{}'),
(2408, 'movement-detroit', 'sat', 'DJ Godfather', 'waterfront', 180, 240, null, null, null, '{}'),
(2409, 'movement-detroit', 'sat', 'Miss Bashful (Live)', 'waterfront', 240, 300, null, null, null, '{}'),
(2410, 'movement-detroit', 'sat', 'Zack Fox b2b Jyoty', 'waterfront', 300, 360, null, null, null, '{}'),
(2411, 'movement-detroit', 'sat', 'X-Altera', 'waterfront', 360, 430, null, null, null, '{}'),
(2412, 'movement-detroit', 'sat', 'Dopplereffekt (Live AV)', 'waterfront', 440, 500, null, null, null, '{}'),
(2413, 'movement-detroit', 'sat', 'Peezy', 'waterfront', 510, 530, null, null, null, '{}'),
(2414, 'movement-detroit', 'sat', 'Danny Brown', 'waterfront', 540, 600, null, null, null, '{}'),
(2415, 'movement-detroit', 'sat', 'K''Alexi Shelby', 'stargate', 0, 60, null, null, null, '{}'),
(2416, 'movement-detroit', 'sat', 'Kyle Hall b2b Byron the Aquarius', 'stargate', 60, 150, null, null, null, '{}'),
(2417, 'movement-detroit', 'sat', 'John Collins', 'stargate', 150, 240, null, null, null, '{}'),
(2418, 'movement-detroit', 'sat', 'Dames Brown', 'stargate', 240, 270, null, null, null, '{}'),
(2419, 'movement-detroit', 'sat', 'Stacey ''Hotwaxx'' Hale', 'stargate', 270, 360, null, null, null, '{}'),
(2420, 'movement-detroit', 'sat', 'Stacey Pullen', 'stargate', 360, 450, null, null, null, '{}'),
(2421, 'movement-detroit', 'sat', 'jessica Care moore', 'stargate', 450, 455, null, null, null, '{}'),
(2422, 'movement-detroit', 'sat', 'Carl Craig b2b Cajmere', 'stargate', 455, 540, null, null, null, '{}'),
(2423, 'movement-detroit', 'sat', 'Luke Hess', 'underground', 60, 120, null, null, null, '{}'),
(2424, 'movement-detroit', 'sat', 'Terrence Dixon (Live)', 'underground', 120, 270, null, null, null, '{}'),
(2425, 'movement-detroit', 'sat', 'Mark Flash', 'underground', 270, 360, null, null, null, '{}'),
(2426, 'movement-detroit', 'sat', 'Nastia', 'underground', 360, 450, null, null, null, '{}'),
(2427, 'movement-detroit', 'sat', 'Dax J (Live)', 'underground', 450, 510, null, null, null, '{}'),
(2428, 'movement-detroit', 'sat', 'Ellen Allien b2b DJ Stingray', 'underground', 510, 600, null, null, null, '{}'),
(2429, 'movement-detroit', 'sat', 'Peter Croce b2b Eddie Logix', 'pyramid', 60, 150, null, null, null, '{}'),
(2430, 'movement-detroit', 'sat', 'Colette b2b DJ Heather', 'pyramid', 150, 240, null, null, null, '{}'),
(2431, 'movement-detroit', 'sat', 'Octo Octa', 'pyramid', 240, 330, null, null, null, '{}'),
(2432, 'movement-detroit', 'sat', 'Eats Everything', 'pyramid', 330, 420, null, null, null, '{}'),
(2433, 'movement-detroit', 'sat', 'Claude Vonstroke', 'pyramid', 420, 510, null, null, null, '{}'),
(2434, 'movement-detroit', 'sat', 'Richie Hawtin', 'pyramid', 510, 600, null, null, null, '{}'),
(2435, 'movement-detroit', 'sat', 'Milan Ariel Atkins', 'detroit', 0, 60, null, null, null, '{}'),
(2436, 'movement-detroit', 'sat', 'DJ Roach', 'detroit', 60, 120, null, null, null, '{}'),
(2437, 'movement-detroit', 'sat', 'Dru Ruiz', 'detroit', 120, 180, null, null, null, '{}'),
(2438, 'movement-detroit', 'sat', 'Rebecca Goldberg (Live)', 'detroit', 180, 240, null, null, null, '{}'),
(2439, 'movement-detroit', 'sat', 'Ataxia b2b Mister Joshooa', 'detroit', 240, 300, null, null, null, '{}'),
(2440, 'movement-detroit', 'sat', 'STS (Live)', 'detroit', 300, 360, null, null, null, '{}'),
(2441, 'movement-detroit', 'sat', 'Duck Trash', 'detroit', 360, 420, null, null, null, '{}'),
(2442, 'movement-detroit', 'sat', 'Sheefy McFly', 'detroit', 420, 480, null, null, null, '{}'),
(2443, 'movement-detroit', 'sat', 'Disc Jockey George', 'detroit', 480, 540, null, null, null, '{}'),
(2444, 'movement-detroit', 'sun', 'DJ Sphinx', 'movement', 120, 210, null, null, null, '{}'),
(2445, 'movement-detroit', 'sun', 'Donato Dozzy', 'movement', 210, 330, null, null, null, '{}'),
(2446, 'movement-detroit', 'sun', 'Eli Brown', 'movement', 330, 430, null, null, null, '{}'),
(2447, 'movement-detroit', 'sun', 'E-DANCER (Kevin Saunderson & Dantiez)', 'movement', 440, 500, null, null, null, '{}'),
(2448, 'movement-detroit', 'sun', 'Carl Cox', 'movement', 510, 600, null, null, null, '{}'),
(2449, 'movement-detroit', 'sun', 'Tammy Lakkis', 'waterfront', 60, 120, null, null, null, '{}'),
(2450, 'movement-detroit', 'sun', 'Heidi Lawden', 'waterfront', 120, 210, null, null, null, '{}'),
(2451, 'movement-detroit', 'sun', 'TEED', 'waterfront', 210, 270, null, null, null, '{}'),
(2452, 'movement-detroit', 'sun', 'The Dare', 'waterfront', 285, 345, null, null, null, '{}'),
(2453, 'movement-detroit', 'sun', 'NEIL FRANCES presents CLUB NF', 'waterfront', 360, 420, null, null, null, '{}'),
(2454, 'movement-detroit', 'sun', 'DJ Harvey', 'waterfront', 420, 510, null, null, null, '{}'),
(2455, 'movement-detroit', 'sun', 'Barry Can''t Swim', 'waterfront', 510, 600, null, null, null, '{}'),
(2456, 'movement-detroit', 'sun', 'Beige', 'stargate', 0, 120, null, null, null, '{}'),
(2457, 'movement-detroit', 'sun', 'Morgan', 'stargate', 120, 210, null, null, null, '{}'),
(2458, 'movement-detroit', 'sun', 'Ryan Elliott b2b Ogazón', 'stargate', 210, 300, null, null, null, '{}'),
(2459, 'movement-detroit', 'sun', 'Skream', 'stargate', 300, 390, null, null, null, '{}'),
(2460, 'movement-detroit', 'sun', 'Josh Baker', 'stargate', 390, 480, null, null, null, '{}'),
(2461, 'movement-detroit', 'sun', 'The Martinez Brothers b2b Eddie Fowlkes', 'stargate', 480, 600, null, null, null, '{}'),
(2462, 'movement-detroit', 'sun', 'Trovarsi', 'underground', 60, 150, null, null, null, '{}'),
(2463, 'movement-detroit', 'sun', 'Lindsey Herbert', 'underground', 150, 240, null, null, null, '{}'),
(2464, 'movement-detroit', 'sun', 'DJ Bone', 'underground', 240, 330, null, null, null, '{}'),
(2465, 'movement-detroit', 'sun', 'Oscar Mulero', 'underground', 330, 450, null, null, null, '{}'),
(2466, 'movement-detroit', 'sun', 'Stef Mendesidis (Live)', 'underground', 450, 540, null, null, null, '{}'),
(2467, 'movement-detroit', 'sun', 'Blawan (Live)', 'underground', 540, 600, null, null, null, '{}'),
(2468, 'movement-detroit', 'sun', 'Father Dukes', 'pyramid', 0, 90, null, null, null, '{}'),
(2469, 'movement-detroit', 'sun', 'SYREETA', 'pyramid', 90, 180, null, null, null, '{}'),
(2470, 'movement-detroit', 'sun', 'The Saunderson Brothers', 'pyramid', 180, 270, null, null, null, '{}'),
(2471, 'movement-detroit', 'sun', 'Kevin Saunderson', 'pyramid', 270, 360, null, null, null, '{}'),
(2472, 'movement-detroit', 'sun', 'ANNA', 'pyramid', 360, 480, null, null, null, '{}'),
(2473, 'movement-detroit', 'sun', 'Maceo Plex', 'pyramid', 480, 600, null, null, null, '{}'),
(2474, 'movement-detroit', 'sun', 'DJ STAKXX', 'detroit', 60, 120, null, null, null, '{}'),
(2475, 'movement-detroit', 'sun', 'KESSWA', 'detroit', 120, 180, null, null, null, '{}'),
(2476, 'movement-detroit', 'sun', 'Zoe Talley', 'detroit', 180, 240, null, null, null, '{}'),
(2477, 'movement-detroit', 'sun', 'DJ Killa Squid', 'detroit', 240, 300, null, null, null, '{}'),
(2478, 'movement-detroit', 'sun', 'Lady Witch', 'detroit', 300, 360, null, null, null, '{}'),
(2479, 'movement-detroit', 'sun', 'hypemelo', 'detroit', 360, 420, null, null, null, '{}'),
(2480, 'movement-detroit', 'sun', 'Something Blue', 'detroit', 420, 480, null, null, null, '{}'),
(2481, 'movement-detroit', 'mon', 'Delano Smith', 'movement', 120, 180, null, null, null, '{}'),
(2482, 'movement-detroit', 'mon', 'DJ Holographic', 'movement', 180, 260, null, null, null, '{}'),
(2483, 'movement-detroit', 'mon', 'Green Velvet', 'movement', 260, 370, null, null, null, '{}'),
(2484, 'movement-detroit', 'mon', 'jessica Care moore', 'movement', 380, 385, null, null, null, '{}'),
(2485, 'movement-detroit', 'mon', '69 (Carl Craig)', 'movement', 385, 440, null, null, null, '{}'),
(2486, 'movement-detroit', 'mon', 'Dom Dolla', 'movement', 450, 540, null, null, null, '{}'),
(2487, 'movement-detroit', 'mon', 'BeatLoaf', 'waterfront', 60, 150, null, null, null, '{}'),
(2488, 'movement-detroit', 'mon', 'OPPIDAN', 'waterfront', 150, 240, null, null, null, '{}'),
(2489, 'movement-detroit', 'mon', 'RUDIM3NTAL', 'waterfront', 240, 315, null, null, null, '{}'),
(2490, 'movement-detroit', 'mon', 'Nia Archives (DJ Set)', 'waterfront', 315, 375, null, null, null, '{}'),
(2491, 'movement-detroit', 'mon', 'Special Request', 'waterfront', 375, 465, null, null, null, '{}'),
(2492, 'movement-detroit', 'mon', 'Overmono', 'waterfront', 480, 540, null, null, null, '{}'),
(2493, 'movement-detroit', 'mon', 'Rimarkable', 'stargate', 0, 90, null, null, null, '{}'),
(2494, 'movement-detroit', 'mon', 'Courtesy', 'stargate', 90, 180, null, null, null, '{}'),
(2495, 'movement-detroit', 'mon', 'Tiga', 'stargate', 180, 270, null, null, null, '{}'),
(2496, 'movement-detroit', 'mon', 'DJ Tennis b2b DJ BORING', 'stargate', 270, 360, null, null, null, '{}'),
(2497, 'movement-detroit', 'mon', 'AYYBO', 'stargate', 360, 450, null, null, null, '{}'),
(2498, 'movement-detroit', 'mon', 'Hot Since 82', 'stargate', 450, 540, null, null, null, '{}'),
(2499, 'movement-detroit', 'mon', 'Garrison XR', 'underground', 30, 90, null, null, null, '{}'),
(2500, 'movement-detroit', 'mon', 'Detroit Techno Militia', 'underground', 90, 180, null, null, null, '{}'),
(2501, 'movement-detroit', 'mon', 'Mija', 'underground', 180, 270, null, null, null, '{}'),
(2502, 'movement-detroit', 'mon', 'DJ Heartstring b2b X CLUB.', 'underground', 270, 360, null, null, null, '{}'),
(2503, 'movement-detroit', 'mon', 'Boys Noize b2b MCR-T', 'underground', 360, 450, null, null, null, '{}'),
(2504, 'movement-detroit', 'mon', 'KI/KI', 'underground', 450, 540, null, null, null, '{}'),
(2505, 'movement-detroit', 'mon', 'DJ Taz', 'pyramid', 0, 90, null, null, null, '{}'),
(2506, 'movement-detroit', 'mon', 'Life on Planets', 'pyramid', 90, 180, null, null, null, '{}'),
(2507, 'movement-detroit', 'mon', 'Tinzo & Jojo', 'pyramid', 180, 270, null, null, null, '{}'),
(2508, 'movement-detroit', 'mon', 'The Ritual with Anané & Louie Vega', 'pyramid', 270, 360, null, null, null, '{}'),
(2509, 'movement-detroit', 'mon', 'Mochakk', 'pyramid', 360, 450, null, null, null, '{}'),
(2510, 'movement-detroit', 'mon', 'DJ Minx', 'pyramid', 450, 540, null, null, null, '{}'),
(2511, 'movement-detroit', 'mon', 'Ryan Spencer', 'detroit', 0, 60, null, null, null, '{}'),
(2512, 'movement-detroit', 'mon', 'Meftah', 'detroit', 60, 120, null, null, null, '{}'),
(2513, 'movement-detroit', 'mon', 'Hazmat Live', 'detroit', 120, 180, null, null, null, '{}'),
(2514, 'movement-detroit', 'mon', 'Salar Ansari', 'detroit', 180, 240, null, null, null, '{}'),
(2515, 'movement-detroit', 'mon', 'SILLYGIRLCARMEN', 'detroit', 240, 300, null, null, null, '{}'),
(2516, 'movement-detroit', 'mon', 'Whodat', 'detroit', 300, 360, null, null, null, '{}'),
(2517, 'movement-detroit', 'mon', 'Keith Worthy', 'detroit', 360, 420, null, null, null, '{}');
