-- HARD Summer 2026 (Aug 1-2, Hollywood Park, Inglewood, CA) --
-- 91 rows across sat/sun, 7 stages (HARD, HARDER, Green, Purple, Pink,
-- Ice Cream Truck, Beatbox Art Car).
--
-- Transcribed verbatim from the festival's own official set-times pages
-- (hardsummer.com/lineup/set-times/day-1/ and .../day-2/), read via a
-- real browser render since the page is a client-rendered React app --
-- raw HTML/basic fetch tools only ever returned the default (Saturday)
-- tab's content. Both start AND end times are explicitly published for
-- every set on both days -- nothing here is inferred/estimated.
--
-- start_min/end_min are relative to each day's FESTIVAL_DAYS startMin
-- (both days: 2:00 PM / 840 min since midnight -- every stage's
-- published start time on both days).

insert into festival_sets (id, festival_id, day_id, artist, stage_id, start_min, end_min, match, genre, sounds_like, sources) values
(2600, 'hard-summer', 'sat', 'Quinn Blake', 'hard', 0, 60, null, null, null, '{}'),
(2601, 'hard-summer', 'sat', 'Bushbaby', 'hard', 60, 130, null, null, null, '{}'),
(2602, 'hard-summer', 'sat', 'BOLO', 'hard', 135, 200, null, null, null, '{}'),
(2603, 'hard-summer', 'sat', 'Chris Lorenzo', 'hard', 205, 285, null, null, null, '{}'),
(2604, 'hard-summer', 'sat', 'Mau P', 'hard', 285, 375, null, null, null, '{}'),
(2605, 'hard-summer', 'sat', 'Kali Uchis', 'hard', 416, 480, null, null, null, '{}'),
(2606, 'hard-summer', 'sat', 'SHAKING', 'harder', 0, 60, null, null, null, '{}'),
(2607, 'hard-summer', 'sat', 'Jon Casey', 'harder', 60, 120, null, null, null, '{}'),
(2608, 'hard-summer', 'sat', 'Mary Droppinz', 'harder', 120, 190, null, null, null, '{}'),
(2609, 'hard-summer', 'sat', 'RØZ', 'harder', 190, 265, null, null, null, '{}'),
(2610, 'hard-summer', 'sat', 'Tokischa', 'harder', 275, 320, null, null, null, '{}'),
(2611, 'hard-summer', 'sat', 'Brutalismus 3000', 'harder', 335, 395, null, null, null, '{}'),
(2612, 'hard-summer', 'sat', 'Charlotte de Witte', 'harder', 405, 480, null, null, null, '{}'),
(2613, 'hard-summer', 'sat', 'DJ Warning', 'green', 0, 60, null, null, null, '{}'),
(2614, 'hard-summer', 'sat', 'Lovefoxy', 'green', 60, 120, null, null, null, '{}'),
(2615, 'hard-summer', 'sat', 'X CLUB. B2B ATRIP', 'green', 120, 210, null, null, null, '{}'),
(2616, 'hard-summer', 'sat', 'Pegassi', 'green', 210, 270, null, null, null, '{}'),
(2617, 'hard-summer', 'sat', 'Anetha', 'green', 270, 330, null, null, null, '{}'),
(2618, 'hard-summer', 'sat', 'Hannah Laing', 'green', 330, 405, null, null, null, '{}'),
(2619, 'hard-summer', 'sat', 'Interplanetary Criminal B2B Main Phase', 'green', 405, 480, null, null, null, '{}'),
(2620, 'hard-summer', 'sat', 'Cquestt', 'purple', 0, 60, null, null, null, '{}'),
(2621, 'hard-summer', 'sat', 'Nick León', 'purple', 60, 120, null, null, null, '{}'),
(2622, 'hard-summer', 'sat', 'Six Sex', 'purple', 130, 170, null, null, null, '{}'),
(2623, 'hard-summer', 'sat', 'Confidence Man', 'purple', 190, 240, null, null, null, '{}'),
(2624, 'hard-summer', 'sat', 'salute', 'purple', 250, 330, null, null, null, '{}'),
(2625, 'hard-summer', 'sat', 'Zack Fox', 'purple', 330, 405, null, null, null, '{}'),
(2626, 'hard-summer', 'sat', '¥ØU$UK€ ¥UK1MAT$U', 'purple', 405, 480, null, null, null, '{}'),
(2627, 'hard-summer', 'sat', 'DREYA V', 'pink', 0, 60, null, null, null, '{}'),
(2628, 'hard-summer', 'sat', 'Brunello', 'pink', 60, 120, null, null, null, '{}'),
(2629, 'hard-summer', 'sat', 'Locklead', 'pink', 120, 180, null, null, null, '{}'),
(2630, 'hard-summer', 'sat', 'Luke Alessi', 'pink', 180, 240, null, null, null, '{}'),
(2631, 'hard-summer', 'sat', 'Omar+', 'pink', 240, 300, null, null, null, '{}'),
(2632, 'hard-summer', 'sat', 'DJ Seinfeld B2B Luuk van Dijk', 'pink', 300, 390, null, null, null, '{}'),
(2633, 'hard-summer', 'sat', 'Maceo Plex', 'pink', 390, 480, null, null, null, '{}'),
(2634, 'hard-summer', 'sat', 'Naomi Green', 'icecreamtruck', 0, 60, null, null, null, '{}'),
(2635, 'hard-summer', 'sat', 'Gay Felony', 'icecreamtruck', 60, 120, null, null, null, '{}'),
(2636, 'hard-summer', 'sat', 'debbiesthuglife', 'icecreamtruck', 120, 210, null, null, null, '{}'),
(2637, 'hard-summer', 'sat', 'Mesmé', 'icecreamtruck', 210, 300, null, null, null, '{}'),
(2638, 'hard-summer', 'sat', 'Lake Hills B2B Ønyx', 'icecreamtruck', 300, 390, null, null, null, '{}'),
(2639, 'hard-summer', 'sat', 'Capes', 'icecreamtruck', 390, 480, null, null, null, '{}'),
(2640, 'hard-summer', 'sat', 'Montique', 'beatbox', 0, 60, null, null, null, '{}'),
(2641, 'hard-summer', 'sat', 'Sim Ivy', 'beatbox', 60, 120, null, null, null, '{}'),
(2642, 'hard-summer', 'sat', 'Small (danny g luvs u B2B Bori)', 'beatbox', 120, 210, null, null, null, '{}'),
(2643, 'hard-summer', 'sat', 'DJ Kita', 'beatbox', 210, 300, null, null, null, '{}'),
(2644, 'hard-summer', 'sat', 'Spiñorita', 'beatbox', 300, 390, null, null, null, '{}'),
(2645, 'hard-summer', 'sat', 'DJ Blackmarket', 'beatbox', 390, 480, null, null, null, '{}'),
(2646, 'hard-summer', 'sun', 'Strawbry', 'hard', 0, 65, null, null, null, '{}'),
(2647, 'hard-summer', 'sun', '1tbsp', 'hard', 65, 140, null, null, null, '{}'),
(2648, 'hard-summer', 'sun', 'Hyperbeam', 'hard', 140, 230, null, null, null, '{}'),
(2649, 'hard-summer', 'sun', 'Snow Strippers', 'hard', 245, 280, null, null, null, '{}'),
(2650, 'hard-summer', 'sun', 'Sammy Virji', 'hard', 300, 375, null, null, null, '{}'),
(2651, 'hard-summer', 'sun', 'Knock2 B2B Zedd', 'hard', 405, 480, null, null, null, '{}'),
(2652, 'hard-summer', 'sun', 'KsoFresKo', 'harder', 0, 60, null, null, null, '{}'),
(2653, 'hard-summer', 'sun', 'Canary Yellow', 'harder', 60, 130, null, null, null, '{}'),
(2654, 'hard-summer', 'sun', 'FIFI', 'harder', 130, 200, null, null, null, '{}'),
(2655, 'hard-summer', 'sun', 'Oppidan', 'harder', 200, 270, null, null, null, '{}'),
(2656, 'hard-summer', 'sun', 'After Midnight', 'harder', 270, 360, null, null, null, '{}'),
(2657, 'hard-summer', 'sun', 'RL Grime', 'harder', 360, 420, null, null, null, '{}'),
(2658, 'hard-summer', 'sun', 'DJ Snake (Hip Hop Set)', 'harder', 420, 480, null, null, null, '{}'),
(2659, 'hard-summer', 'sun', 'Etari', 'green', 0, 60, null, null, null, '{}'),
(2660, 'hard-summer', 'sun', 'DJ Fuckoff', 'green', 60, 120, null, null, null, '{}'),
(2661, 'hard-summer', 'sun', 'Alarico B2B Yanamaste', 'green', 120, 210, null, null, null, '{}'),
(2662, 'hard-summer', 'sun', 'Adiel B2B Quest', 'green', 210, 330, null, null, null, '{}'),
(2663, 'hard-summer', 'sun', 'VTSS', 'green', 330, 405, null, null, null, '{}'),
(2664, 'hard-summer', 'sun', 'Amelie Lens', 'green', 405, 480, null, null, null, '{}'),
(2665, 'hard-summer', 'sun', 'fun2bjane', 'purple', 0, 45, null, null, null, '{}'),
(2666, 'hard-summer', 'sun', '10cust', 'purple', 45, 100, null, null, null, '{}'),
(2667, 'hard-summer', 'sun', 'underscores', 'purple', 110, 150, null, null, null, '{}'),
(2668, 'hard-summer', 'sun', 'Frost Children', 'purple', 160, 215, null, null, null, '{}'),
(2669, 'hard-summer', 'sun', 'MCR-T', 'purple', 220, 280, null, null, null, '{}'),
(2670, 'hard-summer', 'sun', 'Shygirl presents Club Shy', 'purple', 280, 340, null, null, null, '{}'),
(2671, 'hard-summer', 'sun', '2hollis', 'purple', 350, 395, null, null, null, '{}'),
(2672, 'hard-summer', 'sun', 'B3K B2B Boys Noize', 'purple', 410, 480, null, null, null, '{}'),
(2673, 'hard-summer', 'sun', 'Cole Terrazas', 'pink', 0, 60, null, null, null, '{}'),
(2674, 'hard-summer', 'sun', 'Miluhska', 'pink', 60, 120, null, null, null, '{}'),
(2675, 'hard-summer', 'sun', 'Ranger Trucco', 'pink', 120, 210, null, null, null, '{}'),
(2676, 'hard-summer', 'sun', 'Miguelle & Tons', 'pink', 210, 300, null, null, null, '{}'),
(2677, 'hard-summer', 'sun', 'Tiga', 'pink', 300, 390, null, null, null, '{}'),
(2678, 'hard-summer', 'sun', 'Vintage Culture', 'pink', 390, 480, null, null, null, '{}'),
(2679, 'hard-summer', 'sun', 'Adult Hits', 'icecreamtruck', 0, 60, null, null, null, '{}'),
(2680, 'hard-summer', 'sun', 'Bahar Khadem', 'icecreamtruck', 60, 120, null, null, null, '{}'),
(2681, 'hard-summer', 'sun', 'Samwise', 'icecreamtruck', 120, 210, null, null, null, '{}'),
(2682, 'hard-summer', 'sun', 'Bianca Oblivion B2B Star Eyes', 'icecreamtruck', 210, 300, null, null, null, '{}'),
(2683, 'hard-summer', 'sun', 'Mez Monty B2B Shane Thomas', 'icecreamtruck', 300, 390, null, null, null, '{}'),
(2684, 'hard-summer', 'sun', 'Oscar Osorio', 'icecreamtruck', 390, 480, null, null, null, '{}'),
(2685, 'hard-summer', 'sun', 'Chloe404 B2B Kyle Arthur', 'beatbox', 0, 60, null, null, null, '{}'),
(2686, 'hard-summer', 'sun', 'Edge Control', 'beatbox', 60, 120, null, null, null, '{}'),
(2687, 'hard-summer', 'sun', 'Cerulo', 'beatbox', 120, 210, null, null, null, '{}'),
(2688, 'hard-summer', 'sun', 'Lily Ardalan', 'beatbox', 210, 300, null, null, null, '{}'),
(2689, 'hard-summer', 'sun', 'PITCHBLACK', 'beatbox', 300, 390, null, null, null, '{}'),
(2690, 'hard-summer', 'sun', 'FLABBERGAST', 'beatbox', 390, 480, null, null, null, '{}');
